### ISSUE TITLE
Possible memory leak?

### ISSUE THREAD

**Issue by mperham** [contribsys/faktory#100]
I demo'd Faktory to a bunch of people at Rubyconf and had it processing jobs all weekend.  During that time, the Faktory RSS went from 9MB to 300MB after about 300,000 jobs processed.  The RSS seemed to inflate linear with jobs processed so I'm assuming there is some leak in the push, fetch or ack commands, likely a RocksDB C++ structure that is not being Destroy()'d.  Investigate.

**Comment by mperham** [comment]
Pushing 100,000 jobs to Faktory twice:

Empty: 21852
100,000: 45604
200,000: 68796

Popping and acking the jobs just increases the memory usage even more.  I noticed that restarting Faktory with a large amount of queue tombstones that need pruning leads to much larger RSS upon completion of bootup.  In other words, RocksDB appears to be running an initial compaction upon OpenDB and it inflates RSS from 15MB to 70MB.  This could be due to normal I/O buffer allocation or could be some sort of leak but this case is outside of Faktory.

**Comment by thebadmonkeydev** [comment]
This was posted a couple of days ago over on RocksDB https://github.com/facebook/rocksdb/issues/3216 it might be related.  To add my 2 cents, I've got an instance running in docker on an EC2 instance right now that only has about 40 processed jobs, but if left to it's own devices I've seen it climb to a container usage of ~800 MB.  There were workers polling that entire time which would support a claim of a memory leak on reads from RocksDB (given the low amount of actual jobs pushed).  Hopefully that info is somehow helpful.

**Comment by christian-esken** [comment]
Here is a graph on the memory usage of this RocksDB based service.
- Red = Used
- Yellow = Cached
- Green = Free
- Swap is not in the graph, but it usually is eaten up within 1h  after start of the service

![memory on rocksdb prefix-seek and deleterange](https://user-images.githubusercontent.com/3432131/33653183-7c47dc0c-da6c-11e7-8a1a-a008a221efb9.png)

- 11/30 16:00 Start of service, configured to use Iterators for a short amount of time =>Many iterators are created. I see much memory loss
- 12/1 Some restarts. At 16:00 starting the service, configured to use Iterators for a longer amount of time =>Fewer iterators are created. I see less memory loss
- 12/3 and after: Two more automatic restarts, as memory ran out

**Comment by christian-esken** [comment]
FYI I added a graph on memory consumption on facebook/rocksdb#3216

**Comment by mperham** [comment]
Looks like write_buffer_size has a big effect here.  Default is 64MB, currently it is set to 16MB:

RSS after processing 100,000 jobs with various sizes:

64MB - 95MB
16MB - 70MB
4MB - 48MB
2MB - 40MB
1MB - 33MB

Since wall time is unchanged, a smaller buffer isn't having much effect aside from taking memory.  It's likely this buffer is not very useful at our usage level or patterns.  I'm going to bump it down to 2MB.

**Comment by mperham** [comment]
With the new settings, here's the memory usage when processing 2 million jobs:

```
200000    RSS 64792
400000    RSS 91532
600000    RSS 112228
800000    RSS 239560
1000000    RSS 170280
1200000    RSS 184860
1400000    RSS 279460
1600000    RSS 218048
1800000    RSS 223328
2000000    RSS 237912
```

There's a strange dip at 1.6m that bodes well, possible GC within Rocksdb.

**Comment by jbielick** [comment]
Safe to close this one? Or do we want to watch current usage for the same behavior?

**Comment by mperham** [comment]
Definitely no longer applicable.
