### ISSUE TITLE
Cron jobs

### ISSUE THREAD

**Issue by jweslley** [contribsys/faktory#104]
What about cron jobs? It is an important feature.

**Comment by cdrx** [comment]
I wrote a tool that triggers Faktory jobs on a (cron based) schedule, but haven't a chance to polish and publish it yet. Would be nice if it was built in though!

**Comment by jweslley** [comment]
@cdrx Can you create a pull request? We can work together to make it happens!

**Comment by mperham** [comment]
Cron is likely a commercial feature.  I won't accept any PRs for it in the OSS version.

**Comment by cdrx** [comment]
@mperham would you prefer I not publish any scheduler?

**Comment by mperham** [comment]
I would certainly prefer no competition but I'm not going to tell you what to do.  Your choice is your own and you are free to do as you wish so long as you follow the GPL license.

You can fork the repo and maintain your own set of additional features; almost every commercial Sidekiq feature I sell is also available as a free OSS extension.  The difference is that I get the users who are willing to pay money for a curated set of well-supported features.  People who make their own free OSS extensions almost always burn out after a year or two supporting free users.  Free support is fun for the first few dozen issues but gets real old after the 100th...  tl;dr: TNSTAAFL.

**Comment by jonhoo** [comment]
@mperham This might not be the right place to discuss, but is there a particular reason you've chosen to go with a "paid features" model rather than "pay for commercial use" (like the many projects out there with "community editions")?

**Comment by mperham** [comment]
Can you point me to successful projects or businesses that are using that model?

**Comment by cdrx** [comment]
The Caddy http server is paid for commercial use

**Comment by jonhoo** [comment]
Sure:

 - [MS Visual Studio](https://www.visualstudio.com/vs/community/):
   >  If you are an enterprise, your employees and contractors may not use the software to develop or test your applications, except for open source and education purposes as permitted above.
 - [Atlassian's Jira](https://www.atlassian.com/software/views/open-source-license-request) is free for use by open-source projects and charitable organizations.

In a related vein, a number of large projects provide a basically fully-featured standalone server available for free, and then sell infrastructure around + provide paid support. The infrastructure stuff is generally along the lines of high availability, cross data center replication, granular user permissions, additional testing, SSL, etc.

 - [MySQL](https://www.mysql.com/products/community/)
 - [Docker](https://www.docker.com/community-edition)
 - [MongoDB](https://www.mongodb.com/download-center#community)

**Comment by spinx** [comment]
@mperham Count us in for enterprise edition of faktory 👍 hope it lands soon!

**Comment by mperham** [comment]
@jonhoo Thanks for the examples, there's definitely different business models and different end goals for those projects.  VC-backed companies want to give their products away for free to the little guys and chase 7 figure deals with large banks and other enterprise deals (e.g. Docker, Mongo, Hashicorp).

I have no desire to play that game and prefer to build simple, well documented products that require little support and "just work".  If I charge for support, for instance, I'm incentivized to build a hard to use product with little documentation to maximize the need for paid support.  It's certainly possible I might have exemptions for non-profits, students or other niches but that's a secondary goal for the time being.

**Comment by jonhoo** [comment]
I guess at a higher level, I'm mostly arguing that support for cron jobs seems like an odd choice for an enterprise-only feature; it seems like something that many non-enterprise users would find extremely useful. When I think of enterprise features, I think more along the lines of high availability, clustering, sharding, replication, user permissions, etc.

**Comment by cdrx** [comment]
I've published a cron scheduler here: https://github.com/cdrx/faktory_cron -- its basic but works for me. 

I don't want to undermine any of the planned commercial features for Faktory, and I don't think an external OSS scheduler does that -- having a Pro version baked directly into Faktory will always be the better option, one that I would likely use myself. 

My hope is that if this is a feature that a lot of people want in order to use Faktory today, then it might grow the community in the short term.

**Comment by mperham** [comment]
:+1: perfectly fine with me.
