### ISSUE TITLE
Workflows

### ISSUE THREAD

**Issue by spinx** [contribsys/faktory#108]
Enterprise feature request.

There’s a go project that has this implemented:
https://github.com/RichardKnop/machinery#workflows

Even just chains would be incredibly useful.

**Comment by mperham** [comment]
Sidekiq Pro has a notion of [Batches](https://github.com/mperham/sidekiq/wiki/Batches); this is definitely on the roadmap.

**Comment by milesalex** [comment]
Any udate on this?

**Comment by mperham** [comment]
I plan on working on this this summer but have no more precise timeline.

**Comment by mperham** [comment]
https://github.com/contribsys/faktory/wiki/Ent-Batches

**Comment by mperham** [comment]
Faktory Enterprise with the batches feature is now available.
