### ISSUE TITLE
Remove logrus dependency

### ISSUE THREAD

**Issue by mperham** [contribsys/faktory#11]
AFAIK Logrus is not a huge dependency and he's stating he doesn't have time to support the project anymore, we should fork the basic functionality into the util package.  Remember to preserve the copyright notice to keep to the MIT license.

**Comment by titpetric** [comment]
May I suggest using https://github.com/apex/log - the sending of the log data to some friendly external service (papertrail etc.) is a nice convenience. It does have a logrus inspired api, but I suspect it's not exactly a drop-in replacement.

**Comment by mperham** [comment]
Excellent suggestion and that would give me an excuse to use TJ's code.

**Comment by mperham** [comment]
#62

**Comment by agnivade** [comment]
This can be closed now. You should use the magic words in the PRs to auto close issues - https://help.github.com/articles/closing-issues-using-keywords/
