### ISSUE TITLE
Handling downtime(crash or restart)

### ISSUE THREAD

**Issue by lizdeika** [contribsys/faktory#110]
Hello,

I would like to understand what happens if faktory itself gets into a situation of downtime, let's say for half a minute because it was a need for a restart or it crashed and some supervisor/monit thingie started it again.

What happens to the job enqueued from ruby for example.
When using sidekiq jobs would be enqueued to redis and run when sidekiq is up.

What about faktory, where do the jobs go when faktory server is down?

Thank You

**Comment by mperham** [comment]
Like Redis, Faktory persists all data to disk.  If you restart Faktory, all your job data should be right there when you restart.  Your workers might raise network errors; it's their responsibility to reconnect once Faktory has restarted.

**Comment by lizdeika** [comment]
Reconnecting is not an issue.
Where do the enqueued jobs go when faktory is down?
In case of sidekiq they would go to redis and would be later handled by sidekiq.

**Comment by mperham** [comment]
The enqueued jobs are saved in a file on disk.
