### ISSUE TITLE
Force explicit passwords in production mode

### ISSUE THREAD

**Issue by mperham** [contribsys/faktory#113]
To increase security, I think it might be reasonable to force the user to configure a password in production mode.

With `faktory -e production`, you must set `FAKTORY_PASSWORD=` to use no password.  Reasonable?

**Comment by mperham** [comment]
To be clear, Faktory allows you to configure a password in two ways:

* `FAKTORY_PASSWORD=s0m3p4ssw0rd faktory -e production ...`
* The contents of `/etc/faktory/password`

**Comment by cdrx** [comment]
I'm strongly in favour of requiring `FAKTORY_PASSWORD` to be set in a production environment, but I think it would be better to have an explicit environment variable to start Faktory without a password, something like: `FAKTORY_SKIP_PASSWORD=yes`.

Two reasons, both from an ops perspective:
* I expect there are some orchestration systems that wont let you set an environment variable without a value
* It's easier to accidentally set the password to "" than it is to accidentally set FAKTORY_SKIP_PASSWORD=yes
