### ISSUE TITLE
Protocol change: PUSH response

### ISSUE THREAD

**Issue by mperham** [contribsys/faktory#115]
Today the PUSH command returns OK or an ERR if there is an internal server problem.  There is a third class of possible responses: PUSH denied.  For instance, if the JSON payload is bad, that's not an internal server error but a producer problem.  If the PUSH is denied due to unique job logic (i.e. an identical job is already enqueued or in progress), the response needs to inform the producer that the job was not enqueued.  These cases are not technically errors.  What should the response be?

Today Sidekiq returns the JID if the job is enqueued and returns nil if the job was not enqueued.

**Comment by jonhoo** [comment]
I believe the response should still be a redis RESP Error response (i.e., it should start with `-`), but then its contents should probably be a JSON payload. A well-typed error response wouldn't be a bad idea in general (`FETCH`, `FAIL`, `ACK`, etc., also have the same issue). I'd recommend re-using something other people have though through. Perhaps the JSON-RPC [Error object](http://www.jsonrpc.org/specification#error_object)?

**Comment by mperham** [comment]
Well, I'm ambivalent because it's not really an error, more of a validation issue.  Errors are unexpected and usually represented as exceptions that unwind the stack, e.g. network is down.  This case is more of an expected but typically rare issue and one that should be explicitly handled by the client, not rescued as an exception.

I feel the response should be trivariant:

* "+OK" - Job enqueued as normal
* "-ERR" - Internal, unexpected problem
* "+{...}" - JSON hash like that Error object with error code and message, e.g. `{"errcode":123,"message":"Job not unique"}`.

The error code would allow easy case logic.

**Comment by jonhoo** [comment]
I don't know... To me, what you're describing is like a program-level exception. An error is something that is returned by an API when something is wrong. An a validation issue is something being wrong. Think of something like the HTTP status codes. 4XX is considered "client error", and 5XX is "server error"; they're both returned as errors to the client. And if we make *all* error responses have a well-defined form (which I think we should), then the matching isn't made any more difficult.

**Comment by cdrx** [comment]
`+{"errcode":123,"message":"Job not unique"}` seems like a waste of bytes and CPU cycles to encode/decode JSON for this.

Perhaps just `-ERR 123 job not unique`?

Or even `-NOTUNIQUE`, which closer maps to how Redis reports errors. 

Any reply that starts with a `+` should indicate that the job was queued, feels a bit odd to have a failure reply (even if for validation reasons) begin with `+`

**Comment by mperham** [comment]
Using unique error names where possible, e.g. -NOTUNIQUE, or -ERR for generic internal errors seems like a fine idea.

**Comment by mperham** [comment]
My only question here is when does the worker turn an error result into an exception vs a failure return value?  For example, if it gets `-BACKPRESSURE Queue full` the worker should probably raise an exception.  If it gets `-NOTUNIQUE` it probably **shouldn't** raise an error.  None of Sidekiq's unique jobs plugins raise an error in this instance, they just silently drop the PUSH and return nil to indicate the job wasn't pushed.

**Comment by mperham** [comment]
I like Jon's comparison between 400 and 500 errors in HTTP.  Often the question is: can or should the client do anything to recover from this error?  Yes -> failure result.  No -> exception.  But first we need some way for the workers/clients to distinguish between "4xx" and "5xx" types of errors.

**Comment by jonhoo** [comment]
There are a number of ways to expose this in the API. I think what I'll end up doing in the rust one is to have the return value be of type `Result<(), PushError>` where `PushError` is:
```rust
enum PushError {
    QueueFull,
    NotUnique,
    ServerError(io::Error),
}
```
That way, the caller can easily determine what they want to do. There is an argument for making `NotUnique` be an `Ok` response, but I think that's misleading at best. The action the user wanted to take did not complete in the expected way, which is what an error signifies to me.

How this maps to other languages is a good question: what should be exposed as an exception, and what should just return an "error-like" value instead? I don't have a good answer. I *think* I/O errors should be exceptions. The queue being full and the job not being unique both seem to me like they ought not to be exceptions (because they aren't "exceptional"). Server errors (like incorrect JSON encoding) could go either way, though I think I'd call them exceptions.

**Comment by jonhoo** [comment]
Re 4XX vs 5XX, see `code` in the JSON-RPC Error object type: http://www.jsonrpc.org/specification#error_object

**Comment by cdrx** [comment]
I think error vs exception should be decided by the language norms of the client. Its normal to raise an exception in Python, but I wouldn't expect a library to panic in Go. 

As long as errors are named or numbered in some unique way then the client can at least choose to change its behaviour if it knows how to deal with a specific error.

**Comment by jonhoo** [comment]
BTW: we should probably tag issues (and PRs) like this which affect the protocol with a GitHub tag for visibility. This particular change happens to be backwards compatible, but still a useful distinction. A protocol change that is not backwards compatible should bump the protocol version. All such changes should also obviously update the spec.
