### ISSUE TITLE
Evaluate Badger

### ISSUE THREAD

**Issue by mperham** [contribsys/faktory#119]
RocksDB is a pretty painful dependency due to C++: it forces a  more complex build, makes finding memory leaks much harder, and is a black-box when it comes to profiling and tuning.

Badger is a new storage layer written in Go which explicitly bills itself as a competitor to RocksDB.  Right now the load test (`make load`) reports about 5000 job/sec.  If we can stay near that or better, I'd seriously consider moving.

https://github.com/dgraph-io/badger

**Comment by cdrx** [comment]
I have this working, but I'm not sure if it will be faster. Badger doesn't have any concept of column families / tables, so all keys go into the same namespace. 

I'll fix up the bugs and if I can get the performance anywhere near the current levels, I'll push the branch somewhere everyone can review.

**Comment by mperham** [comment]
we could open issues for that and the merge operator for stats to see if they have something on their roadmap.

**Comment by mperham** [comment]
Without column families, the solution is to prefix each different type of data with a char code: "q" for queue elements, "s" for scheduled, "w" for working, etc.  Then when you want to iterate, you only iterate items that start with that code.

**Comment by cdrx** [comment]
That's the solution I used. It does work and I can get performance that matches RocksDB, but only turning the `SyncWrites` option off. Changes are made in RAM and periodically written to disk, so a crash could lead to some data loss. I think this is different to RocksDB, which writes to disk before confirming the `Set`?

**Comment by mperham** [comment]
RocksDB appends to a WAL, basically the fastest I/O you can do, before returning.  We can point the Badger folks to our benchmark and ask if they have any suggestions for tuning.

It should be noted that Redis does the same thing as Badger, updates in-memory and then persists asynchronously every N seconds so Faktory is technically safer than Redis today.

**Comment by cdrx** [comment]
Is that safety worth the pain of RocksDB? We would make `SyncWrites` a user configuration option, giving the end user the choice of speed vs reliability. 

There are some things that could be done to boost the performance:

- my current implementation wraps all the Badger calls in a transaction per call, which is not efficient - there is time to be saved by wrapping the queue get / delete & working set into one tx
- coalesce database updates and run them every ??ms
- skip writing the job to the queue if we have a waiting worker, push it straight into the working set

I'm pretty sure these things would bring it above the performance of RocksDB.

If you think its worth persevering with I'll tidy it up and push into into a branch.

**Comment by cdrx** [comment]
I was curious what the overhead of Rocks was, so I wrote a memory backed Store / Queue / SortedSet (nothing sophisticated, just some decoration around `map[string][]byte`). Using Rocks my laptop runs about 6k jobs/s, using an in memory store it runs 12k jobs/s, so about 50%.

**Comment by mperham** [comment]
I consider that pretty low overhead, considering the guarantees RocksDB provides.  What does Badger give us in the same benchmark?

**Comment by cdrx** [comment]
With SyncWrites off, 6.2k/s. With it on (same guarantees as RocksDB) it’s about 4k/s. Pretty sure those numbers could easily be improved.

**Comment by mperham** [comment]
I’m happy with that performance esp since we can profile and tune much easier than rocks. Would love to see a PR.

**Comment by cdrx** [comment]
I'll tidy this up and open a PR 👍

**Comment by favadi** [comment]
@mperham any change you will accept a PR to abstract storage operations so, if we want, faktory can support multiple storage engines?

**Comment by mperham** [comment]
It already does. That’s the storage package.

**Comment by mperham** [comment]
@cdrx any ETA on this?  It would be fun to play with Badger over the holidays.

**Comment by mperham** [comment]
I rewrote much of the storage package to use Badger but it still does not have a mature Merge implementation needed for counters/stats.

**Comment by mperham** [comment]
Also missing a high-level backup API, similar to Rocks.

**Comment by mperham** [comment]
We already discussed this. Your implementation uses one goroutine per key which doesn’t scale. Please correct me if things have changed.

**Comment by manishrjain** [comment]
Thanks for reminding, been on my TODO list. I'll see if I get some cycles to fix that up. Shouldn't be too much effort.

https://github.com/dgraph-io/badger/issues/373
