### ISSUE TITLE
Negative retries?

### ISSUE THREAD

**Issue by jagthedrummer** [contribsys/faktory#123]
We somehow got one of our Faktory instances into a state where it's showing negative retries in the web UI.

![screen shot 2017-12-11 at 8 48 32 pm](https://user-images.githubusercontent.com/58702/33864930-bd0ae5e4-deb4-11e7-9f52-d10a4320c16d.png)

I haven't been able to nail down exact repro steps yet, but I suspect that it's probably a timing issue as I think it's only happened when we manually delete jobs that are fairly early in their retry cycle, and when I've seen the number go further negative I've noticed that some jobs that should have been deleted from the retry queue are still there. I suspect that it's something like this:

* the UI shows that there are jobs to be retried
* as I'm viewing the page and clicking "select all" and "delete" some jobs are actually retried (maybe giving them a new job id?)
* the "delete" request finally makes it from my browser to the server (but maybe includes job ids that no longer exist?)
* the server tries to delete the retries that correspond to the submitted job ids (and maybe decrements a counter somewhere?)

I'd be happy to post debug information or a dump of the database if that would be helpful.

**Comment by jagthedrummer** [comment]
An additional interesting note is that when the retry count is negative the web UI will show pagination options that seem to lead to a nearly endless supply of 0 item pages. If I click the "last page" button I end up on page 737,869,762,948,382,080 (URL fragment = `/retries?page=737869762948382080`).

**Comment by mperham** [comment]
There's definitely a race condition.  We don't have a mutex on the Retry set so the Web UI can be iterating through the selected keys and removing them one-by-one while the task runner is executing the regular retry "remove and enqueue" process.  This can lead to a double removal. Unfortunately RocksDB doesn't tell us if the delete succeeded or was a no-op so we can tell if there was a double removal.  There's a couple of things we can do:

1. Add a mutex and have all operations use it when calling into Rocks.
2. Add a check for negative size and recount the entries if it goes negative.  This is a bandaid and I'm worried there would be other ramifications if the size is positive but still incorrect.

**Comment by mperham** [comment]
Master now includes a minutely check for improper counts and resets them if they are found to be invalid.
