### ISSUE TITLE
Cannot connect with any client

### ISSUE THREAD

**Issue by nmaggioni** [contribsys/faktory#125]
I'm unable to connect with any client (be it a producer or a worker) - they seem to be trying to open up a TCP socket but receive no reply to read.

I'm running Faktory locally as per the docs, **v1.6.1** _(running v1.6.0 makes no difference)_:

```bash
docker run --rm -it -p 127.0.0.1:7419:7419 -p 127.0.0.1:7420:7420 contribsys/faktory:0.6.1
```

Example code from [cdrx/faktory_worker_python](https://github.com/cdrx/faktory_worker_python/blob/master/examples/producer.py):

```python
import faktory

print("Connecting to Faktory...")
with faktory.connection() as client:
    print("Client connected.")
    client.queue('test', args=(1, 2), queue='default')
    print("Job enqueued.")
```

It simply hangs at "`Connecting to Faktory...`", and Ctrl+C'ing out of it produces this stacktrace:

```python
Connecting to Faktory...
^CTraceback (most recent call last):
  File "producer.py", line 4, in <module>
    with faktory.connection() as client:
  File "/usr/lib64/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/tmp/faktory/python/.env/lib/python3.6/site-packages/faktory/__init__.py", line 15, in connection
    c.connect()
  File "/tmp/faktory/python/.env/lib/python3.6/site-packages/faktory/client.py", line 21, in connect
    self.is_connected = self.faktory.connect()
  File "/tmp/faktory/python/.env/lib/python3.6/site-packages/faktory/_proto.py", line 68, in connect
    ahoy = next(self.get_message())
  File "/tmp/faktory/python/.env/lib/python3.6/site-packages/faktory/_proto.py", line 152, in get_message
    more = socket.recv(self.buffer_size)
KeyboardInterrupt
```

It looks like it is waiting for content over the socket but receives none. The same behavior is observed with the [jbielick/faktory_worker_node](https://github.com/jbielick/faktory_worker_node) for Node:

```javascript
const faktory = require("faktory-worker");

faktory.register('test', (id, size) => {
    console.log(`Faking processing of job with ID ${id} and size ${size}`);
});

console.log('Registering worker...');
faktory.work();
```

---

The amount of connections in Faktory's WebUI does not change from 0 and no job is enqueued, neither in the default queue nor in the `test` one. Netcat'ing port 7419 leaves the connection open - the server does not send any data and the connection is closed as soon as I try to send anything.

Am I missing something obvious here? I'm sticking to the docs as much as possible.

**Comment by cdrx** [comment]
Are you running the workers on the same host as the faktory Docker instance?

**Comment by nmaggioni** [comment]
Very same development laptop, running Docker 17.10.

I also tried running the Faktory server on a remote machine and use each library's respective environment variables to set the connection url, but to no avail.

**Comment by cdrx** [comment]
Is it a Mac?

**Comment by nmaggioni** [comment]
Linux (the distro is Manjaro, in case that matters), kernel 4.12.14.

**Comment by cdrx** [comment]
Can you try running Faktory like this:

```
docker run --rm -it -p 7419:7419 -p 7420:7420 contribsys/faktory:0.6.1 -b :7419
```

does that work for you?

**Comment by nmaggioni** [comment]
It works! :tada: 

But isn't the port specification already included in the [Dockerfile](https://github.com/contribsys/faktory/blob/master/Dockerfile#L34)? `0.0.0.0:7419` should have the same effect of `:7419`, as far as I know... Maybe something is screwing with Docker's networking in my (default) config?

**Comment by cdrx** [comment]
Great

`-p 7419:7419 -p 7420:7420` controls the port mapping for Docker itself, but the missing piece of the puzzle was `-b :7419` which forces Faktory to bind to the external address, inside the container.

This is fixed for the next release of Faktory, where `-b :7419` is the default option.

**Comment by nmaggioni** [comment]
Great news, thanks for the help :+1:

**Comment by smritijanaswamy** [comment]
> Great
> 
> `-p 7419:7419 -p 7420:7420` controls the port mapping for Docker itself, but the missing piece of the puzzle was `-b :7419` which forces Faktory to bind to the external address, inside the container.
> 
> This is fixed for the next release of Faktory, where `-b :7419` is the default option.



> Can you try running Faktory like this:
> 
> ```
> docker run --rm -it -p 7419:7419 -p 7420:7420 contribsys/faktory:0.6.1 -b :7419
> ```
> 
> does that work for you?

Did you mean adding this as the entry point in the docker-compose file?
