### ISSUE TITLE
WebUI doesn't respect the -b flag

### ISSUE THREAD

**Issue by cdrx** [contribsys/faktory#126]
If you run faktory with `-b localhost:7419`, the webui still binds to all interfaces

**Comment by jweslley** [comment]
@cdrx  in fact, the binding option is not for webui, but the job server. Currently, the webui binding is [hardcoded](https://github.com/contribsys/faktory/blob/master/webui/web.go#L69).  I am working in a refactoring of the webui which allows customize the binding. I will finish it before next week. ;)

**Comment by cdrx** [comment]
👍

**Comment by mperham** [comment]
0.9 will have a `-w :7420` option for web ui binding.
