### ISSUE TITLE
Return the number of jobs in each queue in the INFO command

### ISSUE THREAD

**Issue by valo** [contribsys/faktory#128]
It will be nice if the INFO command returns the number of enqueued jobs in each queue. Right the WebUI allows to see this value, but there is no API for getting that. Such information will be useful for implementing job scheduling and also for features like autoscaling.

Something like this will be useful:

```json
{  
   "server_utc_time":"05:03:59 UTC",
   "server":{  
      "used_memory_mb":"5 MB",
      "uptime":53,
      "faktory_version":"0.6.1",
      "connections":5,
      "command_count":7
   },
   "faktory":{  
      "total_queues":2,
      "total_processed":4019,
      "total_failures":2700,
      "total_enqueued":40560,
      "enqueued_jobs": {
        "default": 0,
        "my_fancy_queue": 2
      },
      "tasks":{  
         "Workers":{  
            "size":1,
            "reaped":0
         },
         "Scheduled":{  
            "wall_time_sec":0.0040118,
            "size":0,
            "enqueued":0,
            "cycles":10
         },
         "Retries":{  
            "wall_time_sec":9.299e-4,
            "size":0,
            "enqueued":0,
            "cycles":10
         },
         "Dead":{  
            "wall_time_sec":0,
            "size":0,
            "enqueued":0,
            "cycles":0
         },
         "Busy":{  
            "size":0,
            "reaped":0
         }
      },
      "default_size":0
   }
}
```

**Comment by mperham** [comment]
One note: `default_size` is the size of the default queue.  If you stick with using it for most of your jobs, you can alert on that attribute.

**Comment by thapakazi** [comment]
Stumbled up here, **to know if we have any plans for these.** 
We want to leverage faktory to schedule the workers, but I think we are missing the apis like in: SIDEKIQ.

**Comment by mperham** [comment]
INFO now returns the size of all queues.

**Comment by thapakazi** [comment]
What about the latency details of a jobs in a queue, can we fetch it from redis too ?

**Comment by mperham** [comment]
Only the default queue latency is exposed because it is costly to calculate.
