### ISSUE TITLE
Changing priority of a job

### ISSUE THREAD

**Issue by shatgupt** [contribsys/faktory#129]
I couldn't locate any document or even in code(with my limited ability to understand Go) to change priority of a job already en-queued. Is it possible right now? If not, please consider it as a feature request since it will be very useful for a case I am working on.

Bonus will be to allow changing it from WebUI since we already have a priority column there and delete operation is allowed. We can have a dropdown with values 1-9 in the priority column.

EDIT: I saw a [MoveTo](https://github.com/contribsys/faktory/blob/11eab29169be459f4a3a533c14877099e28d07b4/storage/sorted_rocksdb.go#L165) which moves across queues, maybe something like that(delete and insert again) within the same queue with updated priority?

**Comment by mperham** [comment]
It would be useful for you to tell us why you think changing priority is useful.  It's not useful for any apps I've ever implemented.

**Comment by shatgupt** [comment]
We have an application for broadcasters to upload videos/graphics and schedule them in a playlist. All videos go through a time consuming set of processing involving transcoding, a lot of QCs and thumbnail/preview generation which happen in a Sidekiq worker. Generally multiple videos are uploaded together and their priority is decided based on when they are scheduled in the playlist(today, tomorrow, day after etc). If a broadcaster decides to schedule a previously unscheduled video in today's playlist then we need to bump up its priority to process it before others. We are currently handling it using Sidekiq middleware with our own hacked up priority queue on top of Redis ZSET.

Since faktory has inbuilt support for priority queue, I thought it will be good to have the ability to update priority when you have long running jobs.

I think I can still cook up something using middleware if not enough people find it useful.

**Comment by mperham** [comment]
I'm still a little unclear.  The priority only matters while the job is enqueued and queues should almost always be empty.  Are your queues backed up often or all the time?

It sounds like you want a job to signal "start video transcoding" but to decide which video to transcode when the job is started by maintaining your own prioritized list in a database which the user can edit/adjust in real-time (e.g. your Redis ZSET).  Faktory is not designed for the job payload to be mutable.

I do plan on supporting job cancellation so you could cancel the existing job and create a new job with an updated priority but the precise details are still TBD.

**Comment by shatgupt** [comment]
> The priority only matters while the job is enqueued and queues should almost always be empty. Are your queues backed up often or all the time?

A single job takes several minutes to complete and broadcaster keeps uploading new content. So yes, my queues are not generally empty.

In general, the jobs in my queue will be of priority 4-6 but lets say I need a particular video/s(currently enqueued with priority 4) to be processed urgently, I want to be able to increase its priority to 8 so that it moves to head of the queue and is definitely the next job picked by workers.

**Comment by mperham** [comment]
It's impossible to bake this functionality into Faktory efficiently without a massive redesign.  There's several other ways to implement this efficiently:

* Keep an `urgent`  queue which is checked first before the `default` queue.  Overrides go in `urgent`.
* Keep a Redis LIST with filenames to be processed, push the filename to the HEAD to make it go next, push it to the TAIL to process it normally.  Have each job pop a filename from the HEAD when it starts and check if it is processed already.
