### ISSUE TITLE
Docker install

### ISSUE THREAD

**Issue by mperham** [contribsys/faktory#13]
Docker is a newer way of distributing an entire stack of dependencies as a single unit.  Anyone want or need a Docker install for Faktory?

**Comment by preichelt** [comment]
Checking Docker Hub was actually the first thing I did. A supported image would be great.

**Comment by zbruhnke** [comment]
@mperham do you just want this in an "official" docker image that can run as standalone? I can probably help with getting the dockerfile ready to go and getting to the right people at Docker - would want you to test it as well obviously - happy to walk you through what I did and why if it helps as well to get it there - could also potentially look at the homebrew part if noone else is helping with that already

**Comment by mperham** [comment]
@zbruhnke I'm not really Docker savvy so I would depend on the knowledge of anyone helping.  What do you think is best?  I would consider Faktory akin to Redis and distribute Faktory in the same manner.

**Comment by zbruhnke** [comment]
@mperham no problem - sounds like something I can definitely help with - I'll ping you with a first pass in the next couple of days when i free up a bit

**Comment by cjbottaro** [comment]
Vagrant boxes and Homebrew??  😳 😬

I'm also a container advocate now, though the particular implementation known as Docker brings me more pain that anything else in my life right now... but it's all we really got for now!  :v:

**Comment by vosmith** [comment]
Should this be closed via 1457d88151c43b8d0541dec92037bcdeb2299cc8 ?

**Comment by mperham** [comment]
Yep, we have an initial first pass.  We need to add support for TLS into the image but that doesn't need to hold this issue open.
