### ISSUE TITLE
Random errors

### ISSUE THREAD

**Issue by XescuGC** [contribsys/faktory#130]
Sorry for the vage title, but it's what I've found. IDK if I'm misussing the lib or it's something more internal, I could track them  down to exatly see where those errors are rised.

**Faktory:** Faktory 0.6.1
**Faktory Go Worker**: https://github.com/contribsys/faktory_worker_go/tree/afe3b649091945d6ddb78a7f310eb65f4c46553b
**OS:** I'm using the docker image on a ArchLinux

As they are random, this is all the infomration I could get:
* The main error is a `short write` (https://golang.org/pkg/io/#pkg-variables) produced on https://github.com/contribsys/faktory/blob/master/client/client.go#L362, this one is the worse because is not solved when it's retryied, once one of this is logged, everything fails, I have to restart  the workers manually.
* `ERR invalid character '{' after top-level` on https://github.com/contribsys/faktory/blob/master/client/client.go#L372
*  The  only error with  trace:
```
2018/01/02 18:03:16 http: panic serving 172.20.0.5:52098: runtime error: slice bounds out of range                                                                                             
goroutine 242 [running]:                                                                                                                                                                       
net/http.(*conn).serve.func1(0xc4203f8000)                                                                                                                                                     
   /usr/local/go/src/net/http/server.go:1697 +0xd0                                                                                                                                             
panic(0x6e3a20, 0x8fc6c0)                                                                                                                                                                      
   /usr/local/go/src/runtime/panic.go:491 +0x283                                                                                                                                               
github.com/xescugc/project/vendor/github.com/contribsys/faktory/client.readResponse(0xc42004c600, 0x100, 0xc4203f2d48, 0x6298bf, 0xc42009b6b0, 0x6bb660)                        
   /go/src/github.com/xescugc/project/vendor/github.com/contribsys/faktory/client/client.go:422 +0x4db                                                                          
github.com/xescugc/project/vendor/github.com/contribsys/faktory/client.ok(0xc42004c600, 0x741f09, 0x4)                                                                          
   /go/src/github.com/xescugc/project/vendor/github.com/contribsys/faktory/client/client.go:381 +0x2f                                                                           
github.com/xescugc/project/vendor/github.com/contribsys/faktory/client.(*Client).Push(0xc420048680, 0xc42009b600, 0xc420240960, 0x2)                                            
   /go/src/github.com/xescugc/project/vendor/github.com/contribsys/faktory/client/client.go:236 +0xc8
```
* It also happends randomly that the wokers hang (busy) for ever, but I could not point it to my code or  to the lib so just  droping it here if it rings some bells hehe.

Some questions also, because  maybe I'm misussing the lib, is it concurrent safe?  I say this because as a `Client` has  only one buffer to write (as far as read the code) could  get mixed on the https://github.com/contribsys/faktory/blob/master/client/client.go#L359  if 2 goroutines  are pushing  maybe (IDK, just guessing).

I'm sorry to not be  able to provide  more information, as it happends ramdomly IDK how to reproduce them to provide more insights about them.

**Comment by mperham** [comment]
faktory.Client is not thread-safe, it is designed to be used with a Pool, e.g.

https://github.com/contribsys/faktory_worker_go/blob/master/runner.go#L248

**Comment by XescuGC** [comment]
Ouu Boy, I'll close this issues because with the pool sems to solve the issue (as expected) I think this needs to be documented somewhere, I can do it but, where do you think it's more relevant/correct? On the worker  with the FAQ https://github.com/contribsys/faktory_worker_go#faq or on the Client wiki somewhere? If it needs to be  ofc :)

**Comment by mperham** [comment]
The godoc should definitely mention that. fwg should probably expose or document that Pool so running jobs can access it and use a client instance to create their own child jobs.

**Comment by mslagle** [comment]
@xescugc Can I get an example of the code you used for this?  I am getting the same issue and cannot fix this.

**Comment by xescugc** [comment]
Sorry @mslagle to answer that late, this is what I did:

``` go
import (
  faktory "github.com/contribsys/faktory/client"
  worker "github.com/contribsys/faktory_worker_go" 
)

pool, err := worker.NewChannelPool(0, 5, func() (worker.Closeable, error) {
 return faktory.Open()
})
```

And then with the pool you do:

```go
conn, err := c.pool.Get()
pc := conn.(*worker.PoolConn)
f, ok := pc.Closeable.(*faktory.Client)
```

and `f` in this case is the client you want to use.
