### ISSUE TITLE
Production / use cases

### ISSUE THREAD

**Issue by Schniz** [contribsys/faktory#131]
Hi there,

first of all, let me thank you for this project.
I was thankful for Sidekiq and I'm thankful for this.
I really hope it will become a standard across languages.

Over the last couple of weeks I've been writing an intensive background processing application in Python with Celery and I got a big problem with it, architecturally: tasks aren't ordered in the broker (Redis in my case) by the scheduled time - it's not implemented with an ordered set/priority queue, it's just a queue. I use scheduling pretty intensively (can reach to more than 1 day of delay, for 100Ks of tasks)

I would really want to give Faktory a try, but I have some thoughts about it.

1. When will v1 be released? what are your goals towards the release? Pro/Enterprise version plan? Can I help in any way?
2. We've had peaks of 6M jobs/day last week. Each job can call 0-4 sub-jobs (aka subtasks). have you done some stress tests for it? benchmarking?
3. There are lots of "retries" in our system because we use Facebook's API heavily, and it's inconsistent about errors.
4. I'm currently running ~5 queues with 10-50 background workers
5. Is there an integration of Faktory into existing monitoring systems? (Telegraf/InfluxDB, Graphite/StatsD). Is there a go-to way to get data about jobs/rocksdb?
6. Although it's not v1.0.0, how would you rate "production readiness" of the project?
7. is copying the database to S3 for backup purposes is the right approach?
8. Is there a "golden way" to deploy Faktory to allow high-traffic? a docker container/binary on linux/etc? how would you deploy it to production? :)

Thanks!

**Comment by mperham** [comment]
These are good questions.

1. TBD.  Ideally within the next 6 months.  The big question right now is whether we stick with RocksDB or switch to a Go-native storage layer like Badger.
2. I've done small load tests of 100,000 to 1,000,000 jobs, processing about 3-5000 jobs/sec.
3. There's no built-in Statsd support today, that is expected to be a Pro feature.  You can use the INFO command today to get the set of metrics displayed by the Web UI and dump elements to your monitoring system.
4. There are a few people using it in production today but I don't have any testimonials in front of me.  I have a 0.7.0 release coming this week which fixes a few major lingering issues.
5. I haven't documented any backup best practices, but certainly off-host storage would be best.
6. Unsure on high-traffic deployments.  You can deploy a new Faktory binary and restart but that will lose all network connections and force clients to reconnect.  You can use something like HAProxy as a network intermediary allowing zero-downtime restarts; that's something that we need to document how to do (help welcome!).
