### ISSUE TITLE
[Wiki] Add a Getting started with Go

### ISSUE THREAD

**Issue by koalalorenzo** [contribsys/faktory#132]
Hello!
I would love to see a getting started page written in go!
Is this planned?

**Comment by mperham** [comment]
Not at the moment. You are welcome to start one!

**Comment by koalalorenzo** [comment]
Please, don't close the issue if there is no getting started.
Is it there?

**Comment by mperham** [comment]
The wiki is publicly editable. "You are welcome to start one" This README contains a lot of the material:

https://github.com/contribsys/faktory_worker_go

**Comment by koalalorenzo** [comment]
Thank you... but since the documentation is not there, why is it important to close the ticket that tracks the task? Please, don’t close it:

If anybody wants, they can help by just looking at the tickets!
I decided to drop faktory exactly because there is no Go support and no intention to listen to the community. So keep this issue open, so when you will have the documentation I will know.

**Comment by mperham** [comment]
There is Go support, in https://GitHub.com/contribsys/faktory_worker_go.

**Comment by koalalorenzo** [comment]
Let me help you: What is this issue about?

**Comment by mperham** [comment]
faktory_worker_go's README is the Getting Started guide, I don't see much additional value to a wiki page so I'm not willing to leave this open forever for someone to pick up.

**Comment by francoishill** [comment]
@koalalorenzo please keep conversations in the open-source community strictly to showing gratitude for people making effort to open-source code which you can **use freely**.

It took me 2 minutes now to add [factory_worker_go](https://github.com/contribsys/faktory_worker_go) to the [wiki](https://github.com/contribsys/faktory/wiki). Probably roughly the same time it took you to create this issue.
