### ISSUE TITLE
csrf_token input is plain text not tag code in scheduled page

### ISSUE THREAD

**Issue by icyleaf** [contribsys/faktory#135]
<img width="1161" alt="qq20180117-173633 2x" src="https://user-images.githubusercontent.com/17814/35076505-c8583efa-fc33-11e7-8a65-6c2b0091b034.png">

faktory verison: `0.7.0`, installed with brew tap `contribsys/faktory`

**Comment by mperham** [comment]
https://github.com/contribsys/faktory/commit/bfff469b5350632b2fe1e62dd53d9a6475dc2a47
