### ISSUE TITLE
Data persistence

### ISSUE THREAD

**Issue by PlkMarudny** [contribsys/faktory#140]
I run the Docker image: 

`docker run --rm -it -v faktory-data:/c/Users/someuser/faktory -e "FAKTORY_PASSWORD=pa ss" --name faktory -p 7419:7419  -p 7420:7420 contribsys/faktory:latest /faktory -b 0.0.0.0:7419`

From the Docker, I can successfully create a file in the folder mentioned above, and the command:

`docker inspect faktory`

 gives me: 

> "Mounts": [
>             {
>                 "Type": "volume",
>                 "Name": "faktory-data",
>                 "Source": "/mnt/sda1/var/lib/docker/volumes/faktory-data/_data",
>                 "Destination": "/c/Users/someuser/faktory",
>                 "Driver": "local",
>                 "Mode": "z",
>                 "RW": true,
>                 "Propagation": ""
>             }
>         ]

After restirng the container, data is not persisted. In general, no files are created inside `/c/Users/someuser/faktory`
Not quite sure it this is a Faktory issue, or my setup maybe?

**Comment by bryanrite** [comment]
Looks like you are starting faktory in development environment... you're missing the `-e production` at the end of your command as shown here:

https://github.com/contribsys/faktory/wiki/Installation#docker

`docker run --rm -it -v faktory-data:/var/lib/faktory -e "FAKTORY_PASSWORD=pass" -p 7419:7419 -p 7420:7420 contribsys/faktory:latest /faktory -b 0.0.0.0:7419 -e production`

**Comment by PlkMarudny** [comment]
Indeed, I did not set this, however, even after setting, the output from Faktory is:

`$ docker run --rm -it -v faktory-data:/c/Users/toplonka/faktory -e "FAKTORY_PASSWORD=pa ss" --name faktory -p 7419:7419  -p 7420:7420 contribsys/faktory:latest /faktory -b 0.0.0.0:7419 -e production
Faktory 0.7.0
Copyright © 2018 Contributed Systems LLC
Licensed under the GNU Public License 3.0
I 2018-02-21T10:03:32.053Z Initializing storage at /var/lib/faktory/db
I 2018-02-21T10:03:34.937Z PID 1 listening at 0.0.0.0:7419, press Ctrl-C to stop
I 2018-02-21T10:03:34.937Z Web server now listening on port 7420
`

**Comment by bryanrite** [comment]
Yah, it looks correct now, as its using the production storage location `/var/lib/faktory/db` (see https://github.com/contribsys/faktory/wiki/Administration for details)...  I don't think you are setting your volume correctly... the path should reflect the path within the image, not your local machine... try changing the volume to: `-v faktory-data:/var/lib/faktory`

**Comment by bryanrite** [comment]
If you want to see where the files are stored on your host, you can do something like `docker volume inspect faktory-data` it will show you the host path where the volume's data is being persisted on your local machine.

Alternatively, without volumes, you could do something like `-v /c/Users/toplonka/faktory:/var/lib/faktory` to directly mount your host directory.

**Comment by PlkMarudny** [comment]
Ok, looks like that working syntax is:
`-v //c/Users/toplonka/faktory:/var/lib/faktory`

Unfortunately it does not work on Windows, because of the following line:

https://github.com/facebook/rocksdb/blob/868bfa40336b99005beb9f4fc9cf2acc0d330ae1/util/env_posix.cc#L1016

fsync on directories is not supported with vboxfs.

**Comment by PlkMarudny** [comment]
So the conclusion is that the Docker image does not persist data when run using Docker Toolbox

**Comment by PlkMarudny** [comment]
The same applies on Windows 10 with Docker CE for Windows
