### ISSUE TITLE
Worker stops fetching jobs abruptly - Windows Flask server

### ISSUE THREAD

**Issue by shauryashahi** [contribsys/faktory#141]
Hey, I am using faktory in a windows flask server. Here's a bug which I can't get my head round. I have two services which run, one for flask rest server, one for faktory worker.

> Our architecture is like this:
> 
> A sync request comes in to Flask server, gets queued on faktory and sleeps till a json file is created with appropriate return data, worker runs as a job service in the background, fetches jobs from faktory , does the required work, writes response to a json file, the sleeping request now gathers data from this file and returns to the sync request.

Both the services are running, faktory is queuing up , but the worker is not eating the jobs. This bloats up the incoming requests and they are all waiting for jobs to get executed. Most just time out. (concurrency is 5)

But, on restarting the Job Service (faktory worker service) all the jobs are processed and returned. 

This is not a general outcome, this situation comes up abruptly any time. (can't figure out what exactly triggers this, hence can't pinpoint when this creeps up)

Note: 90% of the time everything works smoothly.

So, here's the deal, why does the worker just stop even when the service is running in the background. (checked with win Task Manager) Can't really place this onto production with a bug like that. 

Any ideas?

**Comment by mperham** [comment]
This repo is for the Faktory server.  Is this bug in the worker and belongs in that repo?

You haven't told us what worker you are using, what versions you are running, etc.  Impossible to help without a lot more info.

**Comment by cdrx** [comment]
Mention of flask makes me think it may be this:

https://github.com/cdrx/faktory_worker_python/issues/10
