### ISSUE TITLE
Retry default value

### ISSUE THREAD

**Issue by danielwestendorf** [contribsys/faktory#144]
Referring to the [Job Payload Spec](https://github.com/contribsys/faktory/wiki/The-Job-Payload), I see that the default retry value is 25.

> "retry": 3 - set the number of retries to perform if this job fails. Default is 25 (which, with exponential backoff, means Faktory will retry the job over a 21 day period).

However, when I submit a job, without a retry key/value, that job is never retried and immediately goes to the failed status.

```
PUSH {"jid":"15ff668d-1208-4196-ac48-6f43e751e6ac","jobtype":"Webhook","args":[...]}
```

Specifying a retry value results in the expected number of retries.

So my question is, what is the correct behavior to invoke the default value of 25? Perhaps:

```
PUSH {"jid":"15ff668d-1208-4196-ac48-6f43e751e6ac","jobtype":"Webhook","args":[...], "retry":null}
```

**Comment by mperham** [comment]
25 is the default for Sidekiq and for the Faktory client libraries I ship.  If you generate the JSON manually and do not pass a value, it will unmarshal to 0, which is a legal value and result in no retries.  Which I think is a semantic which makes sense?  `"retry": null` is not a legal value; it should resolve to 0 also.  So the wiki is misleading and could use refining.

**Comment by danielwestendorf** [comment]
Ah, thanks for the clarification. This resolves my question so I'll close.

I expected retries to be enabled by default, but it appears that the [node worker library](https://github.com/jbielick/faktory_worker_node) doesn't specify a default value, yet references the job spec for arguments to pass.

It appears that defaults which aren't enforced by the spec shouldn't be mentioned there.

From a user's perspective, since I see how to explicitly disable retries for a job, I would expect retries to be opt-out instead of opt-in. Otherwise, it will be up to every client library to set the default value, which will likely be inconsistent when queuing jobs using different languages/clients.

**Comment by mperham** [comment]
I totally agree; the issue is that today I can't tell if you sent no value or explicitly set 0.  Updating the code to differentiate those cases would allow us to enforce the default.  You are welcome to reopen this issue or send a PR to fix.
