### ISSUE TITLE
negative busy worker count shown

### ISSUE THREAD

**Issue by samphippen** [contribsys/faktory#148]
after repeatedly suspending and unsuspending my laptop because I'm flying today my worker process came up and down a bunch of times, resulting in this:

<img width="95" alt="screen shot 2018-04-16 at 12 02 29" src="https://user-images.githubusercontent.com/96662/38821330-37af0a3e-416e-11e8-9cb0-ebeb5e8faf2d.png">

Killing and restarting the faktory binary fixed this.

**Comment by danielwestendorf** [comment]
I just noticed this as well, but on my production faktory server which has heroku driven workers connecting.
![screen shot 2018-04-17 at 9 36 23 am](https://user-images.githubusercontent.com/44478/38880410-e1d7da2c-4222-11e8-9b64-a03bfc6bf704.png)

**Comment by shauryashahi** [comment]
Yup, this is something we come across everyday too.

**Comment by mperham** [comment]
Thanks for your patience here.  I have a PR in #153 which I hope will work around the issue.  Ultimately this is a cache consistency issue which is impossible for me to fix; the PR adds a task which runs every minute and resets the size value if it goes negative.

**Comment by dansgithubuser** [comment]
Could I get a little more insight into this issue? I'm trying to disentangle a few issues I'm seeing -- are there any other symptoms that go along with this, or is _only_ the summary busy-jobs number affected?

In particular, I see faktory claiming that processes always have 0 busy jobs, but I know jobs are being processed. I'm thinking maybe these numbers are affected as well (but logically gated to be no less than 0?)

**Comment by mperham** [comment]
@dansgithubuser All the big metrics except Processed and Failed can go negative.  Master has switched it to be uint (so it'll be HUGE instead) and adds a task to check for invalid values every minute and reset the value if so.
