### ISSUE TITLE
Home tab becomes unresponsive after the app runs for a while

### ISSUE THREAD

**Issue by CaryLandholt** [contribsys/faktory#154]
We're running faktory 0.7.0 inside of docker with both node.js and golang workers.

After restarting the faktory service, every tab (Home, Busy, Queues, etc.) are snappy; however, after a short while the Home tab begins to load slower and slower until it doesn't load at all.

Jobs continue to process just fine.  The only thing noticed is the issue with the home tab.

Anything we should be checking on our end?  Thanks

**Comment by dotanloc** [comment]
same issue to me

**Comment by mperham** [comment]
What does the debug page look like when the system has slowed to a crawl?

**Comment by CaryLandholt** [comment]
Here's the debug info take when the Home tab becomes unresponsive, even after a hard browser refresh.

**Debugging**
```
Location      | en
Version       | Faktory 0.7.0, RocksDB 5.9.2
Data Location | /var/lib/faktory/db
Runtime       | Goroutines: 75, CPUs: 4
Memory        | Alloc (KB): 1604, Live Objects: 12275
GC            | PauseTotal (µs): 249145, NumGC: 1818
```

**Disk Usage**
```
> df -h
Filesystem                Size      Used Available Use% Mounted on
overlay                  77.5G     13.4G     64.1G  17% /
overlay                  77.5G     13.4G     64.1G  17% /
tmpfs                    64.0M         0     64.0M   0% /dev
tmpfs                     7.3G         0      7.3G   0% /sys/fs/cgroup
/dev/sda1                77.5G     13.4G     64.1G  17% /etc/resolv.conf
/dev/sda1                77.5G     13.4G     64.1G  17% /etc/hostname
/dev/sda1                77.5G     13.4G     64.1G  17% /etc/hosts
shm                      64.0M         0     64.0M   0% /dev/shm
/dev/sda1                77.5G     13.4G     64.1G  17% /var/lib/faktory
tmpfs                    64.0M         0     64.0M   0% /proc/kcore
tmpfs                    64.0M         0     64.0M   0% /proc/keys
tmpfs                    64.0M         0     64.0M   0% /proc/timer_list
tmpfs                    64.0M         0     64.0M   0% /proc/sched_debug
tmpfs                     7.3G         0      7.3G   0% /proc/scsi
tmpfs                     7.3G         0      7.3G   0% /sys/firmware
```

**RocksDB Statistics**
```
** Compaction Stats [default] **
Level    Files   Size     Score Read(GB)  Rn(GB) Rnp1(GB) Write(GB) Wnew(GB) Moved(GB) W-Amp Rd(MB/s) Wr(MB/s) Comp(sec) Comp(cnt) Avg(sec) KeyIn KeyDrop
----------------------------------------------------------------------------------------------------------------------------------------------------------
 Sum      0/0    0.00 KB   0.0      0.0     0.0      0.0       0.0      0.0       0.0   0.0      0.0      0.0         0         0    0.000       0      0
 Int      0/0    0.00 KB   0.0      0.0     0.0      0.0       0.0      0.0       0.0   0.0      0.0      0.0         0         0    0.000       0      0
Uptime(secs): 12938.9 total, 0.2 interval
Flush(GB): cumulative 0.000, interval 0.000
AddFile(GB): cumulative 0.000, interval 0.000
AddFile(Total Files): cumulative 0, interval 0
AddFile(L0 Files): cumulative 0, interval 0
AddFile(Keys): cumulative 0, interval 0
Cumulative compaction: 0.00 GB write, 0.00 MB/s write, 0.00 GB read, 0.00 MB/s read, 0.0 seconds
Interval compaction: 0.00 GB write, 0.00 MB/s write, 0.00 GB read, 0.00 MB/s read, 0.0 seconds
Stalls(count): 0 level0_slowdown, 0 level0_slowdown_with_compaction, 0 level0_numfiles, 0 level0_numfiles_with_compaction, 0 stop for pending_compaction_bytes, 0 slowdown for pending_compaction_bytes, 0 memtable_compaction, 0 memtable_slowdown, interval 0 total count

** File Read Latency Histogram By Level [default] **

** DB Stats **
Uptime(secs): 12938.9 total, 0.2 interval
Cumulative writes: 688K writes, 688K keys, 688K commit groups, 1.0 writes per commit group, ingest: 0.22 GB, 0.02 MB/s
Cumulative WAL: 688K writes, 0 syncs, 688508.00 writes per sync, written: 0.22 GB, 0.02 MB/s
Cumulative stall: 00:00:0.000 H:M:S, 0.0 percent
Interval writes: 6 writes, 6 keys, 6 commit groups, 0.9 writes per commit group, ingest: 0.00 MB, 0.01 MB/s
Interval WAL: 6 writes, 0 syncs, 6.00 writes per sync, written: 0.00 MB, 0.01 MB/s
Interval stall: 00:00:0.000 H:M:S, 0.0 percent
```

**Comment by mperham** [comment]
Does a browser restart fix it?  Are you using live polling or just sitting there with the graphs updating?  I'm trying to figure out if this is a client-side or server-side issue.

**Comment by mperham** [comment]
Nevermind about live polling, Faktory UI doesn't implement it.

**Comment by mperham** [comment]
Any console output?  How long does it take sitting on Home for your browser to slow down?

**Comment by mperham** [comment]
Does Busy or Queues slow down or just Home?

**Comment by CaryLandholt** [comment]
• No tabs or queues slow down apart from the home tab UI
• Once the home tab becomes unresponsive, it stays that way until we restart the faktory docker service, even when we refresh the browser page or try to load it in a different browser all-together
• It takes about 10-20 minutes for it to get in this state, but It's dependent upon activity.  We don't experience this in our staging environment, but it's not bombarded with activity - just a trickle of jobs.  Our production environment is pretty busy.
• I have left the home page open with polling on (the faktory UI has polling on the home tab alone).

Here is a screenshot of the Chrome console.
![image](https://user-images.githubusercontent.com/833972/41442684-1a41ce28-6ffe-11e8-9984-d87e6d6bfbb9.png)

And here's a screenshot of the page's network activity.  In this case the document took 2.2 min.
![image](https://user-images.githubusercontent.com/833972/41442837-dfe9ba32-6ffe-11e8-9bbb-1bf85c17b225.png)

**Comment by CaryLandholt** [comment]
Here's another screenshot showing the summary bar loaded (after just over 2 minutes) without the graphs.

![image](https://user-images.githubusercontent.com/833972/41442930-8317a070-6fff-11e8-8858-aec59b4ef758.png)

**Comment by CaryLandholt** [comment]
Yes, the prior screenshots were from Chrome 67 on macOS High Sierra

Here's Safari 11.1 on macOS High Sierra

![image](https://user-images.githubusercontent.com/833972/41443118-a45f9dd6-7000-11e8-842f-b6a7ad37260e.png)

**Comment by mperham** [comment]
`document.getElementById("realtime")` is returning null for some reason in the JS.  I have no idea what would cause this element to disappear from the DOM.

**Comment by mperham** [comment]
I'm using FF with a trickle of jobs, running fine for an hour+ now.  I'll try Chrome.

**Comment by CaryLandholt** [comment]
And the document taking over 2 minutes to retrieve from the server is odd too

**Comment by mperham** [comment]
“Is odd” doesn’t help me. Please give me actual data so I can debug.

**Comment by CaryLandholt** [comment]
All of the tabs complete loading in under 50ms.
After 10 minutes or so of running, the home tab takes over 2 minutes to retrieve the page from the server, and as you noticed, the charts are missing.

**Comment by mperham** [comment]
Oh I thought you meant the HTML data was malformed. It is odd behavior; I’m sure there is a bug here but I need specifics about when it does and doesn’t occur so I can narrow the possible causes.

**Comment by CaryLandholt** [comment]
yep - will provide more as soon as I have it

**Comment by CaryLandholt** [comment]
I must have accidentally closed this issue.
Reopening but looks like it may have been addressed with https://github.com/contribsys/faktory/commit/e5c312630c26ff0811eb9a6fc4fbf12f48bf1242 and noted https://github.com/contribsys/faktory/issues/156.

So may now be a duplicate.

**Comment by CaryLandholt** [comment]
Looks like version 0.8.0 does fix this issue. 
Closing. Thanks!
