### ISSUE TITLE
Support explicitly failing a job and sending to the dead queue

### ISSUE THREAD

**Issue by theoephraim** [contribsys/faktory#159]
certain types of errors in our job handlers may not make sense to re-enqueue the job to retry it.
ex: invalid job parameters

Right now in order to skip the retry logic, I have to ACK the job. It's fine but it means the job does not go into the dead queue where I could inspect it later and easily see that it failed.

It would be nice to be able to fail a job and explicitly tell faktory to send it to the dead queue right away, even if the job has retries enabled.

**Comment by mperham** [comment]
Could you be a little more specific with your usecase?  Jobs and their arguments should be migrated carefully to preserve functionality across deploys so I'm unclear why you'd just want to give up on a job.

**Comment by theoephraim** [comment]
So if the code is broken, or some API request unexpectedly fails, a retry definitely makes sense. But there are cases where either the payload is messed up for another reason, or something in your database could be in a messed up state, where it could make sense to just fail right away. Here are some examples:

Lets say my job is making requests to some external API.
Certain API responses would definitely be good to retry - 500, 429, etc
But lets say the response is "that thing doesnt exist" or "the auth token you are trying to use is invalid". In those cases I already know that retrying will just fail again, so no need to retry at all.

Lets say the job is getting enqueued and has some user-entered parameters.
Yes in many cases there may be a specific API endpoint in front of it that would deny them at that stage, but there are others where it's possible that isn't the case. For example, I have a general purpose "enqueue job X with payload Y" endpoint for manually triggering jobs so each job doesn't need it's own endpoint.



I think it makes sense to have the default behavior to retry - but it would be nice to be able to explicitly go straight to the dead queue.



-

**Comment by jbielick** [comment]
What about sending `{... "retry": 0}` in the `FAIL` command?

**Comment by theoephraim** [comment]
So internally, I already have this set up in my system, I have logs of what happened and the "fail but die right away" jobs do get logged as such.

But it is weird that I have to actually ACK the jobs and that they will not go to the dead queue with the rest of the failed jobs.

The more general feature request (which is also something I would like to be able to do) is as @jbielick mentioned is to mess with the job while failing it, to potentially alter the number of retries.
For example, certain errors I get back from a 3rd party API could mean I want to retry more or less times, and I wouldn't have known how many retries were appropriate when I originally enqueued the job.

I believe beanstalkd had this kind of functionality (to update the job meta info while attempting it) and I had used it before in these kinds of scenarios.

**Comment by mperham** [comment]
No plans to implement. If you don't want the job to retry, you should report the error to your error service and then treat the job as a success.

**Comment by heynemann** [comment]
Really with this would be reopened. Having jobs succeed when they actually failed screws up:
- Metrics (now I have to account not only for jobs failing to dead but also the ones that "fail as expected")
- Monitoring (see above)
- Error handling code duplication (everywhere our teams have to implement this logic to handle these non-retriable errors)

For us, a simple `IsNonRetriableError: func(err) bool` in the job would suffice. Seems like a fairly easy feature to add that brings a lot of value to Faktory. WDYT?
