### ISSUE TITLE
List of improvements over sidekiq

### ISSUE THREAD

**Issue by zachgoldstein** [contribsys/faktory#16]
Besides being more language-agnostic, would love to understand the benefits of this over sidekiq in more detail. As an extension; how does this differ from queuing systems like kafka, zeromq, rabbitmq, etc. and what task-specific sugar is added on top?

Apologies if this is super apparent somewhere already! Looks like a cool project, excited to play around with it.

**Comment by zachgoldstein** [comment]
I see the following in https://github.com/contribsys/faktory_worker_ruby:

> Instead Faktory is a "smart" server that implements all major features within the server itself; the worker process can be dumb and rely on the server for job retries, reservation, Web UI, etc. This also means we can create workers in any programming language.

Sounds like a good start!

**Comment by mperham** [comment]
"improvements" is a stretch right now.  Faktory is fundamentally a different architecture from Sidekiq, as that quote points out.

Functionally Faktory is close to where Sidekiq is.  In fact, Faktory contains the "reliability" extra that I have to charge for in Sidekiq Pro.

**Comment by Omeryl** [comment]
@mperham So, here's a fun question based on the language of your message: Why do you "have to charge for it" in sidekiq's case, whereas you reimplemented it here for free? Curious choice of words.

**Comment by mperham** [comment]
@Omeryl Redis doesn't have the necessary primitives to implement efficient multi-queue reliability easily.  It took me years and multiple tries before I got it working well so I have no problem charging for solving a hard problem.  OTOH, Rocks gives me more flexibility so I can implement job reservation easily and efficiently in Faktory.
