### ISSUE TITLE
Daily Job Problem

### ISSUE THREAD

**Issue by aolmez** [contribsys/faktory#164]
Hi

i want to add one daily job and this job call method every day in a year. how can i add it ?

> job := faktory.NewJob("SomeJob", 1, 2, 3) 
> 	job.Queue = "default"
> 	job.At ="2018-09-14T00:00:00.000000Z"
> 	err = client.Push(job)

**Comment by mperham** [comment]
Faktory doesn’t support cron jobs out of the box, this will be a commercial feature. You can use cron on your server to run a script which enqueues a job.

**Comment by marcstreeter** [comment]
could you explain "commercial feature"?  Will it not be available as an open source feature?

**Comment by mperham** [comment]
Correct. It will be for sale, exactly as like Sidekiq.org

**Comment by marcstreeter** [comment]
Thank you for the quick response.  I wasn't familiar with Sidekiq.
