### ISSUE TITLE
UI freezing/web server choking in 0.9 beta-1

### ISSUE THREAD

**Issue by ttilberg** [contribsys/faktory#165]
I previously provided information in the gitter chat regarding my experience running the 0.9.0-beta1 docker image. To iterate:

Upon switching to the Redis version of Faktory, my current environment comes to a grinding halt very shortly after boot if I have workers connected. For a brief moment, I am able to load part of the index page of the web UI, but it eventually halts, and then becomes completely unresponsive. Additionally, if I am trying to enqueue jobs in the background without loading the web UI, things grind to a halt.

My environment:

- Faktory server running in Docker on a local VM
- Fresh volume, no prior data (did not mount a volume to ensure a clean run)
- 3 Faktory Worker Node services connecting with concurrency of 5 each from same LAN, but physical machines a few switches away from network
- 1 Faktory Worker Ruby service connecting with default concurrency, different VM 
- 3 job queues

You asked that I fire up the Redis monitor. This shows traffic generated from what I assume are my workers. The web UI becomes completely unusable within about 10 seconds of trying to get in. Here is a log that shows the typical redis stream. This data repeats constantly at all times, and does not seem to change when I am attempting to connect to the UI for the first time:

https://pastebin.com/raw/Z0FmC8Mw

Upon doing some other environment testing and trying to create a reproduction using `docker-compose`, I am finding that this log noise is normal, and it is not locking up my compose environment.

I'm not sure what other information I can provide to be helpful, but please let me know. The rocksdb version works flawlessly in this exact same setup, but the redis version fails 100% of the time immediately if there are workers attached.

I wonder: Is it perhaps related to the nature of redis being intentionally blocking and single threaded, and having to do with network latency? i.e. -- perhaps the node workers are asking for updates too frequently? Maybe something in the timestamps will stand out to you -- but comparing the log against my test example -- it looks really similar.

[Here's a link](https://github.com/ttilberg/faktory-issue-reproduction-test-env) to my attempt to reproduce my environment. It does not reproduce the issue like I had hoped, but it closely represents the general structure of my project. Perhaps it will help show more information...

**Comment by mperham** [comment]
Does it work fine if you shut down the node worker or the ruby worker?

**Comment by mperham** [comment]
I just pushed 0.9.0-beta2 to Docker.  Please reopen and give as much detail as possible if it recurs.
