### ISSUE TITLE
Differences from an AMQP server

### ISSUE THREAD

**Issue by DanielVartanov** [contribsys/faktory#17]
Faktory looks like a decent message broker. But how do I advocate it to my teammates over, say, RabbitMQ?

**Comment by mperham** [comment]
Faktory is not really a message queue and RabbitMQ is not really a background job system.  If you want to send arbitrary messages between different apps written in different languages in your business, that's more Rabbit's strength.  Faktory imposes certain conventions like retries, job arguments, etc that are more specialized than just general message passing.  OTOH, that lets the Faktory Web UI show you much more interesting data about each element.

Faktory's strength is that it is much easier to setup.  Rabbit can be quite complex.

**Comment by Skeyelab** [comment]
"Faktory's strength is that it is much easier to setup. Rabbit can be complex."

So far you do not support OSX nor Heroku.  It is not very easy to set up.

**Comment by mperham** [comment]
@Skeyelab you're comparing a 1 day old project with a 15 yr old project.  give it time.

**Comment by Skeyelab** [comment]
Fair.
