### ISSUE TITLE
Unable to connect to web server on 9.0

### ISSUE THREAD

**Issue by emhoracek** [contribsys/faktory#172]
Hi, I'm trying out Faktory, and when I tried 8.0 this worked fine:

`sudo docker run -d --rm -v faktory-data:/var/lib/faktory -e "FAKTORY_PASSWORD=my_password" -p 127.0.0.1:7419:7419 -p 127.0.0.1:7420:7420 contribsys/faktory:latest /faktory -b :7419 -e production`

(Copied from the Wiki)

But when `latest` changed to 9.0, I was no longer able to connect to the Faktory web interface.

I noticed that `docker logs` output changed, from this:

```
I 2018-10-15T21:56:52.120Z Initializing storage at /var/lib/faktory/db
I 2018-10-15T21:56:52.161Z PID 1 listening at :7419, press Ctrl-C to stop
I 2018-10-15T21:56:52.161Z Web server now listening on port 7420
```

to this:

```
I 2018-10-16T14:19:40.623Z Initializing redis storage at /var/lib/faktory/db, socket /var/lib/faktory/db/redis.sock
I 2018-10-16T14:19:40.635Z Web server now listening at localhost:7420
```

I'm hosting Faktory on an AWS EC2 server and it worked fine on 8.0.

Happy to provide any other diagnostics that may be needed for a solution!

**Comment by mperham** [comment]
We need to add “-w :7420” to the CLI args.

**Comment by emhoracek** [comment]
Ahh, I see what happened. I was using `latest` last week, which was 8.0, so when I copied the command from the wiki, I had to remove the `-w :7420` flag in order for the command to work. 

Adding the `-w :7420` flag back fixes the problem!
