### ISSUE TITLE
sysctl path in systemd unit file incorrect

### ISSUE THREAD

**Issue by hellhond** [contribsys/faktory#175]
OS: Debian 9.5
Faktory: faktory_0.9.0-1_amd64.deb

When trying to start Faktory it generates an error,
```
Oct 17 13:29:48 DEV systemd[16363]: faktory.service: Failed at step EXEC spawning /usr/sbin/sysctl: No such file or directory
```

The shipped systemd unit file for the above Faktory package includes the following line,
```
ExecStartPre=/usr/sbin/sysctl vm.overcommit_memory=1
```

However, stock Debian 9 has the sysctl binary at 
```
# which sysctl
/sbin/sysctl
```

**Comment by mperham** [comment]
Looks like Ubuntu has it in /sbin and CentOS has it in /usr/sbin.  Cool cool.
