### ISSUE TITLE
Add way to delete all scheduled tasks on UI

### ISSUE THREAD

**Issue by adriancuadros** [contribsys/faktory#176]
It would be nice if there was an easy way to delete all scheduled tasks (not only the ones on the page) the same way it is easy to delete all tasks on a given queue.

**Comment by mperham** [comment]
Is there not a delete all button at the bottom of the page?

**Comment by adriancuadros** [comment]
This is what I'm currently getting:

![image](https://user-images.githubusercontent.com/51557/47322477-b8587280-d61d-11e8-8be3-07c3b50c6131.png)

No delete all

Currently using: contribsys/faktory:latest Docker image

**Comment by mperham** [comment]
Sounds like I forgot to implement it!

**Comment by mperham** [comment]
Ah, Sidekiq doesn't implement this either; I didn't forget because it's never existed.

**Comment by adriancuadros** [comment]
We have a use case for spreading tasks in a given window of time and this would be really useful during development and debugging 👍

**Comment by adriancuadros** [comment]
Which port is redis running on the container ? or how can I cli into it to do a full reset ?

**Comment by mperham** [comment]
Use the FLUSH command via a Faktory client connection, e.g. https://github.com/contribsys/faktory_worker_ruby/blob/master/lib/faktory/client.rb#L53.

**Comment by adriancuadros** [comment]
Thank you, will do so
