### ISSUE TITLE
Support extending the Web UI

### ISSUE THREAD

**Issue by nathanpalmer** [contribsys/faktory#177]
Would be great if Faktory had a way to extend the Web UI with some custom routes. Similar to how [some Sidekiq integrations would do it](https://github.com/utgarda/sidekiq-status#sidekiq-web-integration.)

Is this on the roadmap?

**Comment by mperham** [comment]
Go is not a dynamic language.  You'd need to rebuild the entire binary.

**Comment by nathanpalmer** [comment]
True. Though there are ways that I've done it in other languages (C#, via Dependency Injection.) I'm not familiar enough with Go to know what is possible. But, I'm also not really sure that injecting purely UI code in the server process that coordinates the job work is the right play.

Is there any documented API to build parts of the UI outside of the binary? Ways to query the 7419 port for the information? I've seen some information [in the wiki](https://github.com/contribsys/faktory/wiki/Worker-Lifecycle) that seems to pertain to getting jobs in and workers getting jobs out. I haven't seen anything on querying server state.

**Comment by mperham** [comment]
https://github.com/contribsys/faktory/wiki/Worker-Lifecycle#information

There's two possibilities today: the INFO command or scraping the web UI.
