### ISSUE TITLE
behavior when heartbeat is missing

### ISSUE THREAD

**Issue by dansgithubuser** [contribsys/faktory#179]
I've just teased apart a trio of issues that resulted in an exponentially-increasing job queue. As best I understand:
1) Jobs were taking over half an hour to complete, successfully, and enqueue a new job (jobs are set up to daisy-chain).
2) My faktory worker doesn't send heartbeats
3) faktory retries jobs that time out

(1) was unexpected, but I'd rather treat it as a noncatastrophic possible failure than something I have to write code to prevent.

Now, (1) and (2) are definitely problems, but I'd also like to understand what faktory has to say about (3). Without knowing the details, my assumption of what "heartbeat missing" should mean is "the worst has happened". I'm thinking "the worst has happened" was mapped to "the job failed", but there is in fact a worse case than this: the job is still going, but isn't reporting heartbeats. Even if (2) is fixed for my particular worker, I suspect these types of failures could still happen from time to time and it'd be great if faktory didn't retry in that case.

So maybe a good top-level question is: what's the repercussions if faktory puts heartbeat-timeout jobs into the dead state instead of retrying? (Am I missing an obvious config that will do this?)

**Comment by dansgithubuser** [comment]
Hm.. is there a way for faktory to distinguish something like a network partition vs bad-behaving faktory worker? I noticed that the queue responsible for aforementioned job will still cap at specified number of concurrency processes, whether they are timed-out or not. For example:

queue has 2 jobs max
job 1 starts
15 minutes pass
job 2 starts
15 minutes pass
job 1 goes to retries
queue reports 1 job running, but if a job comes in, it stays enqueued rather than getting run

Is it possible for faktory to ask worker "hey is this job running?" before retrying on reservation timeout?

**Comment by mperham** [comment]
There is no difference from faktory's POV between a worker crash and a network partition.

Queues do not have job limits, you can push thousands of jobs into a queue.  I'm not sure what you are talking about.

**Comment by dansgithubuser** [comment]
I'm trying to distinguish a worker crash or network partition from the following type of error:
- job infinite loops or some other accidental error that causes it to run long
- worker doesn't send heartbeat for some other unintended reason
It is fair to say that this circumstance isn't worth solving. But, when this circumstance comes up, faktory's behavior will be to exponentially enqueue jobs forever.

Queues do not have job limits, the limit I was getting at was the number of concurrent jobs on a queue. If the limit is 20, it seems with the type of error described here, it the frontend could report the following contradiction: 15 jobs currently running on the queue, and 100 currently enqueued. Because 5 "invisible" jobs are still running.

I'm not sure if this is exactly what's going on. At other times I see 0 busy jobs in the queue despite seeing them listed below.

Perhaps another way to put it: how should I deal with a job that's running where I accidentally inserted an infinite loop, or some other unintentional long-running behavior? AFAIK I can't cancel a running job. And if there's no heartbeat, the job is put into retry state (but the original effort is left alone, so now there's a duplication, which is the root of the exponential behavior).

**Comment by mperham** [comment]
It's not exponential, it's linear.  1 running job -> 2 jobs -> 3 jobs, one every 30 minutes.

The only way to stop a running job is to restart the worker process processing it or implement such a safe stop in your application code.  No language runtime has a safe way to kill a running thread (see Java's Thread.stop, Ruby's Thread#kill, etc).

So you'd fix your code to remove the loop and restart the worker processes, which is what a normal production deploy would do.

You should always monitor the size or latency of your default queue, so you know that work is getting done and queues aren't backed up due to what can be a dozen different issues.

**Comment by dansgithubuser** [comment]
Right, by itself it's linear. Coupled with daisy-chaining, it becomes exponential. I'm not certain how common all these circumstances are.

So being able to stop a job would mean infrastructure to allow faktory, faktory worker, and job code to communicate? Is there a different issue contemplating this tradeoff?

I'm still interested in this question: Is it possible for faktory to ask worker "hey is this job running?" before retrying on reservation timeout? Is it a sensible question?

**Comment by mperham** [comment]
Ah, typically you won't have an infinite loop any job type, much less every job type.  But yeah you're right; if this is the case, you'd see 2 -> 4 -> 8, etc.  I've been using jobs for a decade and can't remember any infinite loops in production.  IME job code is integration tested, which typically catches these sorts of problems on your laptop.

Typically you'd have a database table with a row for each job, keyed by JID, which the job can poll regularly while running to see if it should stop.

No, the protocol does not have any provision for the server to query job status from the worker today.

**Comment by dansgithubuser** [comment]
"Typically you'd have a database table with a row for each job, keyed by JID, which the job can poll regularly while running to see if it should stop."

Oh interesting, I didn't think this was typical.

OK, thank you for the insights (:
