### ISSUE TITLE
Provide CI testing configuration for common providers

### ISSUE THREAD

**Issue by jonhoo** [contribsys/faktory#180]
The [Ruby](https://github.com/contribsys/faktory_worker_ruby) worker implementation currently has no CI testing set up, and the [Go](https://github.com/contribsys/faktory_worker_go) implementation, while it does have an [`.appveyor.yml`](https://github.com/contribsys/faktory_worker_go/blob/master/.appveyor.yml) file, does not seem to do any integration testing. The same seems to be true for the client bindings in this repository.

This is a little sad, as continuous testing catches *so* many bugs, and makes changes and PRs feel much safer. Both [Circle CI](https://circleci.com/docs/2.0/docker-compose/) and [Travis CI](https://docs.travis-ci.com/user/docker/#using-a-docker-image-from-a-repository-in-a-build) make it relatively easy to run Docker images with a few extra lines in the config file, so in theory the barrier to setting up CI for Faktory shouldn't be all that high. Mostly just spin up the Faktory docker image and then run the client with the right environment variables set.

If the "official" client/worker implementations had this, other implementations (like my [Rust implementation](https://github.com/jonhoo/faktory-rs)) could then copy that config and just change the test script invocation, and we'd immediately significantly improve how well-tested the Faktory ecosystem is!

**Comment by mperham** [comment]
💥 Let's fix that.  fwr and fwg are perfect guinea pigs for Faktory CI integration.

**Comment by mperham** [comment]
fwr now working https://github.com/contribsys/faktory_worker_ruby/blob/master/.travis.yml

**Comment by jonhoo** [comment]
@mperham that doesn't also run the tests though, or am I missing something?

**Comment by mperham** [comment]
The default for Ruby projects is to execute "bundle exec rake" as the last step, which is the canonical command to run a ruby test suite.

**Comment by mperham** [comment]
e.g. https://travis-ci.org/contribsys/faktory_worker_ruby/jobs/447910153#L490

**Comment by mperham** [comment]
Docs: https://github.com/contribsys/faktory/wiki/FAQ#how-do-i-test-my-project-with-faktory

**Comment by jonhoo** [comment]
Works for the Rust implementation too! https://travis-ci.org/jonhoo/faktory-rs/builds/447933105
