### ISSUE TITLE
How to close producer client connection?

### ISSUE THREAD

**Issue by majedev** [contribsys/faktory#183]
I'm writing a few producers/consumers in Go. For the producers, I used the Client implementation from this repo. However, I could not find a way to close the underlying TCP connection once I'm done with the client. 

The `Close()` method sends and `END` command to the server without closing the underlying TCP connection: https://github.com/contribsys/faktory/blob/master/client/client.go#L231

The ruby client implementation [closes the underlying socket](https://github.com/contribsys/faktory_worker_ruby/blob/master/lib/faktory/client.rb#L45) on calls to `close`, so I assume the go client behaviour isn't design intent?

**Comment by mperham** [comment]
The server closes the connection in response to the END.  Is it still necessary for the client to do it?

https://github.com/contribsys/faktory/blob/master/server/commands.go#L47

**Comment by majedev** [comment]
@mperham I see. I'm using faktory over TLS (through stunnel) so that might be causing issues. My wild guess: the server in this case only closed the stunnel side of the connection, but stunnel didn't close the client connection. Just ran a few tests and the connections weren't getting closed.

Now should the client close the connection when calling `Close()` either way? In my opinion, yes. I think producers should have control over their resources regardless of the server's behaviour.

**Comment by mperham** [comment]
Fair enough.  I'm working in another part of the codebase right now.  You can either leave this open or submit a PR.

**Comment by majedev** [comment]
Alright, I'll submit a PR later tonight for this one along with the TCP KeepAlive issue.

Thanks!

**Comment by jbielick** [comment]
I've also had trouble getting the server to close the connection on `END` in the node client.
