### ISSUE TITLE
Clarify possible 'retry' values in documentation

### ISSUE THREAD

**Issue by martinml** [contribsys/faktory#189]
Hi!

I'm currently reading about Faktory and was intrigued by an apparent contradiction about the use of 0/-1 in the retry field.

["The Job Payload" wiki](https://github.com/contribsys/faktory/wiki/The-Job-Payload) says:
> A value of 0 means the job will not be retried and will be discarded if it fails. A value of -1 means don't retry but move the job immediately to the Dead set if it fails.

However ["Job Errors" wiki](https://github.com/contribsys/faktory/wiki/Job-Errors) seems to says the opposite:
> Set "retry": 0 in the job payload. The job will go to the Dead set if it fails. Set "retry": -1 if you want jobs to be completely ephemeral and not saved to the Dead set.

[As I understand it](https://github.com/contribsys/faktory/blob/b82a0f698216c1e92325379566a15aa985c8d23b/manager/retry.go#L100), 0 just lets the job disappear and -1 stores in the dead set. Is that right?

I had a look to [the protocol](https://github.com/contribsys/faktory/blob/master/docs/protocol-specification.md#optional-fields) but it didn't seem very clear about it either:
> number of times to retry this job if it fails. -1 prevents retries.

**Comment by mperham** [comment]
Yep.  0 means ephemeral, -1 means save to dead set.  Updated protocol and job errors wiki, thank you!
