### ISSUE TITLE
Max Job Size?

### ISSUE THREAD

**Issue by larskluge** [contribsys/faktory#190]
What is the max size of a job? 

Background: I am working a bit on the Crystal client. I can push a larger job, but when I FETCH it, after a certain position, it comes back with a bunch of `\0`s? 

https://gist.github.com/larskluge/3666c72605feba8023e63926c42e4aa7 — scroll to the right..

**Comment by mperham** [comment]
There is no max size enforced right now but I would recommend staying below 64k. If you are seeing a limit, that’s a bug.
