### ISSUE TITLE
Job Priority after Redis Refactor

### ISSUE THREAD

**Issue by nickpoorman** [contribsys/faktory#201]
Did the job priority stuff make it into the Redis refactor? From what I can tell it's passed here but isn't used for anything.

https://github.com/contribsys/faktory/blob/bc191abd98cfa161c51bd9563e400ed5f8394e2f/storage/queue_redis.go#L77-L80

If this is the case, what is your recommendation for pulling from a queue based on weight? I was thinking of creating three queues for priority (high, medium, low) and to prevent medium and low from being starved by high, shuffling the order in which they are fetched from Redis based on some weight.

Should we achieve this on the client side by simply changing up the order of `Queues` passed to each iteration of `Fetch`?

https://github.com/contribsys/faktory_worker_go/blob/975f422be566286d0e97c5a8018c9bbd69c6ae45/runner.go#L196

**Comment by mperham** [comment]
Your assumptions are all correct.

0. Priority is slowly being removed.  It will all be gone for 1.0.
1. Redis cannot do prioritization without a significant performance hit.
2. Use a few queues with strict ordering, or have the worker randomize its FETCH queue ordering based on weights.
