### ISSUE TITLE
Reservation timeout maximum is reset to 30 min if it exceeds 24 hrs

### ISSUE THREAD

**Issue by majedev** [contribsys/faktory#202]
We've just encountered this issue: if the reservation timeout is set to more than 24 hours for a new job, then it's reset to the default value (30 minutes) by the server.

Related source code lines:
https://github.com/contribsys/faktory/blob/master/manager/working.go#L81-L95

So here are a few suggestions:

- Reset the value to 24 hours (instead of 30 min) and update the wiki accordingly
- Remove the maximum limit (might not be desirable for many users, but for our usecases, it works well)
- Keep the maximum, but reject the job payload if it has a higher reservation value (client-side and server-side checks)

Personally I prefer the third option because it doesn't silently change the expected behaviour (from the client's perspective).

**Comment by mperham** [comment]
One of my best practices is that a background job should run less in than an hour.  The maximum reservation time for a background job is 24 hours.  Can you explain why you need a job which takes longer than this?

I definitely agree this behavior can be improved.  I like failing fast so the PUSH call should fail, i.e. \#3 is my choice.

**Comment by majedev** [comment]
> One of my best practices is that a background job should run less in than an hour. The maximum reservation time for a background job is 24 hours. Can you explain why you need a job which takes longer than this?

For us it's a very specific business requirement which involves moving and processing very large files. We're probably abusing Faktory's model but it gave us quicker time to market dealing with persistent job queues.

> I definitely agree this behavior can be improved. I like failing fast so the PUSH call should fail, i.e. #3 is my choice.

**Comment by majedev** [comment]
>One of my best practices is that a background job should run less in than an hour. The maximum reservation time for a background job is 24 hours. Can you explain why you need a job which takes longer than this?

For us it's a very specific business requirement which involves moving and processing very large files across the globe. We're probably abusing Faktory's model but it gave us quicker time to market dealing with persistent job queues.

>I definitely agree this behavior can be improved. I like failing fast so the PUSH call should fail, i.e. #3 is my choice.
This is great. I like this too as mentioned earlier. Might be able to get a PR in later this week (but no promises :sweat_smile:). For now, we just patched our producers to cap the reservation to 24 hours.

**Comment by mperham** [comment]
This is now in master and will be in 0.9.6.
