### ISSUE TITLE
Unique jobs distinction fails intermittently with map params

### ISSUE THREAD

**Issue by CaryLandholt** [contribsys/faktory#203]
Jobs pushed to faktory with the `unique_for` argument aren't always considered unique even within the unique window and with the same params, when the params contains a map with key names.

Take the following payload as displayed in the ui, for example:
```
[map[dates:[2019-01-03 2019-01-21 2019-01-22] member:map[accessToken:abc refreshToken:def]] false]
```
Refreshing the UI will frequently resort the arguments.
After refreshing, the above may be rerendered as:
```
[map[member:map[accessToken:abc refreshToken:def] dates:[2019-01-03 2019-01-21 2019-01-22]] false]
```

Unclear if that behavior is a symptom of the underlying cause of why jobs are frequently not being considered unique/

**Comment by mperham** [comment]
Golang maps have a random iteration order, meaning their toString() value is random, meaning that any Map arguments will have a random unique key.  There's no easy solution or workaround here except to avoid Map arguments, e.g. you can pass an array of elements instead.

**Comment by mperham** [comment]
To be clear, I will do what I can to fix this issue but there's no easy solution and it will take time.

**Comment by CaryLandholt** [comment]
Yeah - difficult problem

**Comment by mperham** [comment]
Turns out I found a library which helped solve it quickly.  Adds some overhead but was quick to integrate, yay!

**Comment by CaryLandholt** [comment]
Fantastic!  Thanks so much!!

**Comment by CaryLandholt** [comment]
@mperham you happen to have a ballpark release schedule for this?

**Comment by mperham** [comment]
Next week if all goes to plan.

**Comment by CaryLandholt** [comment]
@mperham any update on a release date?

**Comment by mperham** [comment]
Yep, I’ll release it tomorrow.

**Comment by CaryLandholt** [comment]
Working great1
