### ISSUE TITLE
Panic on job Push()

### ISSUE THREAD

**Issue by grigoriy-petrov** [contribsys/faktory#207]
### Problem: 
I got panic when trying to push message to queue

```
panic: runtime error: slice bounds out of range

goroutine 593 [running]:
bufio.(*Reader).ReadSlice(0xc0008e6840, 0xa, 0xc000829c00, 0xc000829d50, 0x4b9e11, 0xc00047e900, 0xc00036c000)
	/usr/local/go/src/bufio/bufio.go:331 +0x22e
bufio.(*Reader).ReadBytes(0xc0008e6840, 0xc0000f800a, 0x0, 0x0, 0xc000829e10, 0x5dcf49, 0xc00047e900)
	/usr/local/go/src/bufio/bufio.go:434 +0x70
github.com/contribsys/faktory/client.readResponse(0xc0008e6840, 0x0, 0xc000829eb8, 0x8f05a3, 0xc000056480, 0x0)
	/go/pkg/mod/github.com/contribsys/faktory@v0.9.7-1/client/client.go:440 +0x72
github.com/contribsys/faktory/client.ok(0xc0008e6840, 0xbfe6d9, 0x4)
	/go/pkg/mod/github.com/contribsys/faktory@v0.9.7-1/client/client.go:403 +0x2f
github.com/contribsys/faktory/client.(*Client).Push(0xc0000564c0, 0xc0007f7c20, 0xc00051a370, 0x1)
	/go/pkg/mod/github.com/contribsys/faktory@v0.9.7-1/client/client.go:254 +0xc8
gitlab.com/.../internal/notificator.(*Notificator).Enqueue(0xc0008e68a0, 0xc0005c5800, 0x31b, 0x600)
	/app-source/internal/notificator/notificator.go:100 +0x50a
created by main.(*Server).handleNotify.func1
	/app-source/cmd/notificator/server.go:226 +0x22b
```

### What I do:

create client on server init with 
`client, err := faktory.Open()`

then on each request I call goroutine with
```
job := faktory.NewJob(notificator.TelegramService.ServiceID(), string(body))
err := notificator.workerClient.Push(job)
```
body is simple json like that
`{
  "event": "subscription_buy",
  "locale": "ru",
  "user_id": 1,
  "params": {
    "premium": false
  }
}`

The last message in logs was 
`msg="Enqueueing job: {\"event\":\"task_finished\",\"locale\":\"ru\",\"user_id\":658382,\"params\":{\"task\":{\"id\":58160882,\"status\":3,\"finished\":\"2019-03-28T14:55:38.000+03:00\",\"created_at\":\"2019-03-20T09:08:43.000+03:00\",\"planned_start_at\":\"2019-03-28T05:54:13.000+03:00\",\"planned_finish_at\":\"2019-03-28T14:32:13.000+03:00\",\"finish_code\":2905,\"login\":\"somelogin_\"}}}"`

but If I trigger request with such params manually it works as intended.

Only thing that I noticed, is that panics starts to occur when message rate grows. And never happens on staging and development.

**Comment by mperham** [comment]
Looks like the server might also be having a problem and possibly crashing, causing the client to crash also.  Does the server log contain anything bad?

**Comment by grigoriy-petrov** [comment]
I got 
```
I 2019-03-29T12:48:35.321Z Retries processed 24 jobs
E 2019-03-29T12:48:37.904Z error=read tcp 127.0.0.1:7419->127.0.0.1:40284: read: connection reset by peer Unexpected socket error
```

Faktory runs in docker container in the same kubernetes Pod

**Comment by mperham** [comment]
I can't decipher what's wrong.  My guess is that the network connection somehow got reset, corrupting the faktory.Client but I can't tell without more data.

**Comment by grigoriy-petrov** [comment]
How could I enable debug logs for faktory? Or what could I do to provide you with additional info?

**Comment by mperham** [comment]
-l debug

Wait, Is the panic in the client process pushing or in Faktory?
