### ISSUE TITLE
Faktory client error handling

### ISSUE THREAD

**Issue by beerlington** [contribsys/faktory#208]
I was curious if you had a list of errors that might come back from Faktory when pushing a job. We have a very early version of client that we're testing and ran into an issue where enqueuing a unique job returns an error and we were not handling it correctly and were naively re-enqueuing it.

If Faktory returns "-ERR" is there a case we would want to try sending to Faktory again without any changes to the payload?

If some errors should be retried, maybe a set of known status code that could be explicitly handled by the client would be possible?

**Comment by mperham** [comment]
Yep, the current Faktory protocol doesn't have a way to distinguish between real, unexpected errors (like a malformed payload) which should raise exceptions on the client-side, versus normal, expected errors (like a non-unique push) that the client might want to handle or ignore.

 I would welcome feedback on how the protocol could change to deal with this; I want to retain compatibility with RESP, Faktory's network protocol.  https://redis.io/topics/protocol

One proposal:

- `-ERR Some message` would signify unexpected errors which should raise an exception in the client.
- `-NOTUNIQUE Job is not unique` would signify expected events which can be handled inline by the client.

Each expected event would have a unique code, e.g. `NOTUNIQUE`, and a human readable message.  Each client package would have to decide how they surface these responses to the caller.

**Comment by beerlington** [comment]
I like that. Initially I was thinking something more generic like `-WARN` so we could choose to ignore all of them, but I think having something explicit like that would allow us to handle all `-ERR` errors one way and then the others could be handled or ignored as needed.

**Comment by mperham** [comment]
Today, in Ruby, `client.push(...)` can return a String (the JID) or raise an exception for ERR.  I'm thinking this would change things to return a Symbol for expected errors, something like this:

```ruby
result = client.push(...)
case result
when String
  return result # JID
when Symbol
  logger.warn("Got #{result} from server, ignoring") # :NOTUNIQUE
end
```

I think push should never return nil.

**Comment by beerlington** [comment]
That makes sense. I think we would end up doing something similar in our client. We don't expect to have unique jobs enqueued, but if it happened we would want to know about it in the logs.

**Comment by beerlington** [comment]
Do you know what other expected errors might come up besides non-unique jobs? We're trying to figure out which ones would come back with a "Halt: " prefix and which ones do not.

**Comment by mperham** [comment]
I don't have a canonical list.  There is a MALFORMED error if you push bad JSON so you might see three errors today: MALFORMED, NOTUNIQUE or ERR.  But I believe in retrospect that MALFORMED should be an ERR as it represents a bug in the client, not something which can be gracefully handled.
