### ISSUE TITLE
init go module files (go.mod & go.sum)?

### ISSUE THREAD

**Issue by zhaolion** [contribsys/faktory#209]

**Comment by mperham** [comment]
Why?

**Comment by zhaolion** [comment]
reasons:
1. these files are generated every time when i run any go tool cmd
2. go modules is awsome

Just a suggestion, It doesn't matter.

**Comment by mperham** [comment]
I don’t know anything about them. You didn’t provide any detail.

**Comment by mperham** [comment]
If someone can explain the advantages of go modules and what problems it would solve for Faktory development or downstream users, I'd be happy to hear more.  Right now I have a process that works for me. 😎
