### ISSUE TITLE
Implementation showing in argument printing

### ISSUE THREAD

**Issue by eborden** [contribsys/faktory#210]
Instead of printing valid `JSON`, arguments are being printed as `go` structs. It would be great to have the raw `JSON` printed instead.

![image](https://user-images.githubusercontent.com/545655/55890437-50202d80-5b78-11e9-97fe-da074089d31e.png)

**Comment by eborden** [comment]
![image](https://user-images.githubusercontent.com/545655/55890496-6201d080-5b78-11e9-9cc2-97da84c45fa7.png)

**Comment by mperham** [comment]
Easy PR if someone wants to contribute.
