### ISSUE TITLE
Faktory server does not send an OK when receiving an END

### ISSUE THREAD

**Issue by swelham** [contribsys/faktory#212]
In our faktory client we are seeing a connection closed error when trying to receive after sending the `END` command from our worker. Based on the protocol spec I was expecting to receive an `OK` before the connection is closed.

From looking through the source I can see the [end command](https://github.com/contribsys/faktory/blob/master/server/commands.go#L47) simply closes the connection. Should this be updated to send an `OK` first or should the client not expect to receive any further packets after issuing the end command?

**Comment by mperham** [comment]
Looks like neither Faktory nor FWR or FWG send or expect an OK after END.  I think this is a protocol doc bug.

**Comment by swelham** [comment]
Awesome, I will update our client to do the same 👍
