### ISSUE TITLE
Can't start container on AWS

### ISSUE THREAD

**Issue by bo-oz** [contribsys/faktory#213]
I'm trying to deploy a Faktory container to AWS. I push the docker image and define a task with the command:

"sh,-c,/faktory -b 0.0.0.0:7419 -e production"

Somehow, the container isn't starting with error:

`CannotStartContainerError: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"sh,-c,/faktory -b 0.0.0.0:7419 -e production\": stat sh,-c,/faktory -b 0.0.0.0:7419 -e production: no such`

Any idea what could be wrong?

**Comment by jbielick** [comment]
Your command should look like this:

```Dockerfile
CMD ["/faktory", "-b", "0.0.0.0:7419", "-e", "production"]
```

From what you posted above, it looks like you're passing a string with commas in it, which is being executed as one whole command named `sh,-c,/faktory`.... 

Could you check and make sure you're using array vs string correctly in your COMMAND declaration?

**Comment by talkl** [comment]
> Your command should look like this:
> 
> ```dockerfile
> CMD ["/faktory", "-b", "0.0.0.0:7419", "-e", "production"]
> ```
> 
> From what you posted above, it looks like you're passing a string with commas in it, which is being executed as one whole command named `sh,-c,/faktory`....
> 
> Could you check and make sure you're using array vs string correctly in your COMMAND declaration?
> 
> Here's an example from the Dockerfile in this repo:
> 
> https://github.com/contribsys/faktory/blob/6c57273da44562dfa0c8da3bbf88045ee2f57c25/Dockerfile#L10

@jbielick Hi Josh,

We want to start using your server in our startup. It looks very promising.
There isn't any documentation about deploying the server in a cloud environment such as AWS. only the docker command.
Do you have any reference to an article that maybe someone implemented?
