### ISSUE TITLE
Question: Module Support with Faktory

### ISSUE THREAD

**Issue by ClaytonNorthey92** [contribsys/faktory#215]
OS: macOS Mojave 10.14.2
Go Version: `1.12.4`

With the Go version I am using, I have module support enabled.  I want to follow the [Go example](https://github.com/contribsys/faktory_worker_go#usage), so I simply copy and paste that code into `main.go`.

#### main.go
```
package main

import (
	"fmt"
	worker "github.com/contribsys/faktory_worker_go"
)

func someFunc(ctx worker.Context, args ...interface{}) error {
	fmt.Println("Working on job", ctx.Jid())
	return nil
}

func main() {
	mgr := worker.NewManager()

	// register job types and the function to execute them
	mgr.Register("SomeJob", someFunc)
	//mgr.Register("AnotherJob", anotherFunc)

	// use up to N goroutines to execute jobs
	mgr.Concurrency = 20

	// pull jobs from these queues, in this order of precedence
	mgr.ProcessStrictPriorityQueues("critical", "default", "bulk")

	// alternatively you can use weights to avoid starvation
	//mgr.ProcessWeightedPriorityQueues(map[string]int{"critical":3, "default":2, "bulk":1})

	// Start processing jobs, this method does not return
	mgr.Run()
}
```

When I run `go build`, I receive the following:
```
go: finding github.com/contribsys/faktory/client latest
build faktory-test: cannot load github.com/contribsys/faktory/client: cannot find module providing package github.com/contribsys/faktory/client
```

If I turn module support off, the program builds (though I had to add the `"fmt"` import)

Am I doing something incorrectly to build this with module support?  Or is that something that is not supported?

**Comment by mperham** [comment]
I’ve never used modules before so I’m unclear what the problem is or how best to adjust Faktory for them.

**Comment by ClaytonNorthey92** [comment]
If no one minds, I would like to see if I can solve this and make Faktory support Go Modules.  Go Modules are where Go is heading (has headed by default, as of 1.12, planned to be finalized by 1.13).

**Comment by mperham** [comment]
DO IT!

**Comment by ClaytonNorthey92** [comment]
let me know what you think #216
