### ISSUE TITLE
Question: Is there any way to view a job's standard output from the web ui?

### ISSUE THREAD

**Issue by ClaytonNorthey92** [contribsys/faktory#217]
OS: macOS High Sierra 10.13.6
Go Version: 1.12.4

I am following the [Go example](https://github.com/contribsys/faktory_worker_go#usage) and I successfully added jobs that were process by Faktory.

I can see that in the UI

![Screen Shot 2019-04-28 at 8 39 22 AM](https://user-images.githubusercontent.com/8801919/56864500-2dbc4b80-6991-11e9-989b-1001b8ef96ce.png)

This job in the example prints to standard output, I don't see a way in the UI to view that nor did I find anything in the documentation in the Wiki.

Is there a way to view standard output for a job from the web ui?

**Comment by mperham** [comment]
Jobs execute in the worker process. Faktory is a separate daemon that might run on a different machine so you can scrape the worker process’s stdout or you’d  need to log to rsyslog or another distributed logging system.
