### ISSUE TITLE
How do I see failed jobs?

### ISSUE THREAD

**Issue by milesalex** [contribsys/faktory#218]
It seems that I can see the list of failed or processed jobs in the UI. Why?

![image](https://user-images.githubusercontent.com/421362/57048095-b44a8480-6c40-11e9-840c-4ce433f3d9bc.png)

**Comment by swrobel** [comment]
This [Wiki entry](https://github.com/mperham/sidekiq/wiki/Job-Lifecycle) from Sidekiq will help you understand the lifecycle (Sidekiq is built by the same author and Faktory's architecture is based on it)
