### ISSUE TITLE
Connection pool for Client

### ISSUE THREAD

**Issue by jmaeso** [contribsys/faktory#219]
I started to get some errors and seems the issue is because of this [TODO](https://github.com/contribsys/faktory/blob/master/client/client.go#L35) comment

Of course I checked the suggested the [faktory_worker_go](https://github.com/contribsys/faktory_worker_go/blob/master/pool.go) to check the implementation, but seems to be used for creating a pool for the client too: https://github.com/contribsys/faktory_worker_go/blob/master/runner.go#L117
(see the `faktory.Open()`)

Probably I'm missing something here on how to implement that connection pool for the client.

**Comment by mperham** [comment]
You are right that this hasn't been pulled into the faktory/client package.  The worker implements its own pool so you can safely use clients within a worker package but any custom Go process that wants to use multiple goroutines must copy the worker's pool code or use their own pooling package today. PRs are welcome to improve this.

Note that the faktory/client package is licensed MPL2.0, a permissive license, so I think we can use any BSD/Apache/MIT licensed pooling code.

**Comment by jmaeso** [comment]
What about moving the pool.go into a new package/subpackage to avoid an import cycle? Since the code in the pool is ready to work for both, a simple restructure would give us a new important feature.
This would require two different PRs, one in the client (here) and another one in the faktory_worker_go.
What do you think about this?

**Comment by mperham** [comment]
Sounds like a good idea to me.

**Comment by mperham** [comment]
Client package now has a pool.
