### ISSUE TITLE
Retrying Unique Jobs

### ISSUE THREAD

**Issue by john-griffin** [contribsys/faktory#220]
We have just noticed that if we use unique jobs they will not get retried if their `unique_for` is set beyond the first retry. This is different behavior to Sidekiq.

For our worker we need a `unique_for` of at least an hour but would still like retries to occur if something goes wrong within that time. Is there a way we can configure the job to do this?

**Comment by mperham** [comment]
Yep, this is a bug, will need to be fixed in 1.0.1.

**Comment by mperham** [comment]
The underlying issue is that the scheduler re-enqueues retries using the same Push() call that clients use when pushing the initial job to Faktory.  Since the lock exists, the unique middleware prevents the scheduler from re-enqueueing the job.
