### ISSUE TITLE
How do I go into the redis-cli

### ISSUE THREAD

**Issue by milesalex** [contribsys/faktory#226]
I want to flush the db

**Comment by mperham** [comment]
Here's an example https://github.com/contribsys/faktory/blob/master/Makefile#L97

**Comment by milesalex** [comment]
Im using the docker container. Do i exec in and run this?

**Comment by milesalex** [comment]
That didnt work.

**Comment by mperham** [comment]
Look at the dmon task right nearby in the same file.
