### ISSUE TITLE
Higher maximum connections, CPU Usage (vs Resque)

### ISSUE THREAD

**Issue by gbhrdt** [contribsys/faktory#227]
Hi! I really enjoy this work server and its easy-to-use API.

One thing I learned by hard yesterday is the limit of maximum 1.000 simultaneous connections. We are trying to send millions of notifications within seconds and therefore need to scale our workers which would then be more connections.

If we could specify the limit ourselves (like we can do with Redis), this would be very helpful!

Also, currently one golang worker uses 20 concurrent connections (should we try less and increase the worker count or try more concurrency and use less workers)?

At last, I see high CPU usage when many jobs are queued. We were using Resque before and this has not happened to us with Redis.

**Comment by mperham** [comment]
PRs welcome, "millions within seconds" is not a scale that I expect a single instance of Faktory to support. You will need to shard or use a different technology, background jobs are typically heavier weight (involving database transactions) and so they tend to top out at thousands/second.

And yes, there's been little optimization of Faktory's CPU burn at scale.  Each connection uses a Goroutine so 1000 connections means 1000 Goroutines inside Faktory, looking for CPU time.

**Comment by mperham** [comment]
Apologies for the delay here, I completely missed this issue.

**Comment by gbhrdt** [comment]
Thanks! We switched to NATS for now but may take a look at the newest updates in the future.
