### ISSUE TITLE
Support proxy configuration as a sub folder for webui

### ISSUE THREAD

**Issue by lightglitch** [contribsys/faktory#228]

**Comment by mperham** [comment]
If you can't spend two minutes writing a decent description of your issue, I'm not willing to spend my time deciphering it.  Be respectful of my time.

**Comment by lightglitch** [comment]
Sorry but for me the title is clear, but may not be for others so I clear the problem.

The issue is that I want to configure the webui using a nginx proxypass using a subfolder, because of that access url is something like "example.com/faktory/".

Because you use links with "/" in the beginning the path "/faktory/" is ignored and the webui doesn't work correctly.

**Comment by mperham** [comment]
Much better, that one or two sentences gives me the context to understand the issue.
