### ISSUE TITLE
faktory-pro : Depends: redis but it is not installable

### ISSUE THREAD

**Issue by johnvali** [contribsys/faktory#229]
When installing faktory-pro on Ubuntu 16.04 (xenial) from the faktory-pro repository it fails with an unmet / not installable dependency,

faktory-pro : Depends: redis but it is not installable

The strange thing here is that redis is not a valid package in Ubuntu xenial, but redis-server is.

We are following the instructions here,
https://github.com/contribsys/faktory/wiki/Pro-Installation

Shouldn't this be requiring redis-server instead?  I can install the package manually with,
dpkg --ignore-depends=redis -i /tmp/faktory-pro_VERSION_amd64.deb

However, that leaves the package with unmet dependencies on the OS.  Is there a fix for this issue?

Kind regards,
John

**Comment by mperham** [comment]
Hmm, looks like the package is called `redis` in CentOS and `redis-server` in Debian/Ubuntu.  Wonderful.

Glad you found that workaround, I'll get this fixed for the next release.

**Comment by johnvali** [comment]
This workaround does get the package installed, but breaks other packages on the OS.  We cannot get the package to be successfully installed in our build pipeline which is causing our builds to break.  We do indeed need a fix for this.  Could you please re-open and address?  Thank you.

**Comment by mperham** [comment]
That's surprising to me.  How does it break other packages on the OS?

**Comment by mperham** [comment]
Just `apt install redis-server` and then run your `dpkg` command to get it working, no?

**Comment by johnvali** [comment]
When doing that it will allow faktory-pro to be installed but any further installations/removals/upgrades of other packages will force an uninstall of faktory-pro.  How it breaks our build pipline is we have some steps towards the end that uninstall sensitive packages that cause the build pipeline to fail when it sees faktory-pro with unmet dependencies.

**Comment by mperham** [comment]
1.0.1-2 has been released with the updated dependency name.

**Comment by lemig** [comment]
Hello. I have got the same issue on Faktory OSS. Could you patch it too?

**Comment by mperham** [comment]
@lemig Please open a new issue with details, don't resurrect old issues.
