### ISSUE TITLE
Usage of the halt error response

### ISSUE THREAD

**Issue by swelham** [contribsys/faktory#230]
Is the `Halt: reason` error response still in use? I was looking through the codebase and I could only find the definition of the function and no instance of it being called.

**Comment by mperham** [comment]
It is used by Faktory Pro.

**Comment by swelham** [comment]
Doesn't that use the new `-NOTUNIQUE` response now?

**Comment by mperham** [comment]
Yep.

**Comment by swelham** [comment]
Right, do you have an example of when a halt message might come back?

I'm trying to work out if we need to still support this response in our faktory client now that we handle the new not unique response.

**Comment by mperham** [comment]
You can support -ERR as a generic "I dunno what happened" response and -SOMETHINGELSE as a context-specific error that can be acted on by clients.  NOTUNIQUE is the only specific error code in use today but if someone wants to fork Faktory and add their own middleware with specific errors, Halt() allows that.

**Comment by swelham** [comment]
Cool that makes sense.

Thanks 👍
