### ISSUE TITLE
"Job not found" errors

### ISSUE THREAD

**Issue by tombh** [contribsys/faktory#231]
I intermittently get errors like this that stop the worker from processing other jobs:
`16:19:38.904 [warn] [faktory] fail failure: Job not found a82e98fb13746eca74755f5d -- retrying in 32.138s`

I suspect it's because I have a large backlog of jobs and weird things happen when I deploy new versions of the worker app. I mean just new versions of my code, not of any of Faktory's components.

So how can a job not be found? I thought there was only one canonical reference to a job. And why should such an error completely stop the worker from doing anything else even though its concurrency is set to 30 or so?

I'm using the Faktory Docker image, the `faktory` binary there reports version 1.0.1. I'm using the latest Elixir [`faktory_worker_ex`](https://github.com/cjbottaro/faktory_worker_ex) client, v0.7.0, would I be better taking this up there?

**Comment by mperham** [comment]
I would open a ticket with fwex. That error shouldn’t stop processing.

**Comment by tombh** [comment]
Thanks for the quick response. I'll do that then.
