### ISSUE TITLE
fetch from multiple queues does not dispatch immediately

### ISSUE THREAD

**Issue by cjbottaro** [contribsys/faktory#232]
If I issue the command `FETCH queue_1 queue_2\r\n`, then immediately enqueue something to `queue_2`, the fetch command will timeout and not return the job (it will return `$-1\r\n`), and I have to issue the fetch command again in order to pick up the job.

If I issue the same fetch command, then immediately enqueue something to `queue_1`, then it works as expected: the job will be immediately returned.

Thanks!

**Comment by mperham** [comment]
The low-level storage API only allows blocking on a single queue, likely leftover from the rocksdb days.  Redis can block on multiple queues but not reliably. I'm not sure I want to implement that.

If you want lower latency in aggregate, you can randomly perturb your queues based on weights and different workers will block on different queues.

**Comment by mperham** [comment]
This has been implemented and released in #235
