### ISSUE TITLE
Support for a max concurrency per jobtype

### ISSUE THREAD

**Issue by swelham** [contribsys/faktory#233]
We are currently experiencing some issues where we are picking up jobs from faktory faster than an external service we are using can handle. This is resulting in many jobs failing and having to retry multiple times until the overall load has decreased enough for the remaining jobs to complete.

To solve this we are looking at implementing some form of concurrency management in our client, however this causes a few other issues such as blocking up our worker connections whilst they wait for the job to complete or having jobs timeout on faktory that are still queued up in our client.

I saw in an older issue (https://github.com/contribsys/faktory/issues/112) that you had queue throttling on the feature list. I haven't seen anything about this in the wiki and wondered if this was ever implemented or discarded as an idea?

**Comment by mperham** [comment]
Tuning concurrency is part of the long-term plan for Faktory.  It will be a commercial feature, not something available in the OSS version.

**Comment by swelham** [comment]
That's great to hear! We are building a work around for it now but we will definitely look forward to having that officially supported by Faktory.
