### ISSUE TITLE
Cannot enqueue Schedule Job now

### ISSUE THREAD

**Issue by pbrisbin** [contribsys/faktory#236]
I apologize if this is fixed in a more recent version, but I don't see it in Issues, so I'm going to report it anyway:

**Steps**:

1. Enqueue a job for later
2. Find it in Scheduled
3. Mark it and Add to queue

**Expected**:

It is added to queue

**Actual**:

![](https://files.pbrisbin.com/screenshots/screenshot.27832.png)

Also, if I go directly to the Job and click *that* Add to queue, it just does nothing.

We're still on version `Faktory Pro 0.9.7`.

**Comment by mperham** [comment]
Thank you, indeed it was a bug and an easy fix.  Will be in 1.0.2.

**Comment by pbrisbin** [comment]
Thanks for the quick fix! Now to bug my team to update... :)

**Comment by 5outh** [comment]
@mperham It looks like the scheduled jobs are still not being enqueued with the `add_to_queue` action, even though the backend accepts it as a valid action. This gif shows the behavior:

![Peek 2020-05-08 10-19](https://user-images.githubusercontent.com/959901/81414737-6a2e9580-9115-11ea-82f1-5acd80050990.gif)

We are on Faktory version `1.4.0`. Any help is appreciated. Thanks!

**Comment by 5outh** [comment]
@mperham It looks like the backend is now accepting the POST just fine, but does not enqueue the job. Clicking "Add to queue" just refreshes the page with the same details.

We are on Faktory 1.4.0 now. Thanks!

**Comment by mperham** [comment]
Yeah, I fixed the Scheduled index page. I forgot there is a Scheduled Job page with actions too. Use the index page for now and I'll get this fixed too.
