### ISSUE TITLE
Busy job is retrying

### ISSUE THREAD

**Issue by rafinkarki** [contribsys/faktory#237]
My JOB remains in a BUSY state for approx 30minutes and all of a sudden JOB moved to RETRY state. I am not expecting by busy state job to go in retry and process again. It should actually be pushed to FAILED or DEAD state.

**Comment by cdrx** [comment]
If your job takes more than 1800 seconds you need to set a longer `reserve_for` time when you queue up the job.

**Comment by MrJoy** [comment]
I'm seeing something similar, and my internal metrics suggest the jobs aren't actually running for that long.  I need to do a bit more digging to be 100% sure but I have zero instances in DataDog of this job completing successfully after more than about 90 seconds -- but I have a continuous state of instances of this job appearing to take 30+ minutes.  The worker process (Go) isn't panicking, nor is the Faktory server process.

**Comment by mperham** [comment]
@rafinkarki Are you disabling retries by setting `"retry": 0` in the job payload?

https://github.com/contribsys/faktory/wiki/Job-Errors#how-do-i-disable-retry-completely

**Comment by mperham** [comment]
@MrJoy Can you open your own issue with more context?

**Comment by MrJoy** [comment]
@mperham I wish I could, but right now I don't have any more information to give.  I routinely see jobs apparently in-flight for up to 30 minutes.  I have a metric I record on success of the job indicating how long it took.  The max value of that metric is never more than a couple minutes.  I need to put some instrumentation in place to record timings for _failed_ iterations of the job just to be sure -- but I don't see errors in our log aggregation system / error tracking system that indicate these jobs are failing (and in every place where I return an error from that job, I capture it first).

If/when I have more information, I'll file a ticket with the relevant context.
