### ISSUE TITLE
Move Building and Testing to Docker Containers

### ISSUE THREAD

**Issue by ClaytonNorthey92** [contribsys/faktory#238]
As of now, the `faktory` executable is built outside of a Docker container, then copied to it.  Also, the automated tests require some things to be installed on the system (like redis for example) that is running the tests.

We could take advantage of [multi-stage builds](https://docs.docker.com/develop/develop-images/multistage-build/) and move the testing and building to within Docker containers, so no dependencies would have to be installed on the machine building and testing (including CI/CD).  The final resulting container would still be the alpine container, as it is now, so it would remain small.

An unfinished example (having trouble with running the executable once it is copied over) might look something like this:

```
FROM golang:x as build

WORKDIR /faktory
COPY . /faktory
RUN apt-get update && apt-get install -y redis
RUN make prepare
RUN make test
RUN make xbuild

FROM alpine:3.8
RUN apk add --no-cache redis ca-certificates socat
COPY --from=build ./faktory/faktory /

RUN mkdir -p /root/.faktory/db
RUN mkdir -p /var/lib/faktory/db
RUN mkdir -p /etc/faktory

EXPOSE 7419 7420
CMD ["/faktory", "-w", "0.0.0.0:7420", "-b", "0.0.0.0:7419", "-e", "development"]
```

thoughts?

**note:** you could also optionally run tests with a build arg as to not do it every time

**Comment by mperham** [comment]
The build really only requires redis and go 1.x to be installed.  That's a pretty minimal set of requirements.  Meanwhile Docker is a complex requirement which I'd rather not force upon people who want to build Faktory. wdyt?
