### ISSUE TITLE
Job result not being reported properly.

### ISSUE THREAD

**Issue by MrJoy** [contribsys/faktory#241]
I'm seeing fairly frequent instances in which a job appears to be running for 30 minutes -- but, as far as I can tell, is not.

One of the job types where I see this has a metric that is recorded to DataDog when it successfully completes.  That metric is never above 90 seconds or so.  I _am_ seeing some job failures here and there, and I need to get concrete data on whether they're taking a _long time_ before they fail, but my intuition is telling me that isn't the problem.

Instead, I suspect this is related to _another_ problem we're having:  We're seeing bursts of dial errors with workers and other clients trying to connect to Faktory unsuccessfully.  What would happen if a job completed (success or failure), but the worker was unable to report that status back to the server because it couldn't get a connection to the server?

Looking at `faktory_worker_go`:

https://github.com/contribsys/faktory_worker_go/blob/master/runner.go#L260

```
				mgr.with(func(c *faktory.Client) error {
					if err != nil {
						return c.Fail(job.Jid, err, nil)
					} else {
						return c.Ack(job.Jid)
					}
				})
```

It appears that `.with` can return an error, but that this error is routinely ignored.

I don't think calling `panic` is appropriate for this situation, but perhaps some combination of the following might be helpful:

1. Getting and holding a connection to both retrieve the job, and report the result (and maybe as a side-effect, make the connection available to the worker via context so it can fire jobs without having to establish its own connection).
2. Introducing a pluggable logger mechanism so we can at least record that these failures are happening.
3. Having some sort of retry loop, specifically around reporting the results of a job.

The first option would have some risks/challenges of its own, of course.  You'd need to ensure the connection didn't time out, handle reconnecting if it did go away (either due to timeout or a server failure), etc.  I'm sure you have more insight into how it would impact operations concerns _in general_, so forgive me if it's an Obviously Stupid Idea.  That said, for situations involving a relatively high job volume (mid-hundreds- low-thousands per second), the many-transient-connections thing has proven to be a bit of a challenge (I'm paying attention to #219 / #222 for this reason, and we've been having to be careful about tuning things like `FIN_WAIT` and such in our server configuration).

**Comment by MrJoy** [comment]
Ok, I've instrumented the cases where one of the job types that is taking "30 minutes" fails.  The longest duration for that job type, regardless of cause, is 5 minutes.  So there are zero occurrences of the job that actually take 30 minutes, yet I'm still seeing it.  That reinforces my hypothesis somewhat.

**Comment by MrJoy** [comment]
@mperham What do you think about the pluggable-logger approach?  It would at least let me have visibility into the presence / severity of potential issues.

**Comment by mperham** [comment]
Faktory can’t have a pluggable logger. If you are talking about fwg, please open an issue there.
