### ISSUE TITLE
`dial tcp 10.4.20.67:7419: i/o timeout`

### ISSUE THREAD

**Issue by MrJoy** [contribsys/faktory#242]
(N.B. #241 is a symptom of this issue.)

We're seeing bursts of this error in production.  We have 6 workers with concurrency of 64, plus one node that is not a Faktory worker but fires jobs into Faktory based on HTTP requests that come in.  Workers are seeing the error when trying to fire new jobs from existing ones, and  the web server is seeing these errors as well.  There's a bit of a pattern involved where we get a burst once every hour, spanning about 15 minutes -- however, I don't know if that's because we're getting bursts of requests every hour or there's some sort of network tuning issue at play.  We've covered the basics (max files for all processes involved, FIN_WAIT setting for all machines involved, etc), but are still trying to narrow this down.

Our current best guess is that the 1 second dial timeout for establishing a connection to the Faktory server is relevant, and I'm going to be bypassing `faktory.Open` to modify that value and test things.

At a minimum, exposing this as a configurable option seems like a prudent option, no?  Would you accept a PR that creates a second method -- maybe `OpenWithServer`, allowing clients to pass in a `Server` object, in order to allow configuring of relevant settings without having to copy-paste the logic of `Open()`?

**Comment by mperham** [comment]
Happy to see PRs. Any APIs should mimic Go network APIs, eg Dial, etc.

**Comment by MrJoy** [comment]
It seems to me that this will require a PR on both faktory, and fwg -- the former for the client object, the latter for how the connections in the internal connection pool are configured.  The latter, however, is somewhat more complex and messy:  There's probably multiple tunable parameters worth exposing and you don't really have a mechanism set up for configuration that I saw.  Should I just add extra CLI options and call it a day, or are you worried that will blow up the complexity of the CLI?

**Comment by MrJoy** [comment]
Experimentally, we're seeing that 10 seconds works well -- but we haven't put connection pooling into place, and done other important work around this.  So, at the very least, it's a bit of a stress-testing situation.

**Comment by jbielick** [comment]
@MrJoy Sorry if this is an obvious debugging question, but what's the CPU usage like on your faktory server process during these timeouts? 1 second is somewhat generous for a TCP connection to be established, and since you're running a high concurrency, each of your 6 worker processes has a connection pool of 64 connections. Do your handlers create a new client when they're ready to push a new job from within a job? If so, that cilent connection might be a +1 open/close each time a push occurs? That's a lot of handshaking and socket handling your server would have to do. I've seen this occur for other faktory users where connection pools weren't reused efficiently.

**Comment by MrJoy** [comment]
@jbielick CPU usage is in the 40-60% range fairly continuously.  My web-hook handlers create a client at the start of the request, and will fire 1-N jobs using the same client.  My jobs that fire jobs are similar:  They create a connection at the start of handling the job, and use it to fire all jobs that they create (which is either 0-1, or 0-N depending on the job).  I have not put connection pooling in place yet, but it's on our list.

**Comment by mperham** [comment]
Are you closing the connections when done with them in your client? I'm worried the used sockets are staying open, leading to socket exhaustion and that's why you eventually see a burst of errors.

**Comment by MrJoy** [comment]
I am indeed closing them via defer.  I even double-checked all the sites where I obtain a connection to see if maybe i absentmindedly missed one.

We _did_ need to lower the `FIN_WAIT` timeout everywhere, and bump the `nf_conntrack` pool size on the server — which makes sense given the sheer number of jobs we’re churning through (about 40m/day right now).

**Comment by mperham** [comment]
Closing as stale. Reopen or send a PR if you make progress.
