### ISSUE TITLE
How do you quiet jobs on deployment?

### ISSUE THREAD

**Issue by nathanpalmer** [contribsys/faktory#246]
I couldn't see how this might be done from a remote container (i.e. not the worker itself.) We'd like to quiet the workers prior to database migrations getting executed. There seems to be a way [to quiet all the workers from the Web UI](https://github.com/contribsys/faktory/commit/ea0a14f6b9b041d8fed46f1fb66e03fe1d7a8826) which seems to pull down a list of all Heartbeats and then sends the quiet signal. 

However, outside of the main faktory process is there a way to pull down a list of heartbeats and then send that same signal to them? I can't find a whole lot of the protocol and can't readily see how it would be done using the ruby client. Is this possible?

**Comment by mperham** [comment]
The only way to do it via Faktory today is automating pressing the Quiet All button on the Busy page. Otherwise you’d need to build something custom.

**Comment by nathanpalmer** [comment]
Got it. Yeah, I was reading through the web ui code and thought that might be a potential way to do it. Thanks, will give it a try.
