### ISSUE TITLE
Readme Fix: "Taking care of business and working overtime"

### ISSUE THREAD

**Issue by jayarc** [contribsys/faktory#25]
Bachman-Turner Overdrive would probably really enjoy the shout-out but only if you get those lyrics perfect:

**Chorus:**
And I'll be taking care of business (every day)
Taking care of business (every way)
I've been taking care of business (it's all mine)
Taking care of business and working overtime, work out

I think the Readme needs an update.

**Comment by mperham** [comment]
updated
