### ISSUE TITLE
i/o timeout Closing connection

### ISSUE THREAD

**Issue by MostafaAhmed456** [contribsys/faktory#250]
Hi guys .

we are trying Faktory our client is python API wrote using python Falcon and workers also in python. the problem is when doing load test on the  API we got this error in faktory " i/o timeout Closing connection "
the code snippet below we use to push to faktory 

client code

`faktory_client = faktory.Client('tcp://ip:7419')`
  `faktory_client.queue('x', args=('1','2','3'))` 
 ` faktory_client.disconnect()`

worker code 

` w = Worker('tcp://ip:7419', queues=['default'],
                        concurrency=100)`
`w.register('recommendation', recommendation_updater)`

we are using machine with 8 CPU. utilization reaches 1% of CPUs . and we are using tcp in the connection to faktory .
we are trying to push 10K concurrent request .

**Comment by MostafaAhmed456** [comment]
yes I am using their code . and talked to them but did not get any response yet

**Comment by MostafaAhmed456** [comment]
@mperham  but this exception is raised from Faktory side not from python worker

**Comment by mperham** [comment]
Ok, can you give me a script to reproduce the issue so I can investigate?
