### ISSUE TITLE
Cannot build fpro Docker image

### ISSUE THREAD

**Issue by CaryLandholt** [contribsys/faktory#256]
I've been building a Docker image of fpro for some time now, but after the 1.1.0-2 release, the build fails with the following output.
```
W: GPG error: https://dl.contribsys.com/fpro/apt stable Release: Detached signature file '/var/lib/apt/lists/partial/dl.contribsys.com_fpro_apt_dists_stable_Release.gpg' is in unsupported binary format
E: The repository 'https://dl.contribsys.com/fpro/apt stable Release' is not signed.
```

I also tried rebuilding to a prior fro version with the same Dockerfile that originally succeeded, but that now fails as well.

**Comment by mperham** [comment]
I built the latest version with a new server running Ubuntu 18.04.3 which I believe includes major changes to the underlying Debian packaging tooling. I’ll have to spend a day or two figuring out how to work around as much of that crap as possible or rollback to .2.

**Comment by mperham** [comment]
I've made some tweaks to the repo builder.  Can you try again?

**Comment by CaryLandholt** [comment]
Just tried again but received the same error.

**Comment by mperham** [comment]
Ok, try again, I changed Release.gpg to use an ASCII format.  If you can enable any debug or verbose logging, please send me that too.

**Comment by CaryLandholt** [comment]
Failed with a different message.

```
tar (child): data.tar.bz2: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
```

**Comment by mperham** [comment]
I think that's your script?  I had to move the .deb to use gzip compression
because of a bug in the packaging tool, fpm.

**Comment by CaryLandholt** [comment]
Yep, had to add the gunzip statement.  Working now.

**before**
```shell
apt download faktory-pro
ar -x faktory-pro*.deb
tar -xjf data.tar.bz2 ./usr/bin/faktory
```

**after**
```shell
apt download faktory-pro
ar -x faktory-pro*.deb
gunzip data.tar.gz
tar xvf data.tar ./usr/bin/faktory
```
