### ISSUE TITLE
How to push a job from Ruby app to be consumed by non Ruby workers

### ISSUE THREAD

**Issue by nikoma** [contribsys/faktory#259]
How do I push (with Ruby lib) a job to a faktory queue that will be picked up by Go or other workers? 
???.perform_async(:something)

**Comment by mperham** [comment]
Good question, the wiki doesn't really cover deeper API usage. Something like this should work, where your go worker process is fetching from the go_work queue.

```ruby
job_hash = { jobtype: "go_func", queue: "go_work", args: [1,2,"hello"] }
cl = Faktory::Client.new
cl.push(job_hash)
```

**Comment by nikoma** [comment]
Great! Thank you. Do you have one example like this for C# as well or perhaps just an example how to send plain json to the faktory server?

**Comment by mperham** [comment]
I don’t know C# so I can’t help in this case. You can look into the source for your C# Faktory lib to see how it pushes JSON.

**Comment by nikoma** [comment]
When I use the hash it says: "all jobs need a jid parameter" and when I add this it says: "all jobs need a jobtype parameter" despite it being there.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by mperham** [comment]
I will add an Advanced wiki page tomorrow with details.

**Comment by mperham** [comment]
Can you post your exact code so we can help?

**Comment by mperham** [comment]
https://github.com/contribsys/faktory/wiki/The-Job-Payload wiki page has the bare minimum job:

```
{
  "jid": "123861239abnadsa",
  "jobtype": "SomeName",
  "args": [1, 2, "hello"],
}
```

**Comment by ziaulrehman40** [comment]
I am also trying to queue python jobs from ruby, but it got a little more complicated as once job finishes i need to send feedback through `ActionCable` channel, and the job needs to access `ActiveStorage`'s file and the DB being used by the rails app(these two can be worked out i guess, but the actioncable thing can be harder).
