### ISSUE TITLE
Add, remove some Pro statsd metrics

### ISSUE THREAD

**Issue by mperham** [contribsys/faktory#261]
Move forward under the assumption that people are using a Statsd server that understands metric tagging.

## Deprecate

These will be removed in a future release:

| Name | Type | Desc | Tags
| -- | -- | -- | --
| jobs.{jobtype}.count | Counter | Execution count for {jobtype}, increments upon ACK/FAIL | "queue:{queue}"
| jobs.{jobtype}.failed | Counter | Failed count for {jobtype}, increments on FAIL | "queue:{queue}"
| jobs.{jobtype}.perform | Gauge (time) | Time between FETCH and ACK | "queue:{queue}"

By creating metrics for each jobtype, we are exploding the cardinality, which can lead to big jumps in cost of storage. Many metrics SaaSes price based on unique metric name count. Instead each metric will have a `jobtype:#{jobtype}` tag, like so:

| Name | Type | Desc | Tags
| -- | -- | -- | --
| jobs.count | Counter | Execution count, increments upon ACK/FAIL | "queue:{queue}", "jobtype:{jobtype}"
| jobs.failed | Counter | Failed count, increments on FAIL | "queue:{queue}", "jobtype:{jobtype}"
| jobs.perform | Gauge (time) | Time between FETCH and ACK | "queue:{queue}", "jobtype:{jobtype}"

## Add

| Name | Type | Desc | Tags
| -- | -- | -- | --
| jobs.expired | Counter | Job expiration | "queue:{queue}", "jobtype:{jobtype}"
| uniq.lock | Counter | A unique job lock was taken | "queue:{queue}", "jobtype:{jobtype}"
| uniq.denied | Counter | A job push was denied due to uniqueness | "queue:{queue}", "jobtype:{jobtype}"
| uniq.unlock | Counter | A unique job lock was released | "queue:{queue}", "jobtype:{jobtype}"
| cron.push | Counter | A periodic job was pushed  | "queue:{queue}", "jobtype:{jobtype}"

**Comment by jbielick** [comment]
> Statsd server that understands metric tagging.

🎉  Really supportive of that move for metric naming.

>  Many metrics SaaSes price based on unique metric name count.

I think Datadog, at least, charge based on the unique combinations of name + each tag. May not save storage/usage costs in some cases, but still a much better way to organize metrics, segment alerting, group by, etc.

Had you ever considered `latency` by queue as a built-in metric? I know there's always been queue size, but that hasn't been as useful in the sidekiq world for monitoring / SLOs.

**Comment by mperham** [comment]
Thanks for the positive feedback! 😎

Faktory Pro can gather latency, but it's opt-in.  I forgot to document it but it's in the latest release already:

https://github.com/contribsys/faktory/wiki/Pro-Metrics#latency
