### ISSUE TITLE
UI not updated with paused status

### ISSUE THREAD

**Issue by scottrobertson** [contribsys/faktory#266]
Hey

I am calling `kill -TSTP 1` predeploy, but the UI is not updating to say the process is "quiet". Is this by design?

**Comment by mperham** [comment]
It’s possible the workers don’t report lifecycle state changes back to Faktory today. The quiet label may only appear when using the UI. I try to minimize load on worker developers and this is one instance of that.

**Comment by scottrobertson** [comment]
That makes sense. However, it does look like the ruby library is calling `fire_event(:quiet)`. Wouldn't that report back?

https://github.com/contribsys/faktory_worker_ruby/blob/8e38d231241c8e124bc845e5c2679d3b8724b2c1/lib/faktory/manager.rb#L57

**Comment by mperham** [comment]
The quiet event is fired local to the worker, it does not send anything back to the server.  The only recurring contact with the server is the heartbeat below and that only accepts a new state from the server.  If you signal TSTP locally, the server doesn't know anything about that and the worker does not report it (today), thus the current behavior.

https://github.com/contribsys/faktory_worker_ruby/blob/8e38d231241c8e124bc845e5c2679d3b8724b2c1/lib/faktory/client.rb#L93

**Comment by scottrobertson** [comment]
That makes sense. Would it be useful for me to implement that, or is it not
something you think is a good idea right now?

**Comment by mperham** [comment]
Sure, I'd love PRs to help solve your problems, that's why it's OSS!

**Comment by scottrobertson** [comment]
Perfect. Is there a message it should send when TERM is fired too?

**Comment by mperham** [comment]
"quiet" and "terminate" are the two state labels so use those.

**Comment by mperham** [comment]
If you send a PR for FWR, you can test it against master.  See that commit message.

**Comment by scottrobertson** [comment]
Thanks. Will let you know when I get around to it :)
