### ISSUE TITLE
Worker redeploy not sending jobs back to queue + process showing as active when its actually been killed

### ISSUE THREAD

**Issue by scottrobertson** [contribsys/faktory#268]
We had a job running on our 'dashboard-faktory" process, and I stopped that container (TSTP, TERM, sleep(40), KILL), however, the job was not returned to the queue. 

The worker also stayed on the busy page for a good few minutes after it was killed too.

![Screen-Shot-2020-01-10-11-02-53 33](https://user-images.githubusercontent.com/68361/72148715-63775800-3399-11ea-9911-359d59da4bde.png)

As you can see here, the job is shown as running, and the process is shown as active, however, the actual server process was killed (TSTP, TERM, sleep(40), KILL) well over 1 minute before this.

Eventually, the process disappeared, but now the job is stuck as busy. This will cause huge issues at production scale, as our concurrency limits will be eaten up by jobs that are not actually running.

![Screen-Shot-2020-01-10-11-03-33 16](https://user-images.githubusercontent.com/68361/72148836-ac2f1100-3399-11ea-8dad-6c8032d00360.png)

**Comment by scottrobertson** [comment]
Some more debugging on this. So the process is killed, and this is the logs:

<img width="664" alt="Screen-Shot-2020-01-10-12-43-23 12" src="https://user-images.githubusercontent.com/68361/72153840-e7840c80-33a6-11ea-9f66-7be0ecc4a429.png">

All looks good. But the job is still stuck in progress. This is then blocking any more jobs from running, as the concurrency is set to 1 (just for testing this).

![Screenshot 2020-01-10 at 12 44 43](https://user-images.githubusercontent.com/68361/72153945-2e720200-33a7-11ea-9a2f-e117a8f852ef.png)

**Comment by scottrobertson** [comment]
@mperham just FYI, this works nicely :)

**Comment by mperham** [comment]
Thanks for the followup, Scott. This issue had me worried so I'm happy the fix was this simple.

**Comment by scottrobertson** [comment]
@mperham I am not sure if anything can be done here, but when restarting the faktory server (it's hosted in kubernetes, so doing in place restarts is very hard), jobs can still get stuck.

**Comment by mperham** [comment]
Why are you restarting Faktory? It’s meant to run 24/7. Use HUP to reload config as necessary, shut down all workers before restarting Faktory. That should minimize issues.

**Comment by scottrobertson** [comment]
@mperham because when configs change, it has to restart. There is no way that i can see to update the configmap in kubernetes (that stores the config files) without restarting the pod.

**Comment by scottrobertson** [comment]
Will do some digging to see if there is a hacky way around this.

**Comment by mperham** [comment]
That’s a serious k8s limitation. I think of Faktory as a database, ie its a stateful service. Do you have the same limitation with postgresql or is that outside of k8s?

**Comment by scottrobertson** [comment]
They are outside of k8s. Will probably just have to move this outside of k8s then.

**Comment by jbielick** [comment]
@scottrobertson FYI I've put together a faktory helm chart. It watches the configs and sends Faktory a HUP when they change. You may not be able to switch to that chart for your deployment, but you're welcome to copy the method I used: https://github.com/AdWerx/charts/blob/88117f79fb345bdb79ab1414bf27cf558f177533/faktory/templates/statefulset.yaml#L29-L54

YMMV—let me know if I can help.

**Comment by scottrobertson** [comment]
@jbielick ohh interesting. I wasnt aware the container would even know about updated configmaps without being restarted. Thank you

**Comment by jbielick** [comment]
@scottrobertson if you mount an entire configmap to a directory, changes to the configmap will be propagated to the container (can take up to 10s), but if you mount via `subPath`, your container won't get updates. 

> SubPaths are not automatically updated when a ConfigMap is modified. Changes to a ConfigMap will need to be a new deployment which would result in the pods being recreated with the updated ConfigMap content.

https://dev.to/joshduffney/kubernetes-using-configmap-subpaths-to-mount-files-3a1i

There's some discussion about this in https://github.com/contribsys/faktory/issues/19#issuecomment-531521390

**Comment by scottrobertson** [comment]
@jbielick 💥  works perfectly, thank you! Any idea why it takes so long for the configmap to be updated?

**Comment by scottrobertson** [comment]
@mperham how do you propose we handle upgrades (regardless of it being k8s or not)? It will have to restart at some point, right?

**Comment by jbielick** [comment]
@scottrobertson 

> ConfigMap is updated to the moment when new keys are projected to the pod can be as long as kubelet sync period (1 minute by default) + ttl of ConfigMaps cache (1 minute by default) in kubelet.

https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#mounted-configmaps-are-updated-automatically

**Comment by scottrobertson** [comment]
Thank you @jbielick 

@mperham sadly this is still happening occasionally. Just redeployed the workers and a job is stuck as busy. Worker shut down as normal.

**Comment by mperham** [comment]
Can you give me more context/detail: step by step instructions, worker and server debug logs, etc.  The more clues I have, the easier to solve the mystery.

**Comment by scottrobertson** [comment]
@mperham I can't sadly. Unable to replicate it reliability. Seems to be ok at the moment.

**Comment by scottrobertson** [comment]
Really need a way to manually clear these out. This + having to have the reserve_for so high until we get the dynamic updating is really killing us. 90 jobs right now just stuck for a very long time.

**Comment by scottrobertson** [comment]
@mperham here you go. Just shut down the workers. Logs from the worker shutting down. And then you can see that the job is still in progress in the UI, blocking the concurrency too.

```
[data-collector-faktory-5bfbc5cf5c-qfg89] 1 TID-gtnd9d278 WARN: Terminating 1 busy worker threads
[data-collector-faktory-5bfbc5cf5c-qfg89] 1 TID-gtnd9d278 WARN: Work still in progress []
[data-collector-faktory-5bfbc5cf5c-qfg89] 1 TID-gtnd9d278 INFO: Bye!
```

![Screenshot 2020-01-20 at 20 09 29](https://user-images.githubusercontent.com/68361/72754835-d1552800-3bc0-11ea-8d8e-81e64792b1d2.png)

![Screenshot 2020-01-20 at 20 09 39](https://user-images.githubusercontent.com/68361/72754840-d3b78200-3bc0-11ea-8d17-6e9b7c45d054.png)

**Comment by scottrobertson** [comment]
```
redis /var/lib/faktory/db/redis.sock> ZRANGE working 0 -1
1) "{\"job\":{\"jid\":\"1d556a0b7157c0cf49725c55\",\"queue\":\"import_stripe_1\",\"jobtype\":\"BareStripe::TimeImportWorker\",\"args\":[\"62muqO5ZPriJTT\",1579478400,1579564799],\"created_at\":\"2020-01-20T20:06:59.2659758Z\",\"enqueued_at\":\"2020-01-20T20:06:59.266324711Z\",\"retry\":25,\"custom\":{\"bid\":\"b-VpBBW9JTMhC9rQ\"}},\"reserved_at\":\"2020-01-20T20:06:59.271705689Z\",\"expires_at\":\"2020-01-20T20:36:59.271705689Z\",\"wid\":\"0d83038f5dffb0ab\"}"
2) "{\"job\":{\"jid\":\"d48e2191825cf795c46879a1\",\"queue\":\"import_stripe_1\",\"jobtype\":\"BareStripe::TimeImportWorker\",\"args\":[\"4lep6VeZKR761I\",1579478400,1579564799],\"created_at\":\"2020-01-20T20:07:06.339961336Z\",\"enqueued_at\":\"2020-01-20T20:07:06.340211478Z\",\"retry\":25,\"custom\":{\"bid\":\"b-fYxpzw-ptQXYkw\"}},\"reserved_at\":\"2020-01-20T20:07:06.349632796Z\",\"expires_at\":\"2020-01-20T20:37:06.349632796Z\",\"wid\":\"2c355d8468bf3ed6\"}"
```

**Comment by mperham** [comment]
So there are two scenarios to consider:

1. The worker process loses network connection to Faktory for a few minutes. Jobs continue to process. Because we don't get a BEAT, Faktory reaps the worker record.  Should any associated in-progress jobs also be reaped? This might allow for duplicate job execution. I would think this is ok; the much more common scenario would be a crashing worker process and we want to release those resources so the jobs can process again ASAP.
2. The worker process shuts down. It should send FAIL for each job which doesn't finish. FAIL releases any resources and schedules the job to execute as a retry. The heartbeat will stop and Faktory will reap the worker record after a minute as above.

I think the change I need to make is to crawl the associated job reservations when a worker process dies as (2) and release those jobs immediately, rather than waiting for them to timeout.

**Comment by scottrobertson** [comment]
Based on what I can see, it's neither of those that are happening here though. From what you can see, the worker process does exit properly

```
[data-collector-faktory-5bfbc5cf5c-qfg89] 1 TID-gtnd9d278 WARN: Terminating 1 busy worker threads
[data-collector-faktory-5bfbc5cf5c-qfg89] 1 TID-gtnd9d278 WARN: Work still in progress []
[data-collector-faktory-5bfbc5cf5c-qfg89] 1 TID-gtnd9d278 INFO: Bye!
```

It seems to just be that the server is not releasing the jobs once the fail is sent.

Unless the process is actually being killed before the `fail` is sent to the server, since the jobs were finished so quickly after the `TSTP` is received??

**Comment by mperham** [comment]
You don't have timestamps on those logs so I don't know about timing. It's possible that the resource release upon FAIL is buggy.  I will double check.

I will go through this tomorrow morning and hopefully have improvements in the forthcoming 1.2.1.

**Comment by scottrobertson** [comment]
Thank you @mperham. This is the last big issue that I have found so far, so it would be awesome to make this solid.

We just passed 40 million jobs processed in Faktory :) 

Shame to say goodbye to the 4.5 billion in Sidekiq ha

**Comment by scottrobertson** [comment]
@mperham if it would be useful for me to demo this bug to you, then let me know. I can replicate it basically every time right now.

**Comment by mperham** [comment]
@scottrobertson See if that helps.

**Comment by scottrobertson** [comment]
@mperham will give it a go.

What happens if the jobs still take longer than the 25s faktory shutdown timer, or the 60s KILL command from kubernetes?

**Comment by mperham** [comment]
Right now jobs that go beyond 25 seconds in FWR are killed.  Part of that kill process sending FAIL to Faktory for each long job. FWR wasn't waiting for that kill process to finish, it was exiting the process within milliseconds and so there was a shutdown race condition if any given long job would be failed, leaving to it being stuck on the Busy page and holding the queue throttle.

**Comment by scottrobertson** [comment]
Seems to be working nicely so far :) will let you know as the days go on. Thank you.

**Comment by scottrobertson** [comment]
@mperham and will this automatically bubble up to cleaning up the "taken" in throttles? 

I am not 100% sure it has. But i should clear out all the old data, as perhaps it's got some stuff stuck from before this fix. What is the best way to do that? Before i did:

```
redis-cli -s /var/lib/faktory/db/redis.sock keys "taken:*" | xargs redis-cli -s /var/lib/faktory/db/redis.sock del
```

But is there a better way?

**Comment by scottrobertson** [comment]
![Screenshot 2020-01-21 at 20 26 35](https://user-images.githubusercontent.com/68361/72840571-7426a880-3c8c-11ea-8320-796eefed96d2.png)

:(

**Comment by mperham** [comment]
Ok, I'm trying to reproduce the issue, here's what I'm doing.

1. I have `LongJob`, which sleeps for 600 seconds. It uses a `long` queue with `concurrency = 1`.
2. Open a console and `perform_async`.
3. Start a faktory-worker with `-q long`.
4. Job starts. Lock appears Taken. Hit Ctrl-C.  After 25 seconds, fwr kills the job which fails it.
5. Job disappears from the Busy list, appears in Retries, lock appears Free.
6. Restarting faktory-worker, a LongJob immediately restarts.

Any thoughts about you are doing differently?

Worker log:
```
2020-01-21T23:06:45.969Z 84849 TID-owtpe6k8c LongJob JID-fde40297669550a3d970ff65 INFO: start
2020-01-21T23:06:46.091Z 84849 TID-owtpe6k8c LongJob JID-fde40297669550a3d970ff65 INFO: Running long
^C2020-01-21T23:06:58.113Z 84849 TID-owtpgei70 DEBUG: Got INT signal
2020-01-21T23:06:58.113Z 84849 TID-owtpgei70 INFO: Shutting down
2020-01-21T23:06:58.113Z 84849 TID-owtpgei70 INFO: Terminating quiet threads
2020-01-21T23:06:58.215Z 84849 TID-owtpgei70 INFO: Pausing to allow threads to finish...
2020-01-21T23:07:23.040Z 84849 TID-owtpgei70 WARN: Terminating 1 busy worker threads
2020-01-21T23:07:23.040Z 84849 TID-owtpgei70 WARN: Work still in progress [{"jid"=>"fde40297669550a3d970ff65", "queue"=>"long", "jobtype"=>"LongJob", "args"=>[], "created_at"=>"2020-01-21T19:12:02.46516Z", "enqueued_at"=>"2020-01-21T19:14:30.091128Z", "reserve_for"=>300, "retry"=>25, "failure"=>{"retry_count"=>1, "failed_at"=>"2020-01-21T19:12:41.498986Z", "next_at"=>"2020-01-21T19:14:28.37474Z", "message"=>"Faktory::Shutdown", "errtype"=>"Faktory::Shutdown" }}]
2020-01-21T23:07:23.041Z 84849 TID-owtpe6k8c LongJob JID-fde40297669550a3d970ff65 INFO: fail: 37.072 sec
2020-01-21T23:07:23.043Z 84849 TID-owtpgei70 INFO: Bye!
```

**Comment by scottrobertson** [comment]
Assuming Ctrl-C is sending `TSTP`, then yeah that is exactly what happens here.

It's worth noting, we had about 400 workers running at this point, and it was only those 2 getting stuck that time. Will try and replicate it again tomorrow.
