### ISSUE TITLE
Synchronous Jobs

### ISSUE THREAD

**Issue by scottrobertson** [contribsys/faktory#269]
We have a requirement for synchronous in some places. Right now with Sidekiq we use a batch (1 job) and then poll the batch status. Would we just do the same with Faktory, or can you think of a better way of doing it with Faktory?

**Comment by mperham** [comment]
Yeah, you'd just need to poll within your worker thread.

**Comment by scottrobertson** [comment]
Still need to use batches? Or can we check the 1 job directly somehow?

**Comment by mperham** [comment]
If you're just interested in one job, I would implement something in app: poll a database record, use for Redis pubsub, etc. But you could use a batch of one, just like Sidekiq Pro.

**Comment by scottrobertson** [comment]
@mperham thanks.

In sidekiq, there is `Sidekiq::Batch::Status`, but i am not seeing anything similar in Faktory Ruby. I am not seeing anything to indicate status on Faktory::Batch either. Ideas?

**Comment by mperham** [comment]
https://github.com/contribsys/faktory_worker_ruby/blob/91cb2b8cec412d15bf15c8dd370d9c5a7cdd3c2e/lib/faktory/batch.rb#L149

**Comment by scottrobertson** [comment]
@mperham oops thanks. Still not used to seeing multiple classes in 1 file!
