### ISSUE TITLE
Race conditions

### ISSUE THREAD

**Issue by andrewstucki** [contribsys/faktory#27]
Running the testing suite with `-race` enabled detects a number of race conditions. Some of them are purely in the test suite i.e. the count incrementing in goroutines in [storage/queue_test.go](https://github.com/contribsys/faktory/blob/master/storage/queue_test.go#L377) not being protected by a mutex, but some of them are deeper in the core, i.e. server/tasks.go appending to an internal tasks array [in one goroutine](https://github.com/contribsys/faktory/blob/master/server/tasks.go#L53) and ranging over it [in another](https://github.com/contribsys/faktory/blob/master/server/tasks.go#L95).

Might want to consider enabling `-race` on the tests to track these down and to generate a list of places that need fixing.

**Comment by mperham** [comment]
I've looked at -race before and the output was all false alarms; that's why I haven't enabled it.  For example, the task stuff is one-time initialization on boot, it isn't mutated at runtime.

**Comment by andrewstucki** [comment]
So, from the looks of it the two biggest offenders appear to be R/W safety around maps (see [Why are map operations not defined to be atomic?](https://golang.org/doc/faq#atomic_maps)) and atomic integer R/W for stats using [atomic.LoadInt64](https://golang.org/pkg/sync/atomic/#LoadInt64).
