### ISSUE TITLE
Add healthcheck capability within the docker container

### ISSUE THREAD

**Issue by CaryLandholt** [contribsys/faktory#271]
`curl` is not available, so need another mechanism for establishing the health of faktory

**Comment by mperham** [comment]
What about mounting /usr/bin/curl into the container with -v? I would prefer not to inflate the image by megabytes for this.

Is there a need for this? Has Faktory needed a health check in your experience?

**Comment by CaryLandholt** [comment]
Interesting idea.  And no, Faktory has been performing exceptionally.
But Faktory is a core infra dependency for us, so would like to stay in front of it as a just-in-case, particularly since it can't yet run in cluster mode.

**Comment by mperham** [comment]
Let me know if the -v trick doesn't work for you, we can document this on the Docker wiki page. Other suggestions welcome.

**Comment by hertzg** [comment]
The base image for `faktory` includes `wget` / `netstat` / `lsof` / `nc` tools (inherited form alpine maybe) which you could use for healthchecks.
