### ISSUE TITLE
Sidekiq Status

### ISSUE THREAD

**Issue by scottrobertson** [contribsys/faktory#272]
This is less of a request for @mperham and more of a question to the community.

Before moving to Faktory, we made extensive use of https://github.com/utgarda/sidekiq-status

Has anyone looked at building something similar? Obviously it's a bit more tricky as you would need an external data store since you cannot talk directly to the redis instance.

**Comment by mperham** [comment]
I would love to see specific use cases. I'm open to building this into Faktory but want to make sure I understand the problem, why it's valuable for Faktory to solve it rather than in some app-specific way, etc.

**Comment by scottrobertson** [comment]
Obviously I can only speak for our use case, but being able to see the % complete of a job is super useful. 

We have a lot of jobs that are a huge amount more efficient as 1 big job vs lots of smaller jobs, so they can be running for quite some time. Being able to see the progress is very nice.

You can also store random data in the status for each job too. All of our jobs are in the context of an "account", so we store that and then display it on the status page. This did require us modifying the gem code, but just a nice usecase i figured i would mention.

<img width="1209" alt="Screenshot 2020-01-18 at 19 40 15" src="https://user-images.githubusercontent.com/68361/72669528-97eab400-3a2a-11ea-96ad-d1b2baf1ddf0.png">

**Comment by mperham** [comment]
Thanks this is really useful information. This might dovetail nicely with other people’s request to extend the reservation for a job dynamically, if the reservation is extended every time you update the complete percentage that would solve both use cases at the same time.

**Comment by scottrobertson** [comment]
Didn't think of that! That solves a huge huge issue for us too then :)

**Comment by mperham** [comment]
Synergy! Business!

**Comment by scottrobertson** [comment]
@mperham just to note. The extension of the reservation time is much more critical to us vs the status dashboard etc. Just don't want to hold that up with the dashboard stuff :)
