### ISSUE TITLE
Update documentation to docker pull for Faktory Enterprise

### ISSUE THREAD

**Issue by dclausen** [contribsys/faktory#279]
The existing documentation states to use the following docker pull command:

$ docker pull docker.contribsys.com/contribsys/faktory-pro:1.2.0

However, I believe this should be updated for Faktory Enterprise customers to:

$ docker pull docker.contribsys.com/contribsys/faktory-ent:1.2.0

**Comment by scottrobertson** [comment]
https://github.com/contribsys/faktory/wiki/Ent-Installation

Fixed
