### ISSUE TITLE
PHP7 library dead

### ISSUE THREAD

**Issue by jcs224** [contribsys/faktory#280]
It looks like the PHP7 library has been deleted.

https://github.com/basekit/faktory_worker_php

I maintain the PHP5 library (but it should work fine with 7 too). I'll make sure it stays compatible with newer versions of Faktory and PHP.

**Comment by mperham** [comment]
Thanks for the tip, is there something I need to do?  You are welcome to edit the wiki page and delete the reference.

**Comment by jcs224** [comment]
Oh duh, forgot I could edit that 😅 done.
