### ISSUE TITLE
Cron not running

### ISSUE THREAD

**Issue by scottrobertson** [contribsys/faktory#282]
Cron's have suddenly stopped running. Nothing in the Faktory server logs. 

The jobs don't get created at all. In fact, i make sure the queue they are going into does not exist, and it doesn't even create the queue.

I don't know what to give you here to debug, since the issue is that just nothing happens. The cron countdown happens on the cron UI, but then it just goes to the next run.

About to restart the Faktory server.

**Comment by scottrobertson** [comment]
Restarting faktory server solved this. Sorry for the useless ticket, but as i said, there is very little i can give in terms of debugging.

**Comment by scottrobertson** [comment]
They have stopped running again. This is going to cause huge issues.

**Comment by mperham** [comment]
Is Redis out of disk? I’m as frustrated as you, we can’t debug an empty log.

**Comment by scottrobertson** [comment]
Disk space is fine

**Comment by mperham** [comment]
Turn off statsd output, maybe those errors are causing it?

**Comment by scottrobertson** [comment]
Already did :(

Scott

**Comment by scottrobertson** [comment]
Note that this is JUST crons. If i run the cron manually, and jobs that are enqueued inside that enqueue and run just fine.

**Comment by mperham** [comment]
I’m out of the house for the rest of the day so I can’t rubber duck anymore. If it was working fine and now suddenly doesn’t work, something must have changed. Check system logs, Redis logs, etc. I will review the cron code on Monday to ensure it is handling returned errors correctly.

**Comment by scottrobertson** [comment]
Nothing has changed on our end. Everyone else is out, and i am not supposed
to be working as i am sick.

Scott

**Comment by scottrobertson** [comment]
Nothing in redis logs

**Comment by mperham** [comment]
Go into the /debug page in the Web UI and see if anything looks wrong there. It’s a bit of a haystack though so a long shot. Also turn on debug log level with ‘-l debug’ so Faktory is more verbose.

**Comment by scottrobertson** [comment]
So with debugging enabled, i did see it enqueue once or twice, but then just nothing after that. No mention cron anywhere after that.

**Comment by scottrobertson** [comment]
Not seeing any errors at all in the logs

**Comment by scottrobertson** [comment]
And nothing odd on /debug that i can see.

**Comment by scottrobertson** [comment]
I am now running clockwork so i can try and go and get some rest.

**Comment by mperham** [comment]
A few things I've noticed while reviewing the code:

0. could uniqueness be an issue? I'm pretty sure uniqueness logs at DEBUG so you should see if so but you can turn it off if you are using it with these cron jobs.
1. cron doesn't export any stats into the blob returned by INFO, I can improve this to get more data in the future
2. the task runner runs all tasks on the same thread, this means a locked up or long-running task can delay or block other internal tasks (like cron) from running, for instance 1 million scheduled jobs that all need enqueuing at the same time.

Glad you found a workaround for now.

**Comment by scottrobertson** [comment]
0. None of the crons have uniqueness settings
2. Lots of batch activity, but no more than normal.

**Comment by scottrobertson** [comment]
Let me know if there is anything i can do/give you to make debugging this easier.

**Comment by mperham** [comment]
Can you give me debug log output from when you start Faktory to after it
stops working?

**Comment by scottrobertson** [comment]
Err, could do. It produces hundreds of lines per second though.

Scott

**Comment by mperham** [comment]
Uh, belay that then. Is there an overwhelming line I can disable in the
next release to minimize log size?

**Comment by scottrobertson** [comment]
The bulk of the logs are:

```
[faktory-server-6d8b48b495-2ckpf faktory-server] D 2020-02-10T17:09:27.995Z Batch: push for b-KzJg9lop_mF3Bw
[faktory-server-6d8b48b495-2ckpf faktory-server] I 2020-02-10T17:09:27.996Z Batch: ack for b-jwTP95hoKDdcIA
[faktory-server-6d8b48b495-2ckpf faktory-server] D 2020-02-10T17:09:28.009Z BATCH COMMIT b-QIRSkZOYfbS7ew
[faktory-server-6d8b48b495-2ckpf faktory-server] I 2020-02-10T17:09:28.017Z Batch: ack for b-QIRSkZOYfbS7ew
[faktory-server-6d8b48b495-2ckpf faktory-server] I 2020-02-10T17:09:28.018Z Batch: ack for b-KzJg9lop_mF3Bw
[faktory-server-6d8b48b495-2ckpf faktory-server] I 2020-02-10T17:09:28.025Z Batch: ack for b-fO1CC1Ww3CKDKQ
[faktory-server-6d8b48b495-2ckpf faktory-server] I 2020-02-10T17:09:28.043Z Batch: ack success callback for b-LQJJkcLV6mgR0g
[faktory-server-6d8b48b495-2ckpf faktory-server] I 2020-02-10T17:09:28.043Z Batch b-LQJJkcLV6mgR0g success!
[faktory-server-6d8b48b495-2ckpf faktory-server] D 2020-02-10T17:09:28.084Z Batch: push for b-KzJg9lop_mF3Bw
[faktory-server-6d8b48b495-2ckpf faktory-server] D 2020-02-10T17:09:28.084Z Batch: push for b-KzJg9lop_mF3Bw
[faktory-server-6d8b48b495-2ckpf faktory-server] D 2020-02-10T17:09:28.107Z BATCH COMMIT b-KzJg9lop_mF3Bw
[faktory-server-6d8b48b495-2ckpf faktory-server] I 2020-02-10T17:09:28.112Z Batch: ack success callback for b-Udwxl5VQX-tJ8g
[faktory-server-6d8b48b495-2ckpf faktory-server] I 2020-02-10T17:09:28.113Z Batch b-Udwxl5VQX-tJ8g success!
[faktory-server-6d8b48b495-2ckpf faktory-server] I 2020-02-10T17:09:28.176Z Batch: ack for b-zg2YkqcM-WH5ow
[faktory-server-6d8b48b495-2ckpf faktory-server] I 2020-02-10T17:09:28.177Z Enqueueing b-zg2YkqcM-WH5ow/success 6ed557ed9f6ff60101e2e4b3
[faktory-server-6d8b48b495-2ckpf faktory-server] I 2020-02-10T17:09:28.181Z Batch: ack for b-jwTP95hoKDdcIA
[faktory-server-6d8b48b495-2ckpf faktory-server] I 2020-02-10T17:09:28.183Z Enqueueing b-jwTP95hoKDdcIA/success 4ab9de8f49831cdf76db2c88
[faktory-server-6d8b48b495-2ckpf faktory-server] I 2020-02-10T17:09:28.183Z Batch: ack for b-yAVOWVm1kggCbA
[faktory-server-6d8b48b495-2ckpf faktory-server] I 2020-02-10T17:09:28.196Z Batch: ack success callback for b-OMaNEignkhz4qA
[faktory-server-6d8b48b495-2ckpf faktory-server] I 2020-02-10T17:09:28.196Z Batch b-OMaNEignkhz4qA success!
[faktory-server-6d8b48b495-2ckpf faktory-server] I 2020-02-10T17:09:28.197Z Batch: ack for b-3WI24k6NT2xsAw
[faktory-server-6d8b48b495-2ckpf faktory-server] I 2020-02-10T17:09:28.197Z Batch: ack for b-B1XyvDTh3hVq6w
[faktory-server-6d8b48b495-2ckpf faktory-server] I 2020-02-10T17:09:28.198Z Enqueueing b-3WI24k6NT2xsAw/success a68a16b3b8a6b3a7169b5d2e
[faktory-server-6d8b48b495-2ckpf faktory-server] I 2020-02-10T17:09:28.198Z Enqueueing b-B1XyvDTh3hVq6w/success 35b5078db394d3efd2089924
[faktory-server-6d8b48b495-2ckpf faktory-server] I 2020-02-10T17:09:28.229Z Batch: ack for b-4pNKPwz7Qd2qZg
[faktory-server-6d8b48b495-2ckpf faktory-server] I 2020-02-10T17:09:28.230Z Enqueueing b-4pNKPwz7Qd2qZg/success c64f05d1e38f8168263eeba6
[faktory-server-6d8b48b495-2ckpf faktory-server] I 2020-02-10T17:09:28.252Z Batch: ack for b-mk9u0WdqhZLU0Q
[faktory-server-6d8b48b495-2ckpf faktory-server] I 2020-02-10T17:09:28.256Z Batch: ack for b-RUX_-bNgFe1X1w
[faktory-server-6d8b48b495-2ckpf faktory-server] I 2020-02-10T17:09:28.283Z Batch: ack for b-8p4bGYHgZFcRhA
[faktory-server-6d8b48b495-2ckpf faktory-server] I 2020-02-10T17:09:28.283Z Enqueueing b-8p4bGYHgZFcRhA/success e58f2213a22891a8ef0d9eaa
[faktory-server-6d8b48b495-2ckpf faktory-server] I 2020-02-10T17:09:28.293Z Batch: ack for b-gYOa-xYVRA0t5w
[faktory-server-6d8b48b495-2ckpf faktory-server] I 2020-02-10T17:09:28.293Z Enqueueing b-gYOa-xYVRA0t5w/success 29cbf8ecfbff90ff78fc7df7
[faktory-server-6d8b48b495-2ckpf faktory-server] I 2020-02-10T17:09:28.296Z Batch: ack for b-3EAQXLtVWcDW1Q
[faktory-server-6d8b48b495-2ckpf faktory-server] I 2020-02-10T17:09:28.306Z Batch: ack for b-E7DDyqT75dDwSA
[faktory-server-6d8b48b495-2ckpf faktory-server] I 2020-02-10T17:09:28.411Z Batch: ack for b-cqMoLsDpzKcGDQ
[faktory-server-6d8b48b495-2ckpf faktory-server] I 2020-02-10T17:09:28.418Z Batch: ack for b-yAVOWVm1kggCbA
[faktory-server-6d8b48b495-2ckpf faktory-server] I 2020-02-10T17:09:28.428Z Enqueueing b-yAVOWVm1kggCbA/success c2e97faf376f414f5e5316d8
[faktory-server-6d8b48b495-2ckpf faktory-server] I 2020-02-10T17:09:28.440Z Batch: ack for b-C6FunhnZfFra4Q
[faktory-server-6d8b48b495-2ckpf faktory-server] I 2020-02-10T17:09:28.547Z Batch: ack for b-LlWYokzljgW6Fw
[faktory-server-6d8b48b495-2ckpf faktory-server] I 2020-02-10T17:09:28.563Z Batch: ack for b-ZsqB0YWQN7jHqw
```

**Comment by scottrobertson** [comment]
But i watched the logs last time i enabled the crons. There is just nothing about them in the logs, other than one or 2 initial enqueues.

**Comment by mperham** [comment]
Are you still seeing retries and scheduled jobs enqueue at the proper time?  They use the same task runner -- if they are working still, that narrows it down to cron itself, rather than the runner.

**Comment by scottrobertson** [comment]
Yeah, they are all working fine.

Scott

**Comment by mperham** [comment]
Can you give me a sense for how long cron works before it stops?  1 min, 5 min, 30 min? Cron will disable after 30 minutes unless running in production with a valid license.  I assume that's true for you but that's one normal case where cron will stop working (it does log a warning at the time).

**Comment by mperham** [comment]
Scan your logs for `Unable to push periodic job`. I have another suspect.

**Comment by scottrobertson** [comment]
The last time I tried it, the cron that we have set to run every minute only ran once. 

There are no `Unable to push periodic job` log entries.

**Comment by scottrobertson** [comment]
If i stop the workers, it will stop a lot of the logs. It should still enqueue the cron jobs without workers running yeah?

**Comment by mperham** [comment]
yes, cron is self-contained within faktory.

**Comment by scottrobertson** [comment]
ok, will give that a go.

**Comment by mperham** [comment]
Can I email you a dev build with a lot more cron debugging?

**Comment by scottrobertson** [comment]
Sure :)

**Comment by scottrobertson** [comment]
Ok, so just confirmed. Zero references to anything to do with crons in the logs. scheduled jobs enqueing fine.

**Comment by scottrobertson** [comment]
```
[faktory-server-67bc6cd948-nhzk2 faktory-server] D 2020-02-10T18:16:00.714Z Running task cron
[faktory-server-67bc6cd948-nhzk2 faktory-server] I 2020-02-10T18:16:00.714Z Starting cron cycle
[faktory-server-67bc6cd948-nhzk2 faktory-server] I 2020-02-10T18:16:00.714Z Cron enqueuing job for Cron::DatadogLoggerWorker
[faktory-server-67bc6cd948-nhzk2 faktory-server] D 2020-02-10T18:16:00.714Z Cron enqueueing Cron::DatadogLoggerWorker/ymC2-AuiVMFRr-wQ
[faktory-server-67bc6cd948-nhzk2 faktory-server] D 2020-02-10T18:16:00.714Z Next Cron::DatadogLoggerWorker job enqueue at 2020-02-10 18:17:00 +0000 UTC
[faktory-server-67bc6cd948-nhzk2 faktory-server] I 2020-02-10T18:16:00.714Z Nothing else to do this cycle, next job enqueues at: 2020-02-10 18:17:00 +0000 UTC

....

[faktory-server-67bc6cd948-nhzk2 faktory-server] D 2020-02-10T18:17:00.716Z Running task cron
[faktory-server-67bc6cd948-nhzk2 faktory-server] I 2020-02-10T18:17:00.716Z Cron disabled
```

**Comment by mperham** [comment]
That's utterly baffling.  The only time cron is ever disabled is with a log warning right beforehand.

**Comment by scottrobertson** [comment]
Anything else i can do to try and help debug?

**Comment by scottrobertson** [comment]
@mperham Running the new build. Annoyingly (maybe?) crons are running fine...

**Comment by scottrobertson** [comment]
oh no, just got a cron disabled. No backtrace before it though...

**Comment by mperham** [comment]
I'm gobsmacked, what the heck is going on?  the only thing I can think of is some sort of memory corruption flipping the disabled bit. The only line of code which toggles that bit has the PrintBacktrace() call right before it.

**Comment by scottrobertson** [comment]
```
[faktory-server-849596ff7d-l4gzq faktory-server] I 2020-02-10T19:10:00.715Z Cron disabled
```

That is now all i am getting. Nothing before or after related.

**Comment by mperham** [comment]
```go
func (cs *cronSubsystem) disable() {
	util.Info("!!!!!!!!!!!!!! Disabling cron !!!!!!!!!!!!!!!!")
	util.PrintBacktrace()
	cs.disabled = true
}
```

I'll send you a build which does not have that last line.

**Comment by mperham** [comment]
I'm going to pull in Go 1.13.7 to make sure this isn't a runtime issue.

**Comment by scottrobertson** [comment]
I got it. Emailing you.

**Comment by mperham** [comment]
Issue was an old license which had expired so the feature was disabling itself after X minutes.

**Comment by scottrobertson** [comment]
Thank you @mperham. Opened #284 to hopefully stop this in the future.
