### ISSUE TITLE
Surface when PRO/ENT license has expired, or is invalid

### ISSUE THREAD

**Issue by scottrobertson** [contribsys/faktory#284]
Either via the UI, logs, or both.

This will save hours of debugging in the future ha.

**Comment by mperham** [comment]
<img width="893" alt="Screen Shot 2020-02-10 at 1 01 19 PM" src="https://user-images.githubusercontent.com/2911/74189688-b7c65f80-4c05-11ea-9bc4-007960e91281.png">

**Comment by scottrobertson** [comment]
Awesome, thanks.
