### ISSUE TITLE
Exec format error

### ISSUE THREAD

**Issue by sazor** [contribsys/faktory#292]
I'm getting `standard_init_linux.go:211: exec user process caused "exec format error"` when trying to run `docker.contribsys.com/contribsys/faktory-ent:1.4.0`. Both previous versions 1.2 & 1.3 work just fine on the same machine (macOS Catalina). I have the same issue on google cloud k8s engine as well.
The error is thrown at the very beginning even before environment flag validation.

**Comment by mperham** [comment]
V1.4 uses the upx utility to compress the compiled binary. Perhaps this does not work on GCP. I will verify it works with Docker on vanilla Linux and macOS.

**Comment by mperham** [comment]
Yep, looks like the Docker image is bad.  I suspect it packed a macOS binary into the image.

I've repushed 1.4.0.  Try pulling it again and re-running.

**Comment by mperham** [comment]
Bad ordering of Makefile targets:

```diff
-prerel: clean test package macos dimg
-       pushd ../pro && make test package macos dimg || popd
+prerel: clean test package dimg macos
+       pushd ../pro && make test package dimg macos || popd
```

**Comment by sazor** [comment]
It works. Thank you!
