### ISSUE TITLE
Tracking API - State unknown, but all other values present

### ISSUE THREAD

**Issue by scottrobertson** [contribsys/faktory#293]
```
{"jid"=>"78400e2720b61d75741996bf", "percent"=>100, "desc"=>"[#44] Processing (100%) (1/1)", "state"=>"unknown", "updated_at"=>"2020-03-27T18:20:35.375362851Z"}
```

Any idea how this can happen?

**Comment by mperham** [comment]
https://github.com/contribsys/faktory/wiki/Ent-Tracking#the-dreaded-unknown-job-state

Any of these true? Did you mark the job with track:1?

**Comment by scottrobertson** [comment]
If it wasn't, wouldn't the rest of the values be missing?

**Comment by mperham** [comment]
You can still call track_progress and faktory will save the values. It just won’t track the state of the job internally.

**Comment by scottrobertson** [comment]
Ah ok.

I don't really need that state anyway, so I'll just ignore this. Track is
set in the code, but I don't really have time to debug.
