### ISSUE TITLE
Feature request: CloudWatch metrics

### ISSUE THREAD

**Issue by pbrisbin** [contribsys/faktory#295]
Would it possible to extend the [Pro Metrics](https://github.com/contribsys/faktory/wiki/Pro-Metrics) feature with a `[cloudwatch]` stanza, to send the same data there too?

I ask because if we knew Queue Depths in CloudWatch I _believe_ it would be trivial to set up Faktory consumers services (which are in ECS/Fargate) to automatically scale based on that. We would use both "outlets" at once, since `statsd` is perfect for DataDog integration, we just can't use it for scaling events.

**Comment by mperham** [comment]
Can you point me to some documentation that shows how to get things into cloud watch?

**Comment by pbrisbin** [comment]
Sure, something like this? https://docs.aws.amazon.com/sdk-for-go/api/service/cloudwatch/#CloudWatch.PutMetricData

I'm not sure, but you mind need to use other APIs to find-or-create the metric, before you can put data to it. It's also possible AWS will just create for you on the Put call.

**Comment by mperham** [comment]
Do you know of any statsd -> cloudwatch bridge?  I try to leverage open source standards where possible, not AWS specific APIs.

**Comment by pbrisbin** [comment]
An initial Google suggests that's totally possible! 

Does Faktory support multiple statsd outlets? I'm guessing we'd want to keep our current one and additionally report to this bridge service.

**Comment by mperham** [comment]
Yeah, I've been googling a bit and found this:

https://github.com/camitz/aws-cloudwatch-statsd-backend

You'd need to run the Statsd daemon somewhere and point Faktory to it. You'd configure it to have the cloudwatch backend and your other metric SaaS backend (e.g. datadog):

https://github.com/statsd/statsd/blob/master/docs/backend.md

That might (no warranties!) work. If you do try it, please report back how well it works.

**Comment by pbrisbin** [comment]
Perfect, looks like the Repeater backend would work to send metrics to our original `dog-statsd` listener. Or I guess we could turn off the `dog-statsd` part of the DD agent and use the direct Datadog Backend I see there.

Anyway, thanks for prodding the Googling. If we get this setup working I might come write up some documentation about it. Either way, feature request rescinded.
