### ISSUE TITLE
[roadmap idea] gRPC 

### ISSUE THREAD

**Issue by jbielick** [contribsys/faktory#306]
Jotting some ideas down here that have been swirling around a bit. I'm curious what feedback there is on some of these points.

### As Faktory features are added, client libraries may fall behind.

Not much to say here. Most of the time we're talking about +1 feature development in a client library to add one additional "command" or something to the client. It's not much, but its n+1 because of all the languages that might be supported.

### Client libraries have varying levels of reliability/maturity

One thing that inspires a lot of confidence about the ruby client is that it's very mature. It's been hardened over time and offers a lot of resiliency. Clients have to catch up to this, but the challenge is the same in every package—connection pooling?, reliable_push, efficient throughput, etc. 

#### Versioning

IMO one of the keys to unhindered iteration is backwards compatibility. Today, managing backwards compatibility is up to the client maintainer. It's reasonable, though, to see a world in which a client can declare the protocol version it wishes to use and negotiate that with the server. Potentially enabling it to reach backwards-compatible endpoints or implementations of server functionality (I know, this seems a little wild considering the data store would be shared, but I think it would be possible).

That would only be partially useful if you couldn't get all of the client libraries to participate or implement some versioning negotiation.

#### Wire protocol

After initially getting this right, there isn't a lot to worry about. The Redis wire protocol is fairly straightforward. However, management of default values (null values) amongst clients (and whether the server backfills these) can be quite inconsistent. Similarly, each client (in its lang) may want rich data structures for the payloads—again this is up to the author/maintainer.

I could see a lot of maturity added if there were a consistent API between the clients, a consistent implementation of serializing payloads and issuing commands over the wire. I think to achieve some consistency like that we're talking about some form of templating the client libraries. Which leads me to the next point.

## Idea: Use gRPC (or similar) 

Value proposition for gRPC: 

> With gRPC we can define our service once in a .proto file and implement clients and servers in any of gRPC’s supported languages, which in turn can be run in environments ranging from servers inside Google to your own tablet - all the complexity of communication between different languages and environments is handled for you by gRPC. We also get all the advantages of working with protocol buffers, including efficient serialization, a simple IDL, and easy interface updating.

#### Code generation—consistent connection and protocol semantics across clients and server

The connection handling and wire protocol aspect of each client library [could be generated code](https://grpc.io/docs/tutorials/basic/go/#generating-client-and-server-code). Even the server-side implementation would be generated. The Faktory server code could be thinned to just the implementation of commands and features.

#### Consistent language-native data structures in each client

Use of protobufs (gRPC does) allows code generation for [language-native structs in each client](https://developers.google.com/protocol-buffers)

#### Client/Server Versioning in all clients

You don't need gRPC for this, but I could see it easily fitting in and management of endpoints may be easier than storing some state for each connected client about the version it's using. [more info](https://docs.microsoft.com/en-us/aspnet/core/grpc/versioning?view=aspnetcore-3.1#version-number-services)

#### Reconnects and Retries (reliable_push)

AFAIK, gRPC clients reconnect when the long-lived TCP connection is severed. 

Retries are a bit of a mystery, though. There's an [old Proposal for client retries](https://github.com/grpc/proposal/blob/master/A6-client-retries.md), but it doesn't appear to have been implemented. However, I did see the concept of [deadlines present in the gRPC implementations](https://grpc.io/blog/deadlines/), which could offer a significant benefit if not a full "retry" mechanism. Ultimately, retries as described here seem to be categorized into the responsibility of a service mesh or two-way proxy (Linkerd, Envoy, Ambassador).

---

Personally, I don't have any experience with gRPC, but maybe this starts a conversation about what might be possible to level up client/server communication. I do think it would be possible to maintain current client APIs (no breaking changes), while swapping the client-server communication portion of the client in many (if not all) cases.

I found these hello-word-like examples of gRPC and Go, if it helps describe the implementation a little bit. 

- https://medium.com/@felipe.infantino.moreno/microservice-in-golang-using-redis-and-grpc-865587aa260c
- https://github.com/LevInteractive/dwarf

Question: can a front-proxy like Envoy be more valuable when used with Faktory if commands are HTTP/2 instead of TCP? That is, can commands be retried more easily if they're L7 and not just TCP packets?

**Comment by mperham** [comment]
This is something I considered when designing the protocol. I'm not a fan of binary protocols because they typically require some protocol library dependency (like grpc) which might have bugs and varying levels of support for different languages. They are also harder to debug on the wire.

HTTP/2 forces TLS which, again, adds a load of complexity that is unwarranted in development.

I liked the Redis protocol because it explicitly has the same core values: simplicity and developer-friendliness. Since there's already a ton of Redis protocol libraries, anyone can reference their own language's Redis client to help implement the Faktory protocol support.

Yep, in practice there will be a few VERBs that various clients might not support, notably Enterprise features like BATCH and TRACK. That's a tradeoff I recognized and accepted early on. The Ruby and Go implementations are there as a reference for anyone that wants to add support in their own language. I would even be happy to contract with OSS developers to implement them if there is customer demand in a language for using those features, e.g. $500 to implement BATCH in JS. Right now my Enterprise customers are using Ruby and Go, the two languages I can support myself, but there could easily be JS or Python need in the future.

**Comment by jbielick** [comment]
All that makes sense. I figured a lot of these things were considered.
