### ISSUE TITLE
Heroku add-on?

### ISSUE THREAD

**Issue by mperham** [contribsys/faktory#307]
Would Faktory users like to have a Heroku add-on which makes it trivial to setup a Faktory server and connect it to your app?

**Comment by sazor** [comment]
Yes, definitely! It'd simplify things for sure.

**Comment by alexmic** [comment]
@mperham Definitely, or allow for a remote Redis?

**Comment by mperham** [comment]
Opening up to a remote Redis would allow for networking error and latency performance issues that would be considered Faktory's fault by users. I consider Redis to be "embedded" in Faktory so a remote option is not on the table.

**Comment by alexmic** [comment]
@mperham Gotcha, makes sense.

**Comment by krainboltgreene** [comment]
I literally needed this a week ago, so yes! Looks like the one on heroku is sadly dead :(

**Comment by tmaximini** [comment]
This would be useful for us! Any ETA on this?

**Comment by aselder** [comment]
From an enterprise perspective, we'd love have faktory available via the AWS Marketplace. It's much easier on our accounting teams when we already have AWS as a designated payee and an established relationship.

**Comment by lukeshumard** [comment]
I would absolutely love this. My team ended up not choosing Faktory because of this about a year ago, even though the rest of our experience was essentially perfect.
