### ISSUE TITLE
Faktory loses tasks when high number of scheduled tasks trigger at the same time

### ISSUE THREAD

**Issue by joosterman** [contribsys/faktory#309]
## Use case
We have a 2 phase process that 1) generates personalized newsletters (slow) and 2) that send newsletters (instantatious). When we kickoff the mail newsletter process we send the generated newsletters as fast as possible. We want to experiment with the time a users get the newsletter. We have set it up such that the newsletters are generated, but for specific users in the experiment we hold on to their newsletter until time T (with a scheduled Faktory task) after which an enqueued task is send to the second phase by a worker causing the email to be send immediately. 

The use case is similar to https://github.com/contribsys/faktory/issues/257.

## Observation
We have around 25k tasks scheduled that should kick off _at the same time_. The behaviour we see is that it removes the tasks from the Scheduled queue, but that they then simply dissappear. They don't make it in into Enqueued.

## Likely cause
Faktory logs a warning message at that point:
`Error running task Scheduled: read unix @->/var/lib/faktory/db/redis.sock: i/o timeout`
My hypothesis is that it fails between removing the scheduled tasks and enqueuing them, i.e. in this function: https://github.com/contribsys/faktory/blob/master/manager/scheduler.go#L32

The error message indicates a read timeout and the Go Redis client specifies that the ReadTimeout defaults to 3 seconds. 
> Timeout for socket reads. If reached, commands will fail with a timeout instead of blocking. Use value -1 for no timeout and 0 for default. Default is 3 seconds.
https://pkg.go.dev/github.com/go-redis/redis/v8?tab=doc#Options

What I believe happens is that the pipeline is send to Redis (https://github.com/contribsys/faktory/blob/master/storage/sorted_redis.go#L274-L277) that starts executing but that takes more then the configured 3 seconds after which the client fails with the above error. At this point the client will not have data and the data is also deleted in Redis as (my assumption) the pipeline command will continue even when the client fails.

## Possible solution

A way to configure the Redis client configuration options such that a larger ReadTimeout can be set that fits this use case.

In addition I wonder whether the use of the pipeline script that immediately deletes the data is ideal, as this could result in jobs that are neither on the server nor in Redis.

## Environment

Runs in Kubernetes via chart: https://hub.helm.sh/charts/adwerx/faktory 
Faktory server version: 1.4.0

## About us
Blendle B.V., a Netherlands-based company with the mission of Saving Journalism. For our Ruby backend system we already make heavily use of Sidekiq and see Faktory as a good solution to extent that to our Python based systems.

---

What are your thoughts?

**Comment by mperham** [comment]
Yeah, I noticed this yesterday and need to revise that code to pull small batches of jobs at a time. In the meantime I’d strongly urge you to smear those jobs across 5 minutes of time.

**Comment by joosterman** [comment]
Thanks for the fast response and code changes! Do you have a release schedule when this hits a Docker image, or do you also have a nightly Docker build?

**Comment by mperham** [comment]
1.4.1 will be out this month but I don't have a more specific release plan. Smearing those jobs over time is still a good idea and will work around the issue.

**Comment by joosterman** [comment]
"This month" is perfect, thanks.

I tried to jitter with 30 seconds but that still produced too big blocks too handle. Based on your suggestion I'll extend that to a few minutes. 👍
