### ISSUE TITLE
Jobs not persisted across restarts

### ISSUE THREAD

**Issue by MarkMurphy** [contribsys/faktory#310]
Using the docker image: contribsys/faktory:1.4.0

There's two issues at play here. 

1. The [docs](https://github.com/contribsys/faktory/wiki/Installation#docker) suggest:

> In production, you'll want to use a persistent volume so Docker doesn't clear your data when restarting the container:
>
>```
>docker run --rm -it -v faktory-data:/var/lib/faktory -e "FAKTORY_PASSWORD=some_password" -p 127.0.0.1:7419:7419 -p 127.0.0.1:7420:7420 contribsys/faktory:latest /faktory -b :7419 -w :7420 -e production
>```

However, no data ends up being stored in the `faktory-data` volume.

When I go to the debug page in the Faktory UI I can see the following:

Data Location | /root/.faktory/db/redis.sock
-- | --

When I change the volume configuration to `faktory-data:/root/.faktory/`, the data _**is**_ then persisted across restarts

2. After getting jobs to persist across restarts I then encounter issue #298

**Comment by jbielick** [comment]
It's probably that its running in development mode and the presence of these lines:

https://github.com/contribsys/faktory/blob/e64be8eadde24582cb2e0c0b1fae97ea0d821e1d/cli/cli.go#L60-L64

**Comment by mperham** [comment]
Correct, you are running in development.

**Comment by MarkMurphy** [comment]
Ah ha! Excellent, thank you both.
