### ISSUE TITLE
Metrics Docs

### ISSUE THREAD

**Issue by MarkMurphy** [contribsys/faktory#311]
I recently deployed Faktory with a single job type that uses the default `retry` of 25. I left the service running overnight and came back to find that there was a recurring error with that job.

The stats in the dashboard:
<img width="1189" alt="Screen Shot 2020-06-24 at 12 09 42 PM" src="https://user-images.githubusercontent.com/873474/85582221-a198c900-b613-11ea-8c29-00d85309f1e9.png">

At first I was confused, if the retry is 25 and there's exponential backoff, how is there already 9 failed jobs and if this job errors each and every time, how is there 9 processed jobs?

But then I thought to myself maybe I'm reading these stats wrong. Is the processed count incremented regardless of failure? and is the failure count incremented each time a job fails (which I was interpreting as permanently failed)?

**Comment by mperham** [comment]
Yeah, I can understand how the terminology takes some time to understand.

* Processed - job execution attempt
* Failed - a failed job execution attempt
* Retries - number of jobs pending retry

You have one job, it is pending retry. Faktory has attempted to execute it 9 times and it failed 9 times.
