### ISSUE TITLE
Allow returning an error that has a retry-after time limit

### ISSUE THREAD

**Issue by diwu1989** [contribsys/faktory#312]
My background tasks query against Microsoft Graph API, and when throttled, the API returns a error 429 with a retry-after limit.
It would be great to be able to bubble up a specific error with retry after time so that there's explicit control of when the task retry is performed.

**Comment by scottrobertson** [comment]
Can't you just requeue the job with a scheduled start time?

**Comment by mperham** [comment]
Agreed, that's the most obvious way to implement this: have the worker catch the error and reschedule the job manually. Faktory doesn't know anything about different error types so I couldn't implement this today.
