### ISSUE TITLE
Batches of jobs with zero retries don't call OnComplete if they Fail

### ISSUE THREAD

**Issue by diegoy** [contribsys/faktory#317]
In the below scenario, a Batch where its jobs have retry set to zero, if one of them fails the onComplete is never called.

#### Batch Setup

```golang
jobComplete := faktory.NewJob("JobComplete", map[string]string{})
batch.Complete = jobComplete

batch.Jobs(func() error {
	jobA := faktory.NewJob("JobA", map[string]string{})
	jobA.Retry = 0
	batch.Push(jobA)

	jobB := faktory.NewJob("JobB", map[string]string{})
	jobB.Retry = 0
	batch.Push(jobB)

	return nil
})
```
#### Scenario 1: All jobs executed with success
 
```
"level":"debug","msg":"============== Job A =============","time":"2020-08-20T11:56:23-03:00"}
{"level":"debug","msg":"============== Job B =============","time":"2020-08-20T11:56:23-03:00"}
{"level":"debug","msg":"============== Job Complete =============","time":"2020-08-20T11:56:23-03:00"}
```

#### Scenario 2: Job A pass but Job B fails

```
{"level":"debug","msg":"============== Job A =============","time":"2020-08-20T11:56:37-03:00"}
{"level":"debug","msg":"============== Job B =============","time":"2020-08-20T11:56:37-03:00"}
2020/08/20 14:56:37.908523 Error running JobB job Jzx-tgnwsWF6IUBg: failed Job B
```
In this case Job Complete never get's called

And looking at the batch details on the dashboard it stays like this.
![image](https://user-images.githubusercontent.com/1043265/90788525-45cd8200-e2dc-11ea-80a3-92839aabf37d.png)

#### Scenario 3: JobA and JobB retry set to 1 and JobB fails

```
{"level":"debug","msg":"============== Job A =============","time":"2020-08-20T12:04:11-03:00"}
{"level":"debug","msg":"============== Job B =============","time":"2020-08-20T12:04:11-03:00"}
2020/08/20 15:04:11.712080 Error running JobB job gUdx1ecv0TVX31XP: failed Job B
{"level":"debug","msg":"============== Job Complete =============","time":"2020-08-20T12:04:11-03:00"}
{"level":"debug","msg":"============== Job B =============","time":"2020-08-20T12:04:30-03:00"}
2020/08/20 15:04:30.817840 Error running JobB job gUdx1ecv0TVX31XP: failed Job B
```` 

With retry 1 `Job Complete` is called and `Job B` goes gets called again later.

#### Which Faktory package and version?
Ent 1.4.1

#### Which Faktory worker package and version?
Faktory Worker Go [Master](https://github.com/contribsys/faktory_worker_go/commit/c439c1be0f518e024d63e953eec5e5174430a9c9)

**Comment by diegoy** [comment]
Hey @mperham could you please release a new version with this fix? 
We need this to a feature that we're building.

**Comment by mperham** [comment]
Set the Retry value to -1 for now, that should get you similar behavior. I will release a new version in September.
