### ISSUE TITLE
go get -u does not get the latest version

### ISSUE THREAD

**Issue by spellgen** [contribsys/faktory#318]
If you do `go get -u github.com/contribsys/faktory` without specifying a version you get the `v0.5.0`-tagged version. I think `go get`'s behavior is to pick the most recent `v1.2.3` version and only if there are none of that format will it start considering tags of the form `v1.2.3-xyz`. As it is now one has to request those versions explicitly (`go get -u github.com/contribsys/faktory@v1.4.1-1`)

Deleting that first `v0.5.0` tag would probably result in a more user friendly behavior for your repo.

**Comment by mperham** [comment]
Good feedback, thank you! I've pruned all tags that do not conform to the `vX.Y.Z-A` format.

**Comment by dontlaugh** [comment]
Hey there. I just got bit by this, so I came searching the issues.

This worked for me

```
go get -u github.com/contribsys/faktory@v1.4.2-1
```

My first call to `go get` led me down the wrong path

```
$ go get github.com/contribsys/faktory/      
go: github.com/contribsys/faktory upgrade => v0.5.0

$ go build
go: finding module for package github.com/contribsys/faktory/client
main.go:10:2: module github.com/contribsys/faktory@latest found (v0.5.0), but does not contain package github.com/contribsys/faktory/client
```

I'm not quite sure what's going on here. I don't think I've ever fetch faktory libraries before. :shrug:

**Comment by dfang** [comment]
@mperham  this breaks `go mod tidy` in go 1.15

```
$ go run main.go
go: finding module for package github.com/contribsys/faktory
go: github.com/contribsys/faktory: package provided by github.com/contribsys/faktory at latest version v0.5.0 but not at required version v1.4.2-1


$ go mod tidy
go: finding module for package github.com/contribsys/faktory
go: github.com/dfang/webhook-demo imports
	github.com/contribsys/faktory: package provided by github.com/contribsys/faktory at latest version v0.5.0 but not at required version v1.4.2-1
```

go.mod
```
module github.com/dfang/webhook-demo

go 1.15

require (
	github.com/contribsys/faktory v1.4.2-1
	github.com/rs/zerolog v1.20.0
)
```

**Comment by spellgen** [comment]
since v0.5.0 is no longer a tag maybe you have some cleaning up to do? Did
you try removing your vendor for an just to be sure: `go clean -modcache`
