### ISSUE TITLE
AWS Integration

### ISSUE THREAD

**Issue by talkl** [contribsys/faktory#323]
> Your command should look like this:
> 
> ```dockerfile
> CMD ["/faktory", "-b", "0.0.0.0:7419", "-e", "production"]
> ```
> 
> From what you posted above, it looks like you're passing a string with commas in it, which is being executed as one whole command named `sh,-c,/faktory`....
> 
> Could you check and make sure you're using array vs string correctly in your COMMAND declaration?
> 
> Here's an example from the Dockerfile in this repo:
> 
> https://github.com/contribsys/faktory/blob/6c57273da44562dfa0c8da3bbf88045ee2f57c25/Dockerfile#L10

@jbielick Hi Josh,

We want to start using the server in our startup. It looks very promising.
There isn't any documentation about deploying the server in a cloud environment such as AWS. only the docker command.
Do you have any reference to an article that maybe someone implemented?

_Originally posted by @talkl in https://github.com/contribsys/faktory/issues/213#issuecomment-706648163_

**Comment by mperham** [comment]
Faktory is a Linux daemon. You start an EC2 instance, install Faktory per the wiki page and it’s running. You can also look up Kubernetes in the issues if you want a more robust Faktory HA installation.

**Comment by mperham** [comment]
I've started a new AWS wiki page to cover how to create a Faktory service in ECS. It does require the upcoming v1.4.2 release.

https://github.com/contribsys/faktory/wiki/AWS
