### ISSUE TITLE
Systemd configuration for Ubuntu 18.04 doesn't allow you to enable the Faktory service.

### ISSUE THREAD

**Issue by mattshort** [contribsys/faktory#324]
- Which Faktory package and version? faktory-pro 1.4.1-1

In Ubuntu 18.04 installing from "deb https://dl.contribsys.com/fpro/apt stable main" I've noticed the following.

- The install creates /etc/systemd/system/multi-user.target.wants/faktory.service
- When I run `systemctl is-enabled faktory.service` it returns disabled
- `systemctl enable faktory.service` returns Failed to enable unit: File /etc/systemd/system/multi-user.target.wants/faktory.service already exists
- `systemctl status faktory.service` shows it is running from the /lib/system/system/faktory.service file.

I believe if the /etc/systemd/system/multi-user.target.wants/faktory.service file wasn't created that would be a fine fix. The end user could enable the service if they wanted.

**Comment by mperham** [comment]
Hmm, I'm not sure what's wrong. I don't believe the package creates any files in /etc/systemd. Here's the postinst packaging script:

https://github.com/contribsys/faktory/blob/2c3afe7134cfd9da30cb24ec9fef52b27b52a4eb/packaging/scripts/postinst.deb.systemd#L12-L17

which creates the .service file in /lib/systemd and enables it. I can't explain why `is-enabled` is showing false.

**Comment by mattshort** [comment]
Closing this issue 😳 it appears that the ansible task I was using replaced the symbolic link causing this issue. I installed a fresh copy manually to verify that I'm crazy. Sorry about that!
