### ISSUE TITLE
fpro 1.4.2 docker not found

### ISSUE THREAD

**Issue by CaryLandholt** [contribsys/faktory#328]
Executing `docker pull docker.contribsys.com/contribsys/faktory-pro:1.4.2` results in the following exception.
`Error response from daemon: manifest for docker.contribsys.com/contribsys/faktory-pro:1.4.2 not found: manifest unknown: manifest unknown`

1.4.1 is downloaded but not 1.4.2.

**Comment by mperham** [comment]
Whoops, build script bug. Thank you!
