### ISSUE TITLE
Started at time on processes list changes frequently

### ISSUE THREAD

**Issue by navaneeth** [contribsys/faktory#331]
# Configuration

|||
|----|----|
|Which Faktory package and version?|1.4.1|
|Which Faktory worker package and version?|v1.4.0-1. Golang|
|Concurrency per worker|20|
|Worker processes|5|
|Faktory server|Hosted on a VM in AWS (8GB)|
|Faktory workers|Hosted on ECS. 5 Workers|

# Issue

- Since last few days we are noticing that process list in Faktory UI will eventually gets cleared and since no workers are available, jobs will not be picked up
- When faktory shows no processes in the list, actual worker processes (ECS tasks) are still active and running. It looks like Faktory worker lost connection with the server. We see the following error on the server
```
2021-01-02T10:13:00.684Z Unexpected socket error: read tcp 172.17.0.2:7419->172.31.29.217:49808: use of closed network connection
W 2021-01-02T10:13:00.684Z Reaped 1 lingering connections, this is a sign your workers are having problems
W 2021-01-02T10:13:00.684Z All worker processes should send a heartbeat every 15 seconds
```
- When I forcefully kill the worker processes on ECS and restarts, everything will work for next one hour or so. Then the same issue repeats

# Temporary workaround

- We have increased the CPU limit set on the ECS task to 2048 and things seems to be stable. 
- But even process list seems to be changing quite often. `Started` column in process list shows different value for different processes.  Ideally started time on ECS worker process and the one in Faktory's process list should match. But in our case they are very different. ECS task is running for last 12 hours, but faktory shows started as *1 hr ago*

![Screenshot_2021-01-06 Faktory](https://user-images.githubusercontent.com/317288/103776758-ed620b80-5055-11eb-9c03-60e8aa55df63.png)

This is the ECS task definition file:

```
{
    "name": "worker",
    "image": "<imagename>",
    "cpu": 2048,
    "memory": 1024,
    "essential": true,
}
```

- Once in a while, I can see process list showing only 2 or 3 processes (we have 5 running) and after few seconds remaining processes shows up. It looks like they are loosing the heart beat signal for sometime. Not sure what is causing this. 

Any help would be great!

**Comment by mperham** [comment]
I suspect you are seeing this https://github.com/contribsys/faktory_worker_go/issues/47

**Comment by mperham** [comment]
I've tagged v1.4.2 if you want to try out the latest.

**Comment by navaneeth** [comment]
Pulled latest version and all working fine. Thanks

**Comment by Laksh47** [comment]
@navaneeth So was this issue happening 1.4.2 or earlier?

Which version fixed this for you?
