### ISSUE TITLE
Run faktory with an external Redis deployment

### ISSUE THREAD

**Issue by dustMason** [contribsys/faktory#337]
I know I'm far from the first to express this (this issue is a duplicate of https://github.com/contribsys/faktory/issues/200)

We would love to be able to run faktory against a separate redis deployment. We have been running sidekiq enterprise in production for years and have a great deal of trust in it. There is a project on our team to create a "paved road" replacement for sidekiq to support our golang services, and faktory is an excellent fit. It has been rejected for consideration because we are unable to operate our own backing redis cluster at this time. The reasoning that customers would blame faktory for redis-related performance / scaling issues would not apply to our case.

Please consider allowing users of Faktory Enterprise to run Faktory against an external Redis cluster 🙏

**Comment by mperham** [comment]
I'm working on this right now. I hope to have something people can test this month.

**Comment by mperham** [comment]
Is it sufficient to merely detect the presence of REDIS_URL in the ENV and use that? How does Elasticache make itself known to a given process?

**Comment by dustMason** [comment]
Elasticache just provides an endpoint url that you provide to your application. An env var would work fine for us 👍

**Comment by mperham** [comment]
If anyone wants to test Faktory Enterprise with remote Redis, email mike@contribsys.com. I will send you a raw Faktory Enterprise binary that you can test. You will need an Enterprise license to use it in production mode.

**Comment by mperham** [comment]
<img width="229" alt="Screen Shot 2021-02-22 at 10 37 59 AM" src="https://user-images.githubusercontent.com/2911/108754122-67612d80-74fa-11eb-8045-ed4a070acc2d.png">

**Comment by mperham** [comment]
Low Redis round-trip latency is important for Faktory performance. My local Redis shows 100-200µs latency during testing. If your latency is above 5-10ms (i.e. 5000-10000µs), you will start to see performance issues.

**Comment by mperham** [comment]
This will be in 1.5.0, coming in a week or two.

**Comment by mperham** [comment]
https://github.com/contribsys/faktory/wiki/Ent-Remote-Redis
