### ISSUE TITLE
Worker requirements 

### ISSUE THREAD

**Issue by cdrx** [contribsys/faktory#34]
I’m working on a Python worker for Faktory and have a couple of questions.

Do all workers need to implement BEAT? What is FLUSH for?

**Comment by mperham** [comment]
Workers should send a BEAT every N seconds, typically 15 seconds.  After 60 seconds without a BEAT, the worker is considered gone and disappears from the Busy web page.

FLUSH clears the entire DB.  It's useful for test suites where you reset state after every test, like Redis' FLUSHDB.  I can't think of a usecase where a worker would use FLUSH.

**Comment by cdrx** [comment]
Thanks. Can you use labels to target the worker group for a job?

eg, can I assign a job to any worker with `label=golang` and another job to any worker with `label=ruby`?

**Comment by mperham** [comment]
Not today, labels are currently web ui only.  It might be neat to be able to target a set of workers with a given label but that's TBD.

**Comment by mperham** [comment]
RIght now, queues are the way to route jobs, so you might have a "python" queue for jobs that require a python worker.

**Comment by cdrx** [comment]
Thanks

**Comment by cdrx** [comment]
If the v (initially 1) from an AHOY doesn't match the client, should it refuse to connect? What are your plans around backwards compatibility in the protocol?

**Comment by mperham** [comment]
I think the client should print a warning that it is out of date and might have trouble.  Upgrade recommended.

Protocol changes will be limited to major versions but I'll be a little more cavalier in the 0.x timeframe since the basics are still solidifying, e.g. #30

**Comment by cdrx** [comment]
Got it. Should I treat `v` as a number (ie the next option will be `2`) or a version number like `1.1`?

**Comment by mperham** [comment]
yes, monotonically increasing integer.  I'll eventually create a page which documents the changes in each version.

**Comment by cdrx** [comment]
@mperham is it deliberate behaviour to always run without a password, if TLS is not enabled?

**Comment by mperham** [comment]
The security policy is meant to be "safe by default" while also being friendly to localhost developers.  I'm not a security expert so I welcome feedback about how to best easily achieve both goals.

With a password but no TLS, the password is exposed via HTTP Basic Auth.  The command port password exchange is hashed but I can't do anything about basic auth (afaik?).  Without TLS, the command connection can still be MITM'd and the Web UI replayed.  In other words, password without TLS isn't much security at all.

So yeah, the current security policy is "if you care about security, you need to set up TLS first".

**Comment by cjbottaro** [comment]
I don't send a BEAT at all and I notice my workers stick around in the UI indefinitely.  Does Faktory have to see at least one BEAT before it starts expiring workers?

Also, how to connect to Faktory servers as a "client" (.e.g for PUSH messages only)?  It seems like `wid` is required in the handshake and then the connection shows up in the UI as a worker process.

**Comment by mperham** [comment]
@cjbottaro Yeah, I think I forgot about that case.  I need to support pure producer connections which produce jobs but don't consume.

**Comment by mperham** [comment]
@cjbottaro Opened #36.
