### ISSUE TITLE
Autoscaling: running/idle workers stats per queue

### ISSUE THREAD

**Issue by jdupl123** [contribsys/faktory#341]
At the moment INFO return the size of each of the queues and summary stats on tasks such as Busy and Workers. 

Ideally for Autoscalling I would like to maintain the workers that are currently working and sufficient workers to service the queue. 

Would it be possible to return the number of busy(hearbeating + running) workers per queue?

**Comment by mperham** [comment]
You'd need to track this elsewhere as workers don't report the queues they are working with. They can call `FETCH a b c` at one minute and `FETCH d e f` at another.
