### ISSUE TITLE
License validation with a grace period

### ISSUE THREAD

**Issue by lucasteligioridis** [contribsys/faktory#348]
A grace period for the license with some logs would be incredibly ideal.

If our license is now not valid, we'd love some sort of grace period (24 hours?), before we go into "commercial" mode, that gives us time to setup alerting and renew the license correctly without losing features in production. Not sure exactly what this would look like, but I hope you get the idea here.

We really just need enough time to:
1. React to a license that is no longer valid
2. Renew said license and apply accordingly to have minimal impact to the service

**Comment by mperham** [comment]
Here's what happens today with 1.5.0. Faktory checks the license status 30 minutes after bootup. If the license has expired, you'll get a notice in the logs and a large banner on the Web UI homepage.

<img width="878" alt="Screen Shot 2021-04-15 at 12 47 31 PM" src="https://user-images.githubusercontent.com/2911/114929707-00207500-9de9-11eb-83af-0045dbcc2259.png">

<img width="1073" alt="Screen Shot 2021-04-15 at 12 47 42 PM" src="https://user-images.githubusercontent.com/2911/114929717-03b3fc00-9de9-11eb-9e33-f60899259176.png">

The issue really is with the expiration datetime. I don't want to have to regularly issue new licenses to a customer and each customer has a different payment term (monthly, annually) and expiry. Right now the credit card billing will email you three times over a week to let you know if there are any card billing problems. Invoicing has one payment reminder. I don't have any way to add a "past due" state and there's no way to guarantee anyone is paying attention anyhow.

I think the simplest thing is to just add a calendar reminder for yourself to verify billing every year.

**Comment by lucasteligioridis** [comment]
From our perspective we would still have a calendar reminder or something along those lines are a kind reminder to ourselves.

Guess I was wondering if there was a proactive "alert" we could have as well, rather than reactive.

Do we receive any courtesy email to tell us our license is expiring X days before expiration date? I'd be happy with that too to be honest :)

**Comment by mperham** [comment]
For annual credit card subscriptions, yes. You get a "renewing in one
week, update your card here" email. Not for monthly (as that would be too
often) and not for invoices.

**Comment by lucasteligioridis** [comment]
Yep thats fair enough 👍🏼

**Comment by mperham** [comment]
The Licensing page documents the license logic. Please open a new issue if you have specific questions or suggestions.
