### ISSUE TITLE
Alternative license model?

### ISSUE THREAD

**Issue by lucasteligioridis** [contribsys/faktory#349]
In some environments where it's a little bit harder to "phone home" due to specific security requirements.

Something that might work could be a "time based" license option, so if we purchased a 1 month license, it would act like a certificate, its only valid from the time of purchase for a month and can utilise system clocks / date / time to understand when the license has expired.

Obviously if you picked this option it would require the customer to have to swap out licenses each time they're about to expire, but that onus would be put onto the customer to rotate accordingly if this option for licensing was chosen.

**Comment by mperham** [comment]
Faktory Enterprise 1.6.0 adds support for unlimited, annual licensing.

https://github.com/contribsys/faktory/wiki/Licensing#unlimited-license
