### ISSUE TITLE
Persistent disk mount in docker container documentation

### ISSUE THREAD

**Issue by robpingxu** [contribsys/faktory#353]
- Which Faktory package and version?
1.5.1

I have `contribsys/faktory` image running on Google Compute Engine VM and was mounting a persistent disk according to the documentation for docker at:
https://github.com/contribsys/faktory/wiki/Installation

The data wasn't persisting after a restart so I looked in the container and found the data sitting at `/root/.faktory/db/faktory.rdb`

Swapped the mount to `/root/.faktory` and it seems to be working.

**Comment by mperham** [comment]
If you run Faktory in production via “-e production”, it will persist to /var/lib/faktory.

**Comment by robpingxu** [comment]
Ah, I see. So I need to set that as an additional container arg in GCE.
