### ISSUE TITLE
Faktory UI Bootstrap 5 upgrade

### ISSUE THREAD

**Issue by saurori** [contribsys/faktory#359]
Placeholder issue to discuss upgrading the UI from Bootstrap 3 -> 5.

Pinging @mperham to add additional context.

**Comment by mperham** [comment]
Thanks for asking and I appreciate the offer! My request is that any upgrade keep the similar static assets as today. I don't want a dynamic build process which creates the bootstrap.css. I hope this is not a problem!

**Comment by saurori** [comment]
Not a problem. Makes it a bit more tedious albeit simpler, but shouldn't be an issue.

**Comment by mperham** [comment]
You are certainly welcome to add tasks to the Makefile which document and help with creating the static CSS but I want this to be something I only have to run every time I want to upgrade Bootstrap, not with every Faktory build or release.

**Comment by saurori** [comment]
I went ahead with the original strategy and updated the static files (will PR something tomorrow). Making a front-end build process (with SASS, webpack, etc) could be another project that would make it easy to build custom bootstrap css and js dist files using only the modules you want. The development experience would be nicer as well (live reload css/js changes, hashed asset files, etc).
