### ISSUE TITLE
Support producer connections

### ISSUE THREAD

**Issue by mperham** [contribsys/faktory#36]
Right now, all connections are supposed to send a WID.  Oops, I forgot: not all connections are from workers!  It will be normal for app servers to push jobs to Faktory and these connections should not be part of the data displayed on the Busy page.  Consuming processes == workers == listed on Busy page.  Figure out how this will change the HELLO and heartbeat handling.

**Comment by cdrx** [comment]
Perhaps a new client connection should send it’s capabilities as part of the ‘HELLO’ 

Something like ‘can_consume’ and ‘can_produce’?

The list could be filtered by connections with the right capabilities.

There could be ‘can_quiet’ or ‘can_terminate’ for the worker to indicate if that functionality is available. It would be nice to progressively add functionality without needing all the worker implementations to update at the same time :)
