### ISSUE TITLE
WebUI unresponsive after a while in production

### ISSUE THREAD

**Issue by amehrdad88** [contribsys/faktory#364]
- Using Faktory 1.5.1 with docker 

I have been experiencing the exact same issues as this closed issue: #154 

Basically, after a few minutes of restarting the docker container, the WebUI just slows down (all pages excel Home work) but is very slow. All pages other than Home load in 2-3 seconds, Home loads in 10+ but the graphs do not load and the network call to the server fails. Jobs still continue running, no issues there.

Also noticed RAM is creeping up (started at 70mb, going up to 300mb now and keeps going up).
Thanks

**Comment by mperham** [comment]
I need more information. Show me the log output. Show me the contents of the debug page.

**Comment by mperham** [comment]
You’ve overloaded Faktory. It has a hard limit of 2000 worker connections
to Redis.

**Comment by mperham** [comment]
Sorry, 1000.

https://github.com/contribsys/faktory/blob/master/cli/cli.go#L174

**Comment by amehrdad88** [comment]
Thanks. I just have a few processes currently on Faktory (I use faktory_node_workers) and have 7 workers connected. Is there any other way to overload Faktory? I send about 200 jobs per hour (across 6 workers) and the actual processing of it seems to work well

<img width="1179" alt="processes" src="https://user-images.githubusercontent.com/17452273/121380851-d710f200-c90a-11eb-8de1-f8feecbb50ab.png">

**Comment by mperham** [comment]
Sounds like the node worker package might not be pooling connections but
rather creating a new connection every time and not closing old
connections? Best practice is for each worker process to use a small pool
of open connections to talk to Faktory.

**Comment by amehrdad88** [comment]
Thank you, will look into that.

**Comment by jbielick** [comment]
Default concurrency in FWN is 20, which would be a pool of (max) 22 connections per process. That would be well under the 1000 connection limit. 

@amehrdad88 could you share your concurrency settings and how you’re starting faktory node worker processes if you open an issue on faktory_worker_node?
