### ISSUE TITLE
Publish arm64 Enterprise binaries for Linux

### ISSUE THREAD

**Issue by clarkdave** [contribsys/faktory#366]
- Which Faktory package and version? *1.5.1*

Attempting to install Faktory Enterprise on an arm64 Linux fails because the repository does not seem to have an `arm64` binary:

```sh
$ uname -m
aarch64

$ apt update
W: Skipping acquire of configured file 'main/binary-arm64/Packages' as repository \
  'https://dl.contribsys.com/fent/apt stable InRelease' does not seem to provide it

$ apt install faktory-ent
E: Unable to locate package faktory-ent
```

This means it's not possible deploy Faktory Enterprise on ARM Linux machines such as [AWS Graviton](https://aws.amazon.com/ec2/graviton/).

As an additional benefit, the availability of arm64 Enterprise binaries for Linux would allow Faktory Enterprise to run inside a Docker container on an Apple Silicon mac, something that isn't currently possible (the published `macos.arm64` binaries can't run inside Docker, and trying to run the amd64 Enterprise binaries in Docker via emulation does not work, as noted in https://github.com/contribsys/faktory/issues/342)

**Comment by mperham** [comment]
Yeah, I was waiting until I picked up an ARM MBP and could test this new platform myself. It seems like I read a new rumor every day that new MBPs are around the corner.

**Comment by clarkdave** [comment]
If there's any way I can help let me know! I have access to Intel and Apple Silicon macs, and ARM Graviton instances (which I was hoping to deploy Faktory Enterprise on)

**Comment by mperham** [comment]
Can I email you a private binary next week and you can run it through some acceptance testing on your different platforms? Since I’ve already got ARM support for Faktory, Enterprise shouldn’t be much more work.

**Comment by sloan-dog** [comment]
As a workaround for local testing you could run a minikube cluster locally (which runs its own vm supported on apple silicon), and run faktory as a stateful set via official docker images and the helm chart.
