### ISSUE TITLE
Add new bulk push command

### ISSUE THREAD

**Issue by mperham** [contribsys/faktory#386]
Add `PUSHB` for pushing many jobs with one network call.

```
PUSHB json
> PUSHB [{job},{job},{job},...]
{}
> PUSHB [{job},{job},{job},...]
{"123456789": "Invalid something or other"}
```

`PUSHB` takes a JSON-formatted Array of job Hashes. The return value is a JSON-formatted Hash of `JID: Error` pairs, empty if all jobs were pushed successfully.

**Comment by conradpronto** [comment]
We rely heavily on `push_bulk` with Sidekiq currently and it would be most useful to have similar support when using faktory.  Our goal is to push large batches (10s or 100s of thousands of jobs) from our Rails app to an elixir microservice.
