### ISSUE TITLE
Support `reserve_for` in Cron jobs

### ISSUE THREAD

**Issue by jeremyowensboggs** [contribsys/faktory#387]
- Which Faktory package and version?
**1.4.1**
- Which Faktory worker package and version?
**Enterprise Cron job**

Are you using an old version? Yes, 1.4.1
Have you checked the changelogs to see if your issue has been fixed in a later version?
**yes**

Hi, we are using Faktory Enterprises cron jobs. Faktory Enterprise 1.4.1 
One of our jobs takes an hour to run, but when started from the cron, it looks like it is ignoring the reserve_for. We have it set the following way in the toml file:
```
[[cron]]
  # every 6 hours
  schedule = "30 */6 * * *"
  [cron.job]
    queue = "default"
    type = "<our task>"
    retry = 1
    reserve_for = 4000
```

**Comment by mperham** [comment]
Yep, already fixed and will be in 1.6.1. I verified there's no other traits in the job payload which need special handling so I hope this won't happen again.
