### ISSUE TITLE
manifest for docker.contribsys.com/contribsys/faktory-ent:latest not found

### ISSUE THREAD

**Issue by crogers-operationalresults** [contribsys/faktory#406]
- Which Faktory package and version? ent, latest
- Which Faktory worker package and version? n/a
- Please include any relevant worker configuration n/a
- Please include any relevant error messages or stacktraces
```
echo $FAKTORY_PASSWORD | docker login docker.contribsys.com --username $FAKTORY_USER --password-stdin
Login Succeeded

docker pull docker.contribsys.com/contribsys/faktory-ent:latest
Error response from daemon: manifest for docker.contribsys.com/contribsys/faktory-ent:latest not found: manifest unknown: manifest unknown

docker pull docker.contribsys.com/contribsys/faktory-ent
Using default tag: latest
Error response from daemon: manifest for docker.contribsys.com/contribsys/faktory-ent:latest not found: manifest unknown: manifest unknown

docker pull docker.contribsys.com/contribsys/faktory-ent:1.6.1
1.6.1: Pulling from contribsys/faktory-ent
2408cc74d12b: Already exists
946a1dd434a7: Already exists
f1f77618307b: Pull complete
ffb53ebefa23: Pull complete
ab1c0d8a63d3: Pull complete
778ebfebd55c: Pull complete
Digest: sha256:60a43e25f96d0f73c57b124bf2373e5c1c85f3e21dedb3ed9310b7f3fda6ebd8
Status: Downloaded newer image for docker.contribsys.com/contribsys/faktory-ent:1.6.1
docker.contribsys.com/contribsys/faktory-ent:1.6.1
```
Are you using an old version? n/a
Have you checked the changelogs to see if your issue has been fixed in a later version? n/a

https://github.com/contribsys/faktory/blob/master/Changes.md
https://github.com/contribsys/faktory/blob/master/Pro-Changes.md
https://github.com/contribsys/faktory/blob/master/Ent-Changes.md

**Comment by mperham** [comment]
You can pull 1.6.0 for now. I don't believe there were any major fixes in 1.6.1. I will investigate after vacation.

**Comment by crogers-operationalresults** [comment]
Exactly

**Comment by mperham** [comment]
I've updated the build script to include the `latest` tag. I can't figure out how to tag the existing version, maybe the multi-arch support is preventing the obvious `docker tag contribsys/faktory-ent:1.6.1 contribsys/faktory-ent:latest`.

**Comment by crogers-operationalresults** [comment]
That's perfectly fine, thank you Mike!
