### ISSUE TITLE
Quiet / stop may cause (buggy) worker implementations to spin

### ISSUE THREAD

**Issue by cdrx** [contribsys/faktory#41]
When a worker calls `FETCH`, if there is no work to be done then the server will wait 2s before returning, which is great because there should usually be a worker waiting to accept a new job and the end to end latency is nice and low.

If a worker has its status set to quiet or stop then when worker calls `FETCH` it will get an immediate empty response. If a worker depends on the 2s timeout to `FETCH` for flow control then it'll spin and send 100s of `FETCH` requests / s that will never get any job.

If a worker is responsible for its own flow control, then it'll need to slow the frequency of `FETCH` requests which will increase the latency of tasks through the system. 

I think if a worker calls `FETCH` on a quiet'd / stop'd connection then the server should wait 1s and then return an err ERR.

What are your thoughts? If you think it makes sense I'll create a PR

**Comment by mperham** [comment]
Great idea.

**Comment by mperham** [comment]
I'm afraid we can't return an error because the BEAT is async.  You can quiet a worker in the Web UI but it won't get that quiet signal until the next BEAT.  In the meantime, it might make many FETCHs.  I think the best we can do is add a sleep to prevent CPU burn.  WDYT?
