### ISSUE TITLE
Panic crash

### ISSUE THREAD

**Issue by navaneeth** [contribsys/faktory#410]
- Which Faktory package and version?  - 1.5.1
- Which Faktory worker package and version? - Running as Docker container in k8s
- Please include any relevant worker configuration
    - Golang based workers
    - 3 worker processes
- Please include any relevant error messages or stacktraces

```
panic: signal: killed

goroutine 17 [running]:
github.com/contribsys/faktory/storage.bootRedis.func2(0xc00012c420, 0xc00001c120, 0x11)
	/Users/mikeperham/src/github.com/contribsys/faktory/storage/redis.go:159 +0x10d
created by github.com/contribsys/faktory/storage.bootRedis
	/Users/mikeperham/src/github.com/contribsys/faktory/storage/redis.go:155 +0xfc5
```
Are you using an old version? - 1.5.1

**Comment by mperham** [comment]
Please try the latest version.

**Comment by navaneeth** [comment]
Looks like Faktory process was running out of memory. Raised the memory limit and it seems to fix it. I see the memory usage growing consistently. Is there a leak happening? 

![image](https://user-images.githubusercontent.com/317288/182773316-784cec07-d45f-4952-8fc1-c245e55ce1a0.png)

**Comment by mperham** [comment]
It does us no good to talk of a memory leak in an old version. I need to know if the memory leak is in the latest version, 1.6.1.
