### ISSUE TITLE
Faktory Enterprise Docker "latest" not tagged

### ISSUE THREAD

**Issue by imack** [contribsys/faktory#412]
- Which Faktory package and version?
`latest`
- Which Faktory worker package and version?
n/a
- Please include any relevant worker configuration
n/a
- Please include any relevant error messages or stacktraces

Pulling the docker faktory enterprise; "latest" appears not to be tagged:

```
ian@Ians-Mac faktory % docker pull docker.contribsys.com/contribsys/faktory-ent

Using default tag: latest

Error response from daemon: manifest for docker.contribsys.com/contribsys/faktory-ent:latest not found: manifest unknown: manifest unknown
```

Specifying `1.6.1` works fine, so I'm assuming it's just that latest isn't tagged

**Comment by mperham** [comment]
Ah, this was fixed on main but I haven't released a new version yet so it hasn't yet created a latest tag.
