### ISSUE TITLE
Question: what type of persistence is redis configured to use?

### ISSUE THREAD

**Issue by rmzg** [contribsys/faktory#413]
Apologies for using this for questions but I couldn't find the answer anywhere in the documentation.

https://redis.io/docs/manual/persistence/ show several different ways to configure redis persistence, which one does faktory use and is it configurable?

**Comment by mperham** [comment]
You can see the Redis configuration on Faktory’s /debug in the Web UI. It should tell you what it is using, I believe it should be the default of RDB.
