### ISSUE TITLE
Pro vs Enterprise versions?

### ISSUE THREAD

**Issue by rmzg** [contribsys/faktory#414]
Hey, a couple of the wiki pages mention a pro version *and* an enterprise version, but the features and purchase pages only mention enterprise. Is pro still a thing?

**Comment by mperham** [comment]
Pro was retired last year. Enterprise is the only commercial version.

**Comment by mperham** [comment]
Let me know where the Pro references are and I’ll fix those.

**Comment by rmzg** [comment]
Thanks.

**Comment by rmzg** [comment]
First one is here: https://github.com/contribsys/faktory/wiki/Development
But the main one is https://github.com/contribsys/faktory/wiki/Storage

**Comment by rmzg** [comment]
Also, sorry if this isn't the right place, but I was able to install faktory and test the debug options and it appears redis aof (https://redis.io/docs/manual/persistence/) is disabled, is this an enterprise feature or can we get this enabled/optional for the oss version? The documentation makes it sound like you should generally use aof+rdb

**Comment by mperham** [comment]
Faktory has used the same persistence mechanism for the last five years and
nobody has complained. I have no plans to touch it.
