### ISSUE TITLE
Duplicate JIDs don't get cleared from the busy section

### ISSUE THREAD

**Issue by GodPingu** [contribsys/faktory#416]
- Which Faktory package and version? Community - 1.6.1
- Which Faktory worker package and version? faktory-worker (node) and faktory (golang)
- Please include any relevant worker configuration
- Please include any relevant error messages or stacktraces

Not many error messages or stacktraces to accompany this. Running community edition so we know unique jobs aren't supported, however it seems as if duplicate JIDs will get stuck in "busy" and only one will be removed from the busy queue when a task is complete, therefore slowly filling up the busy queue

**Comment by mperham** [comment]
Duplicate JIDs are illegal. You'll get undefined behavior. **Every job must have a unique JID**
