### ISSUE TITLE
Can't filter/search retrying jobs

### ISSUE THREAD

**Issue by davidbyttow** [contribsys/faktory#418]
- Which Faktory package and version? faktory-ent 1.6.1

When there are many retry jobs, it's impossible to selectively delete jobs of a certain type (e.g., by searching/filtering), and the pagination UI does not make it easy either. This puts us in a very difficult position when there are thousands of jobs failing that should be killed among jobs that should not be killed. 

Sidekiq Enterprise allows filtering, which makes it easier. Also the plugin model enables one to do more. 

How can this use case be handled with Faktory?

**Comment by mperham** [comment]
Have you considered the mutate API? https://github.com/contribsys/faktory/wiki/Mutate-API

**Comment by davidbyttow** [comment]
Ah, that's a reasonable idea. I think we can manage it this way. Feel free to close if you don't think it's worth adding to the UI any time soon. Thanks @mperham

**Comment by mperham** [comment]
It would be tricky to add the Mutate functionality to the UI. I’ve preferred to keep it as a “power tool” available for more advanced users. I wish there were a better way to publicize its existence though.
