### ISSUE TITLE
Unit of statsd time metrics

### ISSUE THREAD

**Issue by pbrisbin** [contribsys/faktory#419]
In https://github.com/contribsys/faktory/wiki/Ent-Metrics#job-execution, it just says `jobs.perform` Gauge (time).

I'm having trouble correlating values I'm seeing with other sources, so I just want to know for sure: is this metric sent in seconds or milliseconds?

Thanks in advance.

**Comment by mperham** [comment]
It calls `client.Timing()` under the covers, which is documented as milliseconds.

https://pkg.go.dev/github.com/DataDog/datadog-go/v5/statsd?utm_source=godoc#Client.Timing
