### ISSUE TITLE
Add NOOP command 

### ISSUE THREAD

**Issue by cdrx** [contribsys/faktory#42]
If a worker has a concurrency of 10, then it may have 10 (or 11) connections open.

If the BEAT is once per 15s per worker (not per connection) is it worth adding a ping / pong command that a thread tied up with a long running job can send to the server to keep the connection alive?

The worker could send a periodic BEAT but that updates the db (I think) which incurs some cost.

I’m happy to submit a PR

**Comment by mperham** [comment]
Faktory Worker Ruby reserves two extra connections for things like BEAT and other housekeeping.  If you have 10 concurrency, it’ll create up to 12 connections.

**Comment by cdrx** [comment]
To add a bit of context to this: I have one use case that has a high concurrency of very long running tasks (12hrs+) 

I was getting connection timeouts on the connection between faktory <> worker goroutine because nothing was being sent for 1+ hours (only the main connection `BEAT`'s)

I've worked around it by sending `PING` and waiting for `ERR` ;) once per min on idle connections, but it would be nice to have a faktory approved way to keep an idle connection from timing out. 

If it fits within your vision for the protocol I'll workup a PR, otherwise we can close this and I'll carry on generating an ERR :)

**Comment by mperham** [comment]
Looks like we just need to add this:

https://golang.org/pkg/net/#TCPConn.SetKeepAlive

**Comment by cdrx** [comment]
Thanks @mperham

**Comment by majedev** [comment]
Sorry for digging this old issue, but I faced the same problem when using TLS. Looks like the current client implementation does not set KeepAlive for TLS connections: https://github.com/contribsys/faktory/blob/master/client/client.go#L156-L170

**Comment by mperham** [comment]
@majedev PRs welcome.
