### ISSUE TITLE
Issues / Feature request

### ISSUE THREAD

**Issue by Rudis1261** [contribsys/faktory#422]
For our use-case, we need to know what the dead queue looks like, and be alerted when it grows too large. Looking at the code, this is only really kept internal to the application and web UI.

Any chance you would be able to add a method to the manager code to provide a list/count of the jobs currently in a dead state?

Or should we be using a different approach altogether?

**Comment by mperham** [comment]
I believe it's in the INFO json?

**Comment by Rudis1261** [comment]
Awesome thank you 😬
