### ISSUE TITLE
Faktory can't use the IPV4 network mode

### ISSUE THREAD

**Issue by rainysia** [contribsys/faktory#425]
- Which Faktory package and version?
-- v1.6.2

- OS
-- Amazon EC2 instance with Amazon Linux 2 (Centos)

- Package
-- faktory-1.6.2-1.x86_64.rpm

- Faktory Config
-- Default(/usr/bin/faktory -e production -b 0.0.0.0:7419 -w 0.0.0.0:7420)

-Issue
TLTR.: Faktory can't use the IPV4 network mode, it always works under the IPV6.

Detail:
When we installed it on Mac OSX, Linux Debian, and Linux Ubuntu server, it worked without any problems.
When we downloaded the package and used `rpm -Uvh` to install it,  seems It was working with the Nginx proxy to display the 7420 Web UI, 
but when we tried to connect it with the domain with TCP directly, we found it was always working under ipv6 mode, no matter if we disabled the OS IPV6 network or not (including reboot). The EC2 has already been configured the `IpAddressType` to `ipv4` like this issue([#354 ](https://github.com/contribsys/faktory/issues/354)) mentioned.

![image](https://user-images.githubusercontent.com/1259324/212583181-e6f902bb-8225-4b1c-a519-d1236735ff06.png)

I would appreciate any ideas. 

Thank you

**Comment by mperham** [comment]
This sounds purely like an environmental issue with your instance configuration. I don't know how to fix it.
