### ISSUE TITLE
Options for `TARGETPLATFORM` in dockerfile

### ISSUE THREAD

**Issue by Deekor** [contribsys/faktory#426]
Hey! I'm trying to build faktory from the dockerfile and am not sure what I should be passing into the build arguments for `TARGETPLATFORM`.

Is this documented anywhere?

**Comment by mperham** [comment]
Faktory is already available as a prebuilt image. The Makefile shows how it is used.

**Comment by Deekor** [comment]
Yes, there seems to be no easy way to get the prebuilt image into GKE so I was hoping to fork and run the docker build in google cloud build.

**Comment by Deekor** [comment]
I figured it out.

For future searcher's sake:

You can use gcrane to copy the dockerhub image into gcr.io and run the container from there.
