### ISSUE TITLE
Unable to run example code files

### ISSUE THREAD

**Issue by yashgugale** [contribsys/faktory#432]
- Which Faktory package and version?
--> 
1.0.0 installed using `pip install faktory`

- Please include any relevant worker configuration
--> 
Example code from: https://www.mikeperham.com/2019/01/08/using-faktory-with-python/

- Please include any relevant error messages or stacktraces
-->
`RuntimeError: An attempt has been made to start a new process before the current process has finished its bootstrapping phase. This probably means that you are not using fork to start your child processes and you have forgotten to use the proper idiom in the main module: if __name__ == '__main__': freeze_support() ... The "freeze_support()" line can be omitted if the program is not going to be frozen to produce an executable.`

- Are you using an old version? Have you checked the changelogs to see if your issue has been fixed in a later version?
--> No information related to the error in the newer versions

**Comment by mperham** [comment]
I don't support python myself. You'll need to ask in [faktory_worker_python](https://github.com/cdrx/faktory_worker_python/issues).
