### ISSUE TITLE
Factory can not be run as a second user without a computer restart

### ISSUE THREAD

**Issue by jonathan-wondereur** [contribsys/faktory#435]
When I try to run faktory as a user without sudo it crashes. How can I enable faktory to run as a user without sudo?

- Which Faktory package and version?
  - Faktory Enterprise 1.7.0
- Please include any relevant error messages or stacktraces
```
Faktory Enterprise 1.7.0 linux/amd64
© 2023 Contributed Systems LLC.
I 2023-05-26T17:11:23.928Z Initializing redis storage at /home/faktory/.faktory/db, socket /home/faktory/.faktory/db/redis.sock
W 2023-05-26T17:11:34.971Z Redis at /home/faktory/.faktory/db crashed: exit status 1
panic: exit status 1

goroutine 8 [running]:
github.com/contribsys/faktory/storage.bootRedis.func2()
        /Users/mperham/src/github.com/contribsys/faktory/storage/redis.go:166 +0xd3
created by github.com/contribsys/faktory/storage.bootRedis
        /Users/mperham/src/github.com/contribsys/faktory/storage/redis.go:162 +0xa2c
```

Are you using an old version? No
Have you checked the changelogs to see if your issue has been fixed in a later version? N/A

https://github.com/contribsys/faktory/blob/master/Changes.md
https://github.com/contribsys/faktory/blob/master/Pro-Changes.md
https://github.com/contribsys/faktory/blob/master/Ent-Changes.md

**Comment by jonathan-wondereur** [comment]
Okay, sorry, this is actually an issue with starting the process with one user, shutting it down and trying to start it with another user.

In this case the second user can not fully start faktory until the computer has a restart.

**Comment by mperham** [comment]
Looks like Redis maybe doesn’t have permissions to write to that DB directory?

**Comment by jonathan-wondereur** [comment]
Sorry, see my comment, the issue is actually something else, not that big of an issue really, just something to know ...
