### ISSUE TITLE
Debug failed jobs

### ISSUE THREAD

**Issue by JoaoPedroAssis** [contribsys/faktory#443]
Hello @mperham 

I am using faktory in ruby to send jobs to python workers, and the whole architecture is k8s based. How can I debug failed jobs?

The UI does not allow to do this, and I havent found the logs on the faktory-server container

Thanks in advance!

**Comment by mperham** [comment]
The Web UI should show the backtrace for each retry. The worker process stdout/log should also show the backtrace. Faktory server logs would not have any data.

**Comment by JoaoPedroAssis** [comment]
Thanks!
