### ISSUE TITLE
Not picking up CRON jobs

### ISSUE THREAD

**Issue by jonathan-wondereur** [contribsys/faktory#448]
- Which Faktory package and version?
- Faktory Enterprise 1.8.0
- Which Faktory worker package and version?
- github.com/contribsys/faktory_worker_go v1.6.1

Are you using an old version?
No

I can not get Faktory to pick up my CRON jobs no matter what I do as defined in:
`/etc/faktory/conf.d`

```
[[cron]]
  schedule = "0 13 * * *"
  [cron.job]
    type = "PriceRefresh"
    queue = "price-refresh"
```

**Comment by mperham** [comment]
And that content is in a file called `cron.toml` within the `conf.d` directory?

**Comment by jonathan-wondereur** [comment]
Okay, that was the issue; I thought the file was `conf.d`; I read it too fast. Thanks for clarifying the documentation.
