### ISSUE TITLE
Improve error validation on Redis persistence

### ISSUE THREAD

**Issue by pupocw** [contribsys/faktory#451]
- Which Faktory package and version? v1.7.0
- Which Faktory worker package and version? v1.6.0

Is there any chance of not being able to save a task in Redis due to lack of error validation [here](https://github.com/contribsys/faktory/blob/57707bc4b0d1fe703d2781f3fa45ff9dc21132e9/storage/queue_redis.go#L104)?

I did some tests simulating an error in Redis and the client was not informed that the task was not saved. By changing the implementation to return the error, the client is notified about the problem and can take some action to avoid losing the task.

Does it make sense to change to something like this?

```golang
func (q *redisQueue) Push(ctx context.Context, payload []byte) error {
	return q.store.rclient.LPush(ctx, q.name, payload).Err()
}
```

We are using the enterprise version and I don't know if we have the same behavior in it.

Thank you!

**Comment by pupocw** [comment]
Yes, that's exactly my concern, customers using external redis.

**Comment by mperham** [comment]
Good question. The issue is that the Redis command API doesn't return an error directly so the `errcheck` linter doesn't detect the lack of error handling. I'll audit and fix any missing error handling.
