### ISSUE TITLE
if faktory work crashes job sits in `busy` until timeout and then never requeues

### ISSUE THREAD

**Issue by Deekor** [contribsys/faktory#453]
- Which Faktory package and version? `1.6.2`
- Which Faktory worker package and version? `ruby`

I've noticed this behavior: if the faktory worker process crashes (out of memory for example) any jobs that worker was processing sits in `busy` until reservation timeout and then never enters the retry queue. Is this intended behavior? Im worried about jobs being lost if a crash happens, is there a config I'm missing?

**Comment by mperham** [comment]
I believe it doesn't go into retry, it should be directly re-enqueued.

**Comment by Deekor** [comment]
Interesting. I had a long-running job today that definitely didn't

**Comment by mperham** [comment]
I'll look into it next week. If you can give me a simple reproduction, that would help.

**Comment by mperham** [comment]
I was able to reproduce a simple crashing scenario. The jobs moved from Busy to Retries and then to Enqueued as expected.

**Comment by Deekor** [comment]
You're right. Turns out the job had a short circuit in it (on retries) that I didnt notice. It finishes so fast that i didnt even see it in busy or queue.

**Comment by Deekor** [comment]
Ok, in a similar vein to this. The worker that was running my `CampaignStartWorker` job crashed. The job retry short circuited. This is all intended behavior as discussed above.

However, the job still sits in busy state running on a ghost process, the job had a custom reservation and unique_for which is blocking me from re-queueing the same job.. even though the job isn't actually in queue or running on a real process.
```
  faktory_options reserve_for: 10800
  faktory_options custom: { unique_for: 3.hours.to_i }
```
![Screenshot 2024-02-02 at 10 27 48 AM](https://github.com/contribsys/faktory/assets/1904267/f9e405d5-2ddc-4867-ba4c-bed721c21b27)
![Screenshot 2024-02-02 at 10 27 53 AM](https://github.com/contribsys/faktory/assets/1904267/eaaf3bf5-1ba3-437a-853f-6c985ff49e55)
![Screenshot 2024-02-02 at 10 28 00 AM](https://github.com/contribsys/faktory/assets/1904267/068be57d-fb3e-403b-bd87-7461cd4b3043)

**Comment by mperham** [comment]
If the entire worker process crashes, you'll see the job sit until the reservation timeout passes. This is because Faktory can't tell if the job is still executing (and the network is bad) or if the process died and its pending jobs can be retried soon.
