### ISSUE TITLE
Workers not using all available threads?

### ISSUE THREAD

**Issue by Deekor** [contribsys/faktory#454]
I have each worker set at a concurrency of `15`, but none of them are running at full capacity even with a large number of jobs queued up. Is this a known behavior, and what causes it?
<img width="1356" alt="image" src="https://github.com/contribsys/faktory/assets/1904267/7b40e9da-191a-4ae2-ba1d-c6963d207ca6">

Faktory Enterprise 1.8.0

**Comment by mperham** [comment]
I'm not sure, it's impossible for me to tell why it might be running slow.

**Comment by mperham** [comment]
Use the TTIN signal to dump backtraces when the process appears to be stuck.
