### ISSUE TITLE
Question: 14 day runs

### ISSUE THREAD

**Issue by 76creates** [contribsys/faktory#457]
Hey all, I have a system where we work on jobs that are up to 14 days long, workers are interruptable, meaning we can kill it at any moment and its jobs should be picked up as soon as possible, ideally with 1s timeout. I see two issues with using the factory:
1. Limited retry count, but max int 32 should be sufficient.
2. Exponential (non configurable?) backoff.

Is there a ready made solution for this? If we were to implement a custom backoff, could you see any potential pitfalls with low retry timer?

**Comment by mperham** [comment]
That's not a supported use case. You might be able to get things working but I can't verify or support it.
