### ISSUE TITLE
Custom data stripped on batch callbacks for trace metadata propagation

### ISSUE THREAD

**Issue by TurtleSRE** [contribsys/faktory#462]
Using the latest Faktory enterprise version (1.8.0), batch [callback jobs](https://github.com/contribsys/faktory/wiki/Ent-Batches#callbacks) have their [custom data](https://github.com/contribsys/faktory/wiki/The-Job-Payload#custom-data) stripped (i.e. inspecting the batch via UI shows the custom data is no longer there). When those custom jobs are then enqueued at the end of a batch, they only have `_bid` and `_cb` attributes set in custom data. This is an issue for using custom data to propagate trace metadata (populated by middleware).

Is this intended behaviour or a bug (documentation doesn't make it clear either way)? If it's intended, how should we propagate metadata for distributed tracing?

**Comment by mperham** [comment]
Can you give me a piece of code which reproduces the problem and shows how you are constructing the batch?
