### ISSUE TITLE
[Feature Request] Include Redis RTT in statsd metrics that are emitted

### ISSUE THREAD

**Issue by yvjessestephens** [contribsys/faktory#475]
- Which Faktory package and version?
Faktory 1.7.0, Enterprise

Some Redis metrics are already available ([see Ent-Metrics](https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcontribsys%2Ffaktory%2Fwiki%2FEnt-Metrics%23global&data=05%7C02%7Cjesse.stephens%40youversion.com%7C52c6de2b4a1c4f0a216408dc6871b068%7C8c9a6ca9b4314964afb4b8e1a2ba636f%7C0%7C0%7C638500084721062224%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=khKVwcaXEYKkonWaS25rYUP12qzdIl1LVb19Q5H7SMM%3D&reserved=0)):
- Redis network connections (ops.redis.connections)
- Redis RAM usage, in bytes (ops.redis.memory)

I'm interested in being able to capture the RTT so that we can alert if that metric exceeds its baseline by very much and investigate what might have changed to cause that (e.g. the SaaS Redis instance got moved to a different zone), and to track that metric over time for historical performance.

**Comment by yvjessestephens** [comment]
@mperham , now that you have marked this as completerd, in what version could I expect this feature to be available?

**Comment by mperham** [comment]
I don't have an ETA on 1.9.0, I was trying to land #474 first but it's blocked until I have a way to reproduce and verify the PR improves things. I might need to adjust my release plan.

**Comment by mperham** [comment]
this is now available in 1.9
