### ISSUE TITLE
[Feat Request] Improve the reliability of Faktory server when overloaded with connections

### ISSUE THREAD

**Issue by yvjessestephens** [contribsys/faktory#476]
- Which Faktory package and version? Enterprise v1.7.0
- Are you using an old version? Yes
- Have you checked the changelogs to see if your issue has been fixed in a later version? Yes, it is not

Using the Enterprise version, the number of connections is capped at X number. The server allows for the number of clients connected to exceed X. If there are more than X clients connected, the behavior of the Faktory server becomes a bit unpredictable. At the very least, it stops emitting statsd metrics. It appears that the excessive number of clients connected overruns the ability of Faktory internals to connect to Redis.

Can the behavior of Faktory be improved such that when all the connections are in use that it is a little less apocalyptic?

**Comment by mperham** [comment]
this is now available in 1.9
