### ISSUE TITLE
Retry documentation

### ISSUE THREAD

**Issue by j-manu** [contribsys/faktory#56]
1. Does retry apply to only failed jobs or jobs that failed to ACK?
2. If it applies only to failed jobs, then can we set a limit for how many times a job can be enqueued again?

**Comment by mperham** [comment]
Job attributes are documented here:

https://github.com/contribsys/faktory/wiki/The-Job-Payload

but we could definitely improve the docs around Faktory's job retry/error process.

1. retry only applies to explicitly FAILed jobs.
2. see the 'retry' option in the job payload.

**Comment by mperham** [comment]
Started this page: https://github.com/contribsys/faktory/wiki/Job-Errors

**Comment by j-manu** [comment]
So there is currently no way to limit retrying of Non-ACKed jobs right? If a job doesn't complete within the reserve_for timeline faktory will enqueue it again and again? This can lead to a scenario where if there is a job which doesn't complete due some bug, all worker processes will eventually fetch that and get stuck processing that job.

**Comment by mperham** [comment]
If you are re-enqueuing quickly, every N seconds, as you want to do, yes, a poison pill can take down all your workers quickly.  If you are reserving for 30 minutes by default, it's generally not a problem.  Sidekiq does not limit either and no one's ever reported this as a problem.

**Comment by j-manu** [comment]
Sidekiq retries only failed jobs. So a single job which never finishes doesn't take down all workers whereas it is a definite possibility in faktory. Does it matter whether it happens slowly with default limit of 30minutes or faster with a lower reserve_for?

Ideally I would like to have a new config (re-enqueue) to control how many times a job should be re-enqueued and a configurable lower reserve_for

**Comment by mperham** [comment]
Sidekiq Pro has the same side effect.  If it happens slowly, it doesn’t have a big effect on throughput. Workers dying every 10 seconds would mean not many jobs are actually finishing.
