### ISSUE TITLE
Lower minimum for reserve_for

### ISSUE THREAD

**Issue by j-manu** [contribsys/faktory#57]
Why is there a hard limit of 60 seconds for reserve_for? We have a lot of small jobs (2-5 seconds each) which need to have a lower reserve_for to tolerate workers going down. Is there any chance of lowering the limit later?

**Comment by mperham** [comment]
Because even a simple DNS lookup can sometimes take many seconds.  The lower the limit, the more likely you are to get duplicate job execution under slow/flaky network conditions.

If your worker processes are crashing that often, you need to spend your time debugging and fixing that problem.

**Comment by j-manu** [comment]
Workers are not going down often but the machine that workers are on may go down. For many cloud providers it is profitable to run machines which may be shutdown anytime (spot instances on AWS, preemptible on Google Cloud). There is a way to safely shutdown but on google cloud at least the shutdown scripts are "best effort" and not guaranteed to run. So the machine might just get shutdown in the middle of processing. The jobs take 2-5 seconds and it has to complete within 30 seconds so scheduling it after 60 seconds doesn't make sense for us. 

I'm not asking for a lower default time limit. Why not give the user to change the limit?
