### ISSUE TITLE
Security and authentication

### ISSUE THREAD

**Issue by mperham** [contribsys/faktory#6]
Security is always tricky, with compromise and tension between usability and safety.  My basic policy: development should be easy, production should be safe.  More thoughts:

## Network safety and Encryption

Development mode should be quickly usable, without needing to read docs or configure options in order to get working.  If someone is running Faktory locally, she should be able to install and start it immediately.  The default would be to listen on localhost only, with no TLS or passwords required in this mode.

In production, we want to listen on a non-localhost interface.  Once ports exposed to the outside world, we need to get more paranoid and require TLS and authentication.

We can't provide TLS without the user providing a cert for the hostname used to access the API and Web UI.  The user will need to provide a TLS cert and CA chain, which I propose reside at a conventional location:

{\~/.faktory,/etc/faktory}/public.crt
{\~/.faktory,/etc/faktory}/private.key
{\~/.faktory,/etc/faktory}/ca-chain.crt

Those filenames can be actual bytes or soft links to the files elsewhere on the disk.

In summary:

* If listening on localhost, Faktory will use insecure TCP.
* If those files are found, Faktory will use TLS.
* If not listening on localhost and no certs, Faktory will exit immediately with an error.

### Alternatives

The user can run Faktory in production using e.g. stunnel, proxy to expose insecure localhost ports instead of TLS.  Since Faktory is listening on localhost, it doesn't care or require any security.  It's up to the user to expose those ports securely.

## Authentication

TLS doesn't solve our problem, we still need to limit access.  I propose a simple password scheme for all connecting clients when sending the AHOY payload.  Clients should send two attributes, `pwdhash` and `salt` where `pwdhash` is `sha256(password+salt)`.  Salt should be, at minimum, a 12-char random string and generated unique for each AHOY.

AHOY {"pwdhash":"d40b8917d7aff72a40a677c55992d2edc1b41331ec3b24641f2affa67b8dba09","salt":"aos,dfis33dkvn"}

This is the SHA256 for the password "helloworld":

```
$ echo -n helloworldaos,dfis33dkvn | shasum -a 256
d40b8917d7aff72a40a677c55992d2edc1b41331ec3b24641f2affa67b8dba09 -
```

Without a valid pwdhash and salt in the AHOY, Faktory will disconnect the client immediately.

### Open questions

* How do we pass the password to Faktory in production?  A command line option will expose it in `ps` output, I believe current best practices suggest an ENV variable to be best.  Other ideas?

**Comment by Lusitaniae** [comment]
Another option is config file, like AWS ~/.aws/credentials or Mysql ~/.my.cnf.

Should be equivelent to ENV variables?

**Comment by philips** [comment]
Consider integrating with or punting to something like [Istio](https://istio.io/blog/istio-auth-for-microservices.html)? xref #19

**Comment by mperham** [comment]
@philips Would Istio lock our users into the Kubernetes stack?  Ideally Faktory can be set up manually also, to integrate into any system.

**Comment by jtdowney** [comment]
I would suggest implementing a standard authentication protocol like [SCRAM-SHA256](https://tools.ietf.org/html/rfc7677) instead of making your own. If you want to go full blown enterprise, you could support [SASL](https://en.wikipedia.org/wiki/Simple_Authentication_and_Security_Layer) and let it do the authentication part.

**Comment by philips** [comment]
@mperham Istio can be ran anywhere. It is a reverse proxy and control-plane for that reverse proxy. The focus just happens to be Kubernetes.

**Comment by mperham** [comment]
@jtdowney Thanks for the pointer! 👍

**Comment by mperham** [comment]
#30

**Comment by mperham** [comment]
TLS has been removed, random hash iterations added in protocol v2, CSRF protection in the works.
