### ISSUE TITLE
Option to force language of GUI to be english

### ISSUE THREAD

**Issue by ruudk** [contribsys/faktory#60]
Hi, First of all, very interesting project 👏 

I'm from The Netherlands and when I opened the web GUI it showed me everything in Dutch. 
I looked it up, and it seems that it uses the `Accept-Language` header to automagically select this.

I don't like my technical tools to be translated in Dutch. I prefer English for that. 

Would it be possible to make this optional?

**Comment by mperham** [comment]
There's no way to do that today; you can change your browser's language preferences or use a separate English-only browser.

**Comment by vosmith** [comment]
I'd like to give this a shot, I think it can be overridden with a cookie and a select box.

**Comment by mperham** [comment]
sounds good. put it on the debug page, so it doesn’t distract from the main UI?

**Comment by vosmith** [comment]
Closed by dd12bd8cda1b645cb4d3052dd6f09e8f69b2a451
