### ISSUE TITLE
Add CSRF protection

### ISSUE THREAD

**Issue by mperham** [contribsys/faktory#63]
The Web UI currently is missing CSRF protection because we don't have any notion of session to store the current token value.  The hooks are all there in the forms to inject an authenticity_token, we just need to implement it.

**Comment by vosmith** [comment]
Looks like this library could really help with this

https://github.com/justinas/nosurf
Doesn't look like it has any third party dependencies and wraps the http.Handler to protect POST, PUT, PATCH, and DELELTE routes.

**Comment by mperham** [comment]
That library looks great, even has modern Context support.  :+1:

**Comment by vosmith** [comment]
Awesome, I'll get started on a PR :+1:

**Comment by mperham** [comment]
@vosmith Rad, I look forward to it.
