### ISSUE TITLE
Reap connections that never heartbeat

### ISSUE THREAD

**Issue by jbielick** [contribsys/faktory#66]
I noticed that if a connection doesn't send a heartbeat, it doesn't get reaped in the 60s timeout. Would an acceptable solution to this be to write a heartbeat to the map the moment a connection is opened (clientWorkerFromHello)? Alternative? I'm willing to open a PR—wondering what the intended behavior is.

**Comment by mperham** [comment]
the fix should be on master, are you running the latest?

**Comment by jbielick** [comment]
I'm not. I'll reopen if it's still occurring. Thanks!
