### ISSUE TITLE
Load testing tool

### ISSUE THREAD

**Issue by mperham** [contribsys/faktory#80]
We have a very basic queue push/pop tool in test/load but it would be nice to have broader coverage of more commands, more connections, etc.  What makes sense to add?

**Comment by jonhoo** [comment]
I think we'd also want to provide some representative numbers so that new implementations have something to compare against.

To start off, results with `make drun` for the [Go load tester](https://github.com/contribsys/faktory/blob/master/test/load/main.go):
```console
contribsys/faktory $ ./load push 30000
Enqueued 30000 jobs in 2.829427 seconds, rate: 10602.854369 jobs/s
contribsys/faktory $ ./load pop 30000
Processed 30000 jobs in 7.956643 seconds, rate: 3770.434286 jobs/s
```
For the equivalent [Rust load tester](https://github.com/jonhoo/faktory-rs/tree/master/src/bin):
```console
faktory-rs $ cargo run --release --bin push -- 30000
Enqueued 30000 jobs in 2.48 seconds, rate: 12086.058280037405 jobs/s
faktory-rs $ cargo run --release --bin pop -- 30000
Processed 30000 jobs in 6.04 seconds, rate: 4969.648735069443 jobs/s
```

**Comment by mperham** [comment]
Here's what I'm getting when running against Faktory directly (note that Docker for Mac has severe performance issues) on my touchbar MBP:

```
$ ./loadtest push 30000
Enqueued 30000 jobs in 2.765033 seconds, rate: 10849.778610 jobs/s
$ ./loadtest pop 30000
Processed 30000 jobs in 6.700829 seconds, rate: 4477.058055 jobs/s

$ cargo run --release --bin push -- 30000
Enqueued 30000 jobs in 2.22 seconds, rate: 13520.637129161603 jobs/s
$ cargo run --release --bin pop -- 30000
Processed 30000 jobs in 5.35 seconds, rate: 5609.325109444202 jobs/s
```

**Comment by andrewstucki** [comment]
I definitely think that having some amount of parallelism would be good. Right now everything just runs serially.

Also, it might be good to have tighter bounds on the timings so we remove the additional time used in constructing jobs.

**Comment by jonhoo** [comment]
The load test should also have flags for things like the number of workers to use in `pop`, the duration of the jobs, etc.

**Comment by mperham** [comment]
I didn't notice the load tester was single threaded.  Yeah, test/go_system_test.go spawns three threads to get some parallelism (and stress RocksDB's concurrency support).

**Comment by mperham** [comment]
I reworked the load tester a bit to make it multi-threaded:

```
$ ./loadtest 30000 2
Running loadtest with 30000 jobs and 2 threads
Processed 30000 pushes and 30000 pops in 7.817055 seconds, rate: 3837.762492 jobs/s
$ ./loadtest 30000 20
Running loadtest with 30000 jobs and 20 threads
Processed 30009 pushes and 30009 pops in 3.737247 seconds, rate: 8027.298670 jobs/s
$ ./loadtest 30000 200
Running loadtest with 30000 jobs and 200 threads
Processed 30099 pushes and 30099 pops in 3.953855 seconds, rate: 7587.531626 jobs/s
```

**Comment by jonhoo** [comment]
Could you push the updated code somewhere so I can make the equivalent changes in the Rust one? Is the number of threads the number of concurrent producers, the number of threads in a single consumer, or the number of consumers (and if the latter, how many threads/goroutines per consumer)?

**Comment by mperham** [comment]
^^^^

**Comment by jonhoo** [comment]
Pushed what I believe to be an equivalent test in https://github.com/jonhoo/faktory-rs/commit/1849e6533d9b63720078ef77d963b04ee47fc52b.
Results:
```console
$ target/release/loadtest 30000 2
Running loadtest with 30000 jobs and 2 threads
Processed 30000 pushes and 30000 pops in 5.78 seconds, rate: 5186.246296171545 jobs/s
$ target/release/loadtest 30000 20
Running loadtest with 30000 jobs and 20 threads
Processed 30020 pushes and 30000 pops in 4.29 seconds, rate: 6992.372752199894 jobs/s
$ target/release/loadtest 30000 200
Running loadtest with 30000 jobs and 200 threads
Processed 30200 pushes and 30000 pops in 4.59 seconds, rate: 6532.493004204627 jobs/s
```
Not entirely clear where the additional slowdown compared to the Go implementation with more threads comes from -- will investigate that later.

**Comment by mperham** [comment]
The randomized aspects can certainly cause some drift but unlikely to be responsible for 10-20% slower.

**Comment by jonhoo** [comment]
Actually, I think this is just my laptop having fewer cores than yours:
```console
$ ./loadtest 30000 2
Running loadtest with 30000 jobs and 2 threads
Processed 30000 pushes and 30000 pops in 7.838850 seconds, rate: 3827.091775 jobs/s
$ ./loadtest 30000 20
Running loadtest with 30000 jobs and 20 threads
Processed 30009 pushes and 30009 pops in 4.450884 seconds, rate: 6740.233433 jobs/s
$ ./loadtest 30000 200
Running loadtest with 30000 jobs and 200 threads
Processed 30099 pushes and 30099 pops in 4.455176 seconds, rate: 6733.740977 jobs/s
```

**Comment by jonhoo** [comment]
Averaging across ~7 runs:
```console
$ rust
2: 5201, 20: 6752, 200: 6358
$ go
2: 3809, 20: 6726, 200: 6483
```

This suggests to me that at some point around 6.7k/s you saturate the server (which I assume then is single threaded?).

The Go tool sometimes printed a bunch of warnings of the form
```
dial tcp [::1]:7419: getsockopt: connection refused
```
but I discarded those datapoints.

**Comment by mperham** [comment]
Faktory uses one goroutine per network connection so it's extremely concurrent.  The Go runtime maps those onto one OS thread per core (I think?) which should minimize real mutex contention.

I tried 500 threads and Faktory crashed so there's some socket scalability issues that need to be investigated in the mid-term.

**Comment by jonhoo** [comment]
Yeah, Go should do that. It is strange why the performance drops beyond 20 though, since my four CPU cores do not seem fully saturated? I wonder what's going on...

**Comment by andrewstucki** [comment]
So, just in case it helps, I'll attach some pprof traces that I got from bumping up the max queue size to 10mil jobs and running pprof on the web server. I'm not super sure how to interpret them, but it looks like (from my limited understanding of pprof traces), that 50% of execution time is spent somewhere in cgo land (presumably either doing go to c translation or the actual rocks operations) and another 25% of execution time is spent reading/writing to the network. Here are the levels I ran at (laptop has an SSD, 16 GB of RAM, and 4 cores at 2.8 GHz):

```
➜  faktory git:(master) ✗ go run test/load/main.go 1000000 10
Running loadtest with 1000000 jobs and 10 threads
Processed 1000004 pushes and 1000004 pops in 89.833148 seconds, rate: 11131.748379 jobs/s
```
And with 100 threads:

```
➜  faktory git:(master) ✗ go run test/load/main.go 1000000 100
Running loadtest with 1000000 jobs and 100 threads
Processed 1000049 pushes and 1000049 pops in 73.296338 seconds, rate: 13643.246404 jobs/s
```
Traces attached: [pprof.tar.gz](https://github.com/contribsys/faktory/files/1460293/pprof.tar.gz)

Also, I found that if I got rid of the timeout on the go client `Dial` method [here](https://github.com/contribsys/faktory/blob/master/client.go#L132) that I could bump up the concurrency even higher. I haven't taken an in-depth look at the refactored load test, but I kind of doubt that something like lock-contention or parallelism is the issue, I have the feeling what's happening is that there are some clients `FETCH`ing jobs off of queues that don't have enough write volume, so they're timing out while doing a blocking Pop.

That said, It looks like I'm still saturating my rate at even up to levels of 200 concurrent connections, so I have the feeling that this acts as a pretty good baseline load test for how the server itself performs.

**Comment by andrewstucki** [comment]
Here's at 200 concurrent connections btw:

```
➜  faktory git:(master) ✗ go run test/load/main.go 1000000 200
Running loadtest with 1000000 jobs and 200 threads
Processed 1000099 pushes and 1000099 pops in 78.078717 seconds, rate: 12807.587468 jobs/s
```
