### ISSUE TITLE
Support dequeueing scheduled jobs

### ISSUE THREAD

**Issue by jonhoo** [contribsys/faktory#82]
If an application schedules a job using `at`, and then discovers that the job is no longer necessary (likely due to a user action), it would be convenient to have a way of cancelling that job, rather than expending resources on executing it. There are ways to do this out-of-band by having workers consult a "cancelled jobs" table somewhere, but this seems like unfortunate complexity to add to the application when Faktory already has the necessary control structures.

Note that this feature would *not* let you abort or cancel jobs that are currently running, nor does it give any guarantees that a job will not run. Rather this is a hint to the system that a given job need not subsequently be given out to workers. We *could* scope this only to jobs with an `at` set, but that seems like an unnecessary restriction.

The proposed API call would be something like:

```
DEQUEUE {"queue": "<queue>", "jid": "<jid>"}
```

which returns one of

```
+OK
+gone
```

`queue` defaults to `default` if not given. As with #81, we want to explicitly name the queue to avoid having to search over all queues. See also Gitter discussion starting at https://gitter.im/contribsys/faktory?at=5a02d85286d308b755c10755

**Comment by vosmith** [comment]
I like this feature, I could definitely see it's benefit. May I suggest the command be called `cancel`? I feel like `dequeue` implies processing the job.

**Comment by jonhoo** [comment]
I think `cancel` implies a stronger kind of operation: if a job is *currently* running at a worker, I would expect `cancel` to kill the running job. I'm not sure I agree with `dequeue` implying processing, and it's also a nice dual to `enqueue`. How about `deschedule`?

**Comment by jweslley** [comment]
`dequeue ` is a better command name.

**Comment by andrewstucki** [comment]
So, a couple of things:

1) `jid` is a globally unique identifier, so the specification of a queue isn't necessary.
2) RE the name: I think that the flip-side of `schedule` should actually be `unschedule`

Also regarding the idea of doing a `cancel` on a running job: since this is a queue that just hands work off to a bunch of distributed clients, unless you added in a large amount of complexity for doing server-initiated communication to clients, there's not going to be a way to `cancel` a running job.

**Comment by jonhoo** [comment]
Re 1. I was going off of @mperham's comment here: https://gitter.im/contribsys/faktory?at=5a0344b27081b66876c7bb15
> that is possible: pending?(jid)
> but would be a pretty heavyweright operation, require a full scan of all queues and sets

Re 2: Is there currently a `schedule` command? I don't think so? The command is called `PUSH`. And we don't want to use `POP`, because that has the wrong semantic meaning. `UNPUSH` is sort of right, but just sounds wrong.

Re `cancel`, yes, I completely agree. That is why this issue does *not* propose allowing cancellation of jobs, but rather *just* removing a job that has been queued, but not yet processed. It is more of a hint that a given job need to be executed.

**Comment by andrewstucki** [comment]
I believe that the `pending?` remark was regarding doing a scan of jobs that are currently enqueued to be processed, not jobs that are `scheduled` for the future. Seems like a small difference, but it's not, basically there's `scheduled` storage where jobs sit until they get moved to the actual work queue once the scheduled time is reached. Removing the jobs from being scheduled should be substantially easier than removing jobs from the work queue itself.

I think that where the semantic mismatch is happening here is that jobs actually pushed into the work queue (who are scheduled to be processed immediately) aren't really "scheduled" jobs at all, they're jobs that are expected to be processed almost instantaneously.

"Scheduled" jobs, on the other-hand, just sit in a holding tank until they can be enqueued at the proper time.

I would totally support unscheduling a job that's `PUSH`d to be processed at a later time, but I think that you get into too many timing issues, implementation quirks, and potentially abstraction violations if you remove a job that is essentially considered "ready to be processed".

**Comment by mperham** [comment]
See the diagram under Job Lifecycle here for a similar design in Beanstalkd, need to consider all the states a job can be in. https://raw.githubusercontent.com/kr/beanstalkd/master/doc/protocol.txt

**Comment by vosmith** [comment]
For stopping a running job I would use `kill`, but I think most people are on board with dequeue as a command so I'll roll with it :+1:

**Comment by jonhoo** [comment]
I guess ultimately, this is an argument about the length of queues. If the "ready to process" queue is expected to have a non-trivial amount amount of jobs on it, then I think `dequeue` is a useful operation to have, because you can save the system work by removing elements from the queue. If the queue is expected to be mostly empty or close to empty, then I agree, `dequeue` is not useful, and `deschedule` is the only operation that should be supported.

**Comment by andrewstucki** [comment]
Thought that this might be useful (assuming it's accurate), but as far as I can tell, here's the basic state machine from beanstalkd modified to fit the faktory job lifecycle.

```
PUSH (at)  
------------> [SCHEDULED]
                ||   |                     
                ||   | (time passes)       
                ||   |                     
PUSH            ||   v         POP                   ACK
-----------------> [ENQUEUED] ---------> [WORKING] --------> *poof*
                ||   ^                      |
                ||   |                      |
                ||   |                      |
                ||   |                      |
                ||   | (time passes)        |
                ||   |                      |
                ||   |       FAIL           |
                 [RETRIES] <---------------'
                ||   |
                ||   |  kill (web ui only)
                ``    `---------------------> 
                 ``    kill (web ui only)     [DEAD]
                  ``========================> 
```

Some of the things are fairly simplified, like the `[ENQUEUED]` state storage is actually a multi-dimensional FIFO-based priority queue.

**Comment by jonhoo** [comment]
`POP` should be `FETCH` I assume?

**Comment by andrewstucki** [comment]
@jonhoo yep, thanks, I'll fix it

**Comment by cjbottaro** [comment]
Super interested in this. I feel like this combined with a way to inspect queues (including the retry queue) would solve the issue I just opened #134.

**Comment by mperham** [comment]
The newish `MUTATE` command allows you to remove a specific JID within a sorted set. This can be used to remove scheduled jobs quickly.
