### ISSUE TITLE
Clean up protocol documentation

### ISSUE THREAD

**Issue by jonhoo** [contribsys/faktory#89]
The best description of the protocol for talking to Faktory we currently have is https://github.com/contribsys/faktory/wiki/Worker-Lifecycle, with bits and pieces in https://github.com/contribsys/faktory/wiki/The-Job-Payload. For anything missing, implementors must consult the [Go client source](https://github.com/contribsys/faktory/blob/master/client.go). This is suboptimal.

Faktory should provide an in-tree (not Wiki), detailed description of the protocol, with complete examples of interactions (including the exact REDIS RESP formatted response). I recommend looking at the IMAP RFC for inspiration (see, for example, the docs for `SELECT` in [§6.3.1](https://tools.ietf.org/html/rfc3501#section-6.3.1)). Implementors should not need to look at the Go client source at all. This also means that we need to sort out some current disagreements between the Wiki docs and the Go source. For example, what exactly does `BEAT` return? The docs [say](https://github.com/contribsys/faktory/wiki/Worker-Lifecycle#heartbeat):

> The response can be OK or a JSON hash with further data for the worker:
> 
> ```
> {"state":"quiet"}
> ```

Whereas the Go client assumes it's always a string:

https://github.com/contribsys/faktory/blob/2e7a019addc3750d5198b7fce9dee819a70b2b68/client.go#L329
https://github.com/contribsys/faktory/blob/2e7a019addc3750d5198b7fce9dee819a70b2b68/client.go#L325
https://github.com/contribsys/faktory_worker_go/blob/05a5c14543ea9c2737e5ec4900f0336c5d2cc819/runner.go#L145-L152

Ideally, we should also supply a set of test cases with trace responses from the server, and expected messages from the client, but that can be another step down the line.

**Comment by mperham** [comment]
Yep, the docs can always be improved.  I can't afford to spend time documenting perfectly a work in progress but improvements are always welcome.

The BEAT response is a string; the Go client is returning the string rather than deserializing it because it can be OK or {...} and I can't return two different types.

**Comment by jonhoo** [comment]
Hmm.. But if `{"state":"quiet"}` is returned, it won't match the `if` here:
https://github.com/contribsys/faktory_worker_go/blob/05a5c14543ea9c2737e5ec4900f0336c5d2cc819/runner.go#L147
So presumably the Go client will never be quiet or terminate?

**Comment by mperham** [comment]
That's a beautiful bug found in the wild!
