### ISSUE TITLE
Windows builds?

### ISSUE THREAD

**Issue by andrewstucki** [contribsys/faktory#91]
@mperham:

Noticed that the idea of building on Windows was raised in Gitter. Thought that I'd take a stab at getting it building with CI on Windows. I'm not by any means even a fan of Windows systems, but figured that maybe it would help get more people contributing.

However, I'm not sure how much you want to actually support Windows--personally, with all the craziness of Windows systems and non-POSIX-compliant stuff... I wouldn't... but, it looks fairly possible given that the only real platform-specific dependency is pretty easy to install with a Microsoft supported [package manager](https://github.com/microsoft/vcpkg). Before I spend too much time on this though, I figured I'd get your thoughts.

On a side note, man, Windows builds of library dependencies are [_**SLOW**_](https://ci.appveyor.com/project/andrewstucki/faktory). It takes like 25 mins just to build all the required dependencies through appveyor. Thank goodness for caching.

**Comment by mperham** [comment]
Let's get some Faktory users, and then get some Faktory users expressing interest in Windows, and then we'll talk.  I'm really not interested in supporting a platform that no one is using.

Please speak up if Windows support is important to you.

**Comment by andrewstucki** [comment]
Frankly it's not to me, so I'm totally cool with shutting this down for now.

**Comment by jonhoo** [comment]
Should this be closed or left open?

**Comment by pdaher** [comment]
At least for the worker library (golang), Windows support is very important to me. Even if there is no much interest from the community in having the server daemon in Windows, my opinion is that at least the golang worker library should be able to run in Windows.

**Comment by jonhoo** [comment]
I agree with @pdaher; I think it is *much* more important that the workers are able to run on Windows. For what it's worth, I think the Rust one can, but haven't tried. I'll add an AppVeyor CI asap.

**Comment by mperham** [comment]
I'm all for it but I'll need one or two people to step up and help me support the platform (set up CI, fix build issues, advise on platform issues and conventions, etc).  Shouldn't be too hard, I just don't have access to Windows and haven't used it in a decade.

**Comment by jonhoo** [comment]
@mperham AppVeyor's config is quite similar to that of Travis. Not sure if it helps, but the commit adding Windows testing to the Rust worker is https://github.com/jonhoo/faktory-rs/commit/87ee2a17d721c864da14f6d54c4ff34dc8034d6a

**Comment by mperham** [comment]
contribsys/faktory_worker_go#4

**Comment by nadilas** [comment]
It looks like a really great solution, can the server be compiled for windows?

**Comment by nadilas** [comment]
@mperham can you guide me in the right direction?

**Comment by mperham** [comment]
@nadilas I can't.  I haven't used Windows in 10 years.

**Comment by ilovefreesw** [comment]
So your entire premise of not releasing it for Windows is based on "Becasue I don't like it ..." pretty stupid logic.

https://www.statista.com/statistics/1482210/os-distribution-among-developers-worldwide/#:~:text=In%202024%2C%20over%2059%20percent,personal%20and%20professional%20use%2C%20respectively.


https://survey.stackoverflow.co/2024/technology

**Comment by mperham** [comment]
@ilovefreesw Be careful, you're one hasty comment away from being Blocked.

> I'm all for it but I'll need one or two people to step up and help me support the platform (set up CI, fix build issues, advise on platform issues and conventions, etc). Shouldn't be too hard, I just don't have access to Windows and haven't used it in a decade.
