### ISSUE TITLE
[FEATURE] Prometheus metrics

### ISSUE THREAD

**Issue by lukasmalkmus** [contribsys/faktory#97]
I'm keeping this short: I'm pretty sure the project and its users can benefit from exporting prometheus metrics. Metrics are important in modern application deployments, especially if there are many moving parts.

I would suggest to export some basic metrics about the application itself, queues, jobs and the web server (latency, http status codes, etc.). They are also interesting for scaling Kubernetes deplyoments: See #19.

If this is desired, we can discuss it in detail and I would love to contribute a basic implementation.

**Comment by mperham** [comment]
The INFO command provides basic metrics already but you'd have to pull them.  I'm still in the process of deciding how to support various metrics standards like Prometheus and Statsd.

**Comment by lukasmalkmus** [comment]
Today I hacked together a very basic exporter: https://github.com/lukasmalkmus/faktory_exporter

**Comment by mperham** [comment]
Faktory Pro now has [Statsd support](https://github.com/contribsys/faktory/wiki/Pro-Metrics).  I will add first-class Prometheus support based on customer demand.

**Comment by jazzdragon** [comment]
@mperham Was there any work towards supporting exports to Prometheus? We would like to utilise those for alerting for our enterprise account.

**Comment by mperham** [comment]
Not yet, you're the first to request Prometheus support.

**Comment by MrDHat** [comment]
Adding my vote to support prometheus metrics!

**Comment by MRigal** [comment]
Thanks @lukasmalkmus for bringing this up and providing a first exporter. As I had problem to use your package from source as well as in a docker container, I've written a similar Python implementation: https://github.com/prospect-server/faktory-prometheus-exporter
