### ISSUE TITLE
Test coverage scan

### ISSUE THREAD

**Issue by mperham** [contribsys/faktory#98]
Run coverage reports for the {storage,server,webui} packages.  Find any non-trivial blocks of uncovered code.  Write a test for that block.  Rinse, repeat until no blocks remain.

**Comment by jweslley** [comment]
While writing some tests to faktory, I realized how hard it is actually. To mitigate this, I started a refactoring to separate the job management logic from the server package (more focused in the protocol). This separation will make testing easier, more testable, and will remove some global state.

**Comment by mperham** [comment]
:+1:  Your reservation reaper refactoring was a great example.
